---
layout: developer
title: 为插件开发做准备
references:
- url: http://www.oracle.com/technetwork/java/javase/downloads/index.html # TODO redundant?
  title: Oracle Java downloads site
- url: https://maven.apache.org # TODO redundant?
  title: Apache Maven website
---

- link:../prepare[*Step 1: 为插件开发做准备*]
- link:../create[Step 2: 创建一个插件]
- link:../run[Step 3: 构建并运行一个插件]
- link:../extend[Step 4: 扩展你的插件]

== 下载并安装 JDK

// TIMEBASED
Jenkins 是基于 Java 开发的。想要构建 Jenkins 插件，你首先需要下载 Java 开发工具（JDK）。
最新的 Jenkins 版本需要运行 JDK 8 上，这也是我们要在这里使用的版本。

从 link:http://www.oracle.com/technetwork/java/javase/downloads/[Oracle 官网]免费下载并安装 JDK 8。

NOTE: 许多 Linux 发行版为 Oracle JDK 或 Open JDK 提供了更简单的安装和升级体验。
详细信息请查阅您的发行版的文档。
它甚至可能已经安装。
为了找到答案，请在命令提示符下键入 `javac -version`。

== 下载并安装 Maven

Jenkins 几乎都使用 Maven 构建，所以这也是我们将在本教程中使用的内容。

link:https://maven.apache.org[点击下载] Maven。
请确保下载名称中带有 `bin` 的其中一个文件。
`src` 表示一个源分布

// TODO: 为每个操作系统包含子部分
NOTE: 许多 Linux 发行版为 Maven 提供了更简单的安装和升级体验包。
详细信息请查阅您的发行版的文档。
在 MacOS 上，link:https://brew.sh/[Homebrew] 软件包管理器提供 Maven 软件包。
确保下载 3.3.9 或更新的 Maven 版本。
// TIMEBASED

下载并解压 Maven，并记录它的位置。
您现在有以下选项:

. 将提取目录 `bin/` 子目录添加到 `PATH` 中。
  这会让你使用 `mvn` 来调用 Maven。
  如何工作取决于你的操作系统和命令行。
. 总是使用 `mvn` 可执行文件的完整路径， 例如 `~/Applications/apache-maven/bin/mvn` 或 `C:\Program files\Maven\bin\mvn`

本教程的其余部分假定 Maven 在您的 `PATH` 上，但您也可以输入完整路径。

一旦下载并解压到某个地方，通过在命令提示符下输入以下内容，确保一切正常:

NOTE: MacOS上输入 `Terminal.app` , Windows 输入 `cmd.exe` , Linux 在任意 shell 中输入 。

[listing]
mvn -version

这会打印一些诊断输出，包括 Java 和 Maven 的版本，以及 Maven 找到哪个 Java 版本。
这里应该显示 Java 的 _1.8_ 版本，并列出 JDK 的路径。
如果不是这两种情况，请参阅 <<故障排除>>。

下一步: link:../create[创建你的第一个 Jenkins 插件]。

== 故障排除

NOTE: 没有适合你的东西？ 在 link:/chat[IRC] 或 link:/mailing-lists[jenkinsci-dev 邮件列表上]寻求帮助。
