---
layout: simplepage
title: "Jenkins 行为准则"
section: conduct
---

:toc:

本文档只说明 Jenkins 项目和社区的问题的提出和处理的方式，更多关于文化，哲学，价值观，目标，和组织架构等问题，请查看link:/zh/project/governance[管理文档]。


== 行为准则

为了培养出一个开放和受欢迎的社区，作为本项目的贡献者或者管理者（<<社区>> 和 link:/zh/project/governance[管理文档]），请尊敬所有那些提出问题或贡献的人，内容包括功能需求，文档更新，贡献代码以及相关的一切活动。

我们努力为本项目的参与者提供一个不受经验水平，性别，性别认同，性取向，身体，外貌，种族，年龄，宗教，民族等问题骚扰的环境。

例如，如下行为是不可接受的：

* 使用与性有关的言语或是图像，以及不受欢迎的性骚扰
* 人身攻击及政治攻击
* 捣乱/煽动/造谣的行为或进行侮辱/贬损的评论
* 公开或私下的骚扰
* 在没有明确许可的情况下，公布他人的具体地址或网络联系方式
* 不道德或不专业的行为

Jenkins 管理者有权力和义务及时的对他们认为不适当的，对他人有威胁，冒犯，和伤害性的行为进行禁止。插件和其他维护者也同样需要移除和拒绝不适当的评论，提交，代码，文档，和问题等内容。

Jenkins 管理者应该公平一致的实施此准则管理项目。不按上述行为执行的参与者可能会被永久的从本项目踢出。

当个人代表本项目或者社区的时候，也应该在其他场合准守上述行为准则。

实质性的滥用，骚扰或者不可以接受的行为可以给通过 jenkinsci-board@googlegroups.com 报告给  link:https://wiki.jenkins-ci.org/display/JENKINS/Governance+Board[Jenkins 管理者]。
所有的投诉都会被讨论和调查，适当情况下会公布结果。管理者有责任为相关事件的报告者保密。

本行为准则采纳自
link:http://contributor-covenant.org/[Contributor Covenant]， 1.3.0 版本，
详情：link:http://contributor-covenant.org/version/1/3/0/[contributor-covenant.org/version/1/3/0/]。


=== 社区

==== 代码管理

* GitHub
** 组织
*** link:https://github.com/jenkinsci[jenkinsci]
*** link:https://github.com/jenkinsci-cert[jenkinsci-cert]
*** link:https://github.com/jenkins-infra[jenkins-infra]
** Commits
** Pull requests
** Issues
** Wikis
* Subversion

感谢来自技术问题的批评和建议，但是请避免没有用的批评，如只是提出对某个问题，而没有相关问题改善的意见和建议。
(link:https://golang.org/conduct#values[Go Lang 行为准则])

==== 网站

所有的内容都托管在 link:https://jenkins-ci.org/[jenkins-ci.org] 以及其子域名上，如:

* link:https://issues.jenkins-ci.org/[issues.jenkins-ci.org]
* link:https://wiki.jenkins-ci.org/[wiki.jenkins-ci.org]
* link:http://lists.jenkins-ci.org/mailman/listinfo[lists.jenkins-ci.org]

==== 邮件组

使用 Google group （见
link:/mailing-lists[这里]）且自托管在 link:http://lists.jenkins-ci.org/mailman/listinfo[lists.jenkins-ci.org].

==== IRC 频道

见文档
link:https://wiki.jenkins-ci.org/display/JENKINS/IRC+Channel[IRC Channel] wiki
页等，如：

* `#jenkins`
* `#jenkins-meeting`
* `#jenkins-infra`
* `#jenkins-community`

==== 活动

* link:https://wiki.jenkins-ci.org/display/JENKINS/Office+Hours[Office Hours]
* link:https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Area+Meetup[Jenkins
  Area Meetup]
* 官方活动 (如：
  link:https://fosdem.org[FOSDEM] , link:https://socallinuxexpo.org/[SCaLE])
* 其他 Jenkins 团体（如：会议，聚会，其他非官方论坛）也需要准守上述行为准则。且请提供团体的主办者信息和反馈方式。


== 举报

如果有人违规了，可以发送邮件到 jenkinsci-board@googlegroups.com，它会被 link:https://wiki.jenkins-ci.org/display/JENKINS/Governance+Board[管理人员]看到。

请注意，每个人的时间是有限的，所以反馈的时候请尽可能的提供详细的信息。

如果你认为管理者有违反上述准则的，可以发送邮件个其他管理者，联系信息见：link:https://wiki.jenkins-ci.org/display/JENKINS/Governance+Board[管理人员]

== 违规处理

视情况轻重，管理人员会采取不同措施。一般会私下里沟通解决，不会发布公告。这么做也是为了保护事件相关人员免受人身攻击。

=== 谴责

如果影响较小，管理者会告知相关人员，他的行为是错误的且需要改变。

=== 惩戒

如果问题较为严重，相关人员会被禁止活动一段时间，包括内容：

* link:https://wiki.jenkins-ci.org/display/JENKINS/IRC+Channel[IRC 频道]
* 邮件组
* Pull requests
* 活动
* 其他

这样做的目的是为了明确的告知相关人员他的行为是不可以接受的，减少其行为的影响，让其他人员也可以引以为戒。

=== 封禁

如果惩戒不能解决问题，已经达到了很严重的程度，则相关人员会被踢出至少 12 个月。12 个月之后可以要求管理人员取消封禁。

内容包括但不限于：

*  IRC Channels 封禁
*  删除 LDAP 账户
*  组织内屏蔽其 Github 账号
*  邮件列表内移除



注意: 本页引用自
link:https://wiki.jenkins-ci.org/display/JENKINS/Code+of+Conduct[Code of
Conduct] wiki 页， 作为 `v15` , 在管理人员内通过
link:http://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-01-06-19.01.html[2016-01-06]
