---
layout: project
title: "基础设施"
section: projects
tags:
- infra
- infrastructure
---

作为一个独立的开源项目，Jenkins 维护了大部分自身的基础设施，包括维持项目运行所需的各种服务。所谓“基础设施”其跨度从运行虚拟机和分布式网络，到帮助 Jenkins 核心和插件更加高效开发的专用应用开发。

== 概览

大部分情况下，Jenkins 项目的基础设施通过 link:https://github.com/jenkins-infra/jenkins-infra[Puppet 仓库] 来管理和编排。

== 应用

Jenkins 项目通过运行许多的脚本和应用来推进项目目标。虽然下文并未罗列出所有的脚本和应用，但已列举出的覆盖了足够的范围/大小，值得一览。

=== 账户应用

link:https://github.com/jenkins-infra/account-app[GitHub 地址]

我们使用 LDAP 给跨 Jenkins 项目的多个服务提供中心化的身份管理。为了给项目成员提高一系列自助服务，账户应用创建后支持用户登录并在 LDAP 中编辑部分用户属性。生产环境的账户应用实例在这里 link:https://accounts.jenkins.io[accounts.jenkins.io] 。

=== IRC 机器人

link:https://github.com/jenkins-infra/ircbot[GitHub 地址]

Jenkins IRC 主频道（ 
link:http://freenode.net[Freenode]
网络上的 `#jenkins`）使用了一个管理员机器人 "jenkins-admin" ，这样一些项目维护工作可以通过社区来完成。任何人在频道中通过一个为可信用户开发的 IRC术语 “voice” 即可唤起该机器人。 

link:/projects/infrastructure/ircbot[了解 IRC 机器人的更多信息].


=== Jenkins

Jenkins 项目顺理成章地在 Jenkins 上运行自身的一系列构建/测试/发布任务，以及一些周期性或批处理任务。唯一的公开 Jenkins 集群在这里 link:https://ci.jenkins.io[ci.jenkins.io] 。 


参考：

* link:https://github.com/jenkins-infra/documentation/blob/master/ci.adoc[Available nodes/tools/labels/etc]
* link:https://github.com/jenkinsci/puppet-jenkins[puppet-jenkins module]

=== Plugin 站点

link:https://github.com/jenkins-infra/plugin-site-api[GitHub 地址]

=== 评分 app

link:https://github.com/jenkins-infra/rating[GitHub 地址]
