==== 加强安全性以防止 XSS 漏洞

Jenkins 中的视图应用了一种安全性强化，以防止跨站点脚本漏洞被利用。
在极少数情况下，这会导致视图中某些内容转义两次（通常会导致可见的 HTML 实体）。

我们认为这些影响是插件的一个 bug ，要么选择跳过默认测试套件，要么使用过时的工具链。
我们在 https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+2018-10-10+Stapler+security+hardening[the Jenkins wiki] 上跟踪已知受影响的插件及其状态。

作为临时解决方法，可以通过将系统属性 `org.kohsuke.stapler.jelly.CustomJellyContext.escapeByDefault` 设置为 `false` 来禁用此强化。 

==== 升级后首次启动时的登录告警

https://issues.jenkins-ci.org/browse/JENKINS-53998[JENKINS-53998]

第一次启动 Jenkins 2.138.2 ，如果插件 jobConfigHistory[Job Config History Plugin] 安装的是 2.19 之前的版本，则可能会记录如下警告。

----
Oct 10, 2018 2:27:17 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=jenkins.telemetry.Correlator, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Tried proxying jenkins.telemetry.Correlator to support a circular dependency, but it is not an interface.
----

这似乎不会导致进一步的问题。
Jenkins 的后续重新启动将不再记录此警告。 

==== 安全强化影响 GitHub OAuth 插件的使用

https://issues.jenkins-ci.org/browse/JENKINS-54031[JENKINS-54031]

2.138.2 和 2.146 中的安全强化可能导致使用 github-oauth[GitHub OAuth Plugin] 插件访问任务时出现问题，由于插件的 bug 。

作为解决方法，可以通过将 https://wiki.jenkins.io/display/JENKINS/Features+controlled+by+system+properties[Java system properties] `hudson.model.AbstractItem.skipPermissionCheck` 和 `hudson.model.Run.skipPermissionCheck` 设置为 `true` 来暂时禁用部分安全强化。 

IMPORTANT: 请查看 link:/security/advisory/2018-12-05/#SECURITY-595[description of SECURITY-595 in the 2018-12-05 security advisory] 获取有关此解决方案的重要信息。
