[#SECURITY-1072]
==== 用户记录的迁移

link:/security/advisory/2018-12-05/#SECURITY-1072[SECURITY-1072]

应用此升级后， Jenkins 将用户记录迁移到稍有不同的存储格式，该存储格式使用中央索引将用户 ID 映射到目录名称。
这是一个向前不兼容的更改， 因此较旧的 Jenkins 版本将无法处理新的存储格式。 
强烈建议您在升级之前至少备份 `$JENKINS_HOME/users/` 目录。

如果 Jenkins 崩溃或在启动过程中被杀死， 则迁移可能不完整，可能使一部分用户记录不可用。
要确定是否属于这种情况，请检查 `$JENKINS_HOME/users/users.xml` 文件是否存在。
如果不存在，但是用户目录已按如下所述重命名，则迁移被中断。
在这种情况下，如果没有备份可用，我们建议检查 Jenkins 系统日志，并使用其中的信息将目录恢复为以前的名称。
日志条目看起来类似于以下消息：

----
INFO: 迁移用户 'admin' 从 'users/admin/' 到 'users/admin_6635238516816951048/'
----

在这种情况下，在 Jenkins 非运行状态下，将目录 `$JENKINS_HOME/users/admin_6635238516816951048/` 重命名为 `$JENKINS_HOME/users/admin/`。
对日志中列出的所有其他用户目录重复此操作。
完成上述所有操作将撤消部分迁移。
Jenkins 将在下次启动时重新运行它。

如果更新后 Jenkins 需要降级并成功应用了用户目录迁移，请执行上述所有操作，并同时删除 `$JENKINS_HOME/users/users.xml` 文件。
这将还原迁移并将所有用户记录还原为与 Jenkins 2.138.3 及更早版本兼容的格式。
IMPORTANT: 请注意，降级 Jenkins 通常不受支持，并且可能由于与迁移无关的原因而失败。


[#SECURITY-595]
==== HTTP 请求路由的新限制

link:/security/advisory/2018-12-05/#SECURITY-595[SECURITY-595]

Stapler web 框架中的一个设计缺陷允许通过访问特定 URLs 来访问原本不打算通过这种方式调用的字段和方法。
link:/security/advisory/2018-12-05/#SECURITY-595[For further details, see the security advisory].

作为此安全修复的副作用，某些 HTTP 请求将不再像以前那样工作。
这通常会导致 `HTTP 404 Not Found` 响应，尽管一小部分请求将成功，但响应将与应用程序修复之前完全不同。
无论何时发生， Jnkins都会向Jenkins 系统日志中写入类似于以下内容的消息： 

----
WARNING: New Stapler routing rules result in the URL "/example" no longer being allowed. If you consider it safe to use, add the following to the whitelist: "method hudson.model.Hudson doExample". Learn more: https://jenkins.io/redirect/stapler-routing
----

如果这是由于合法使用 Jenkins UI 造成的，则可以将受影响的签名添加到已批准的签名列表中。
为此，请以管理员身份在 Jenkins 脚本控制台中运行以下命令：

----
jenkins.security.stapler.StaticRoutingDecisionProvider.get().add('method hudson.model.Hudson doExample')
----

这将在 Jenkins 主目录中创建一个名为 `stapler-whitelist.txt` 的文件，并添加指定的条目。
也可以手动修改此文件，但如果 Jenkins已经在运行，则需要在应用任何更改后执行以下脚本： 

----
jenkins.security.stapler.StaticRoutingDecisionProvider.get().reload()
----

我们在link中跟踪已知受影响的插件及其状态： https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+the+SECURITY-595+fix[the Jenkins wiki]。
