==== 控制台记录安全修复

https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2017-02-01[SECURITY-382]

控制台记录，通常是粗体或彩色的附加功能，可以通过插件创建日志，例如 plugin:timestamper[Timestamper] or plugin:ansicolor[AnsiColor], 在升级到Jenkins 2.43或2.32.2之前创建的文件将因安全原因不再被加载。
要恢复先前（不安全）的行为，请设置系统属性 `hudson.console.ConsoleNote.INSECURE` 为`true` 如 link:https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties[ wiki 页面]所述。

plugin:maven-plugin[Maven 集成插件] 2.14 及更早版本中使用 Maven 3.0.x 构建的 Maven 项目将创建控制台记录，这些笔记不能再由 Jenkins 读取，因此其构建输出的部分内容不会被着色/粗体显示。
这对自由式项目不影响。


==== 新的加密秘密格式

https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2017-02-01[SECURITY-304]

加密的秘密不是 AES-128 CBC，而是随机 IV，而不是没有 IV 的 AES-128 ECB。 因此加密秘密的格式已经改变。
尽管仍然可以读取现有秘密，但保存配置文件将导致以新格式重新加密存储的秘密。
在更改 Jenkins 存储的密码作为密钥后，单击 _Apply_ 重复提交相同的表单，现在会导致配置文件被更改。


==== 重新键入备份文件已删除

https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2017-02-01[SECURITY-376]

重新键入，为 Jenkins 1.480.2 安全更新实施的一个流程，并且仅在从版本 1.480.1 或 1.497 或更低版本升级 Jenkins 时执行，并留下没有限制性文件访问权限的备份文件。
在应用 2.32.2 更新后的第一次重新启动时，Jenkins 将删除这些备份文件（如果存在）。

如果您依靠文件系统权限来保护存储在 Jenkins 中的秘密，并且正在运行最初运行 Jenkins 1.480.1 或 1.497（或更早版本）的实例，那么请考虑更改 Jenkins 中存储的任何秘密。

如果您依靠文件系统权限来保护存储在 Jenkins 主目录备份中的秘密，建议您从所有备份中删除 `JENKINS_HOME/jenkins.security.RekeySecretAdminMonitor/backups` 目录。

==== 远程黑名单添加

https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2017-02-01[SECURITY-383]

禁止在 XStream 和 Java 对象序列化中使用的类的远程黑名单已被扩展。 这些条目已被添加:

   ^javax[.]imageio[.].*
   ^java[.]util[.]ServiceLoader$
   ^java[.]net[.]URLClassLoader$

预计不会合法使用这些类型，但可能。 link:/doc/upgrade-guide/2.19/#upgrading-to-jenkins-lts-2-19-3[Jenkins 2.19.3升级指南] 中先前的建议仍然适用。

==== 不能通过 GET 创建用户

https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2017-02-01[SECURITY-406]

Jenkins管理员可以通过访问URL `/user/example` 来创建用户。 这样做会为（此 URL）创建一个 ID 为 `example` 的新用户，如果它以前不存在的话。

虽然方便，但这构成了一个 link:https://en.wikipedia.org/wiki/CSRF[跨站请求伪造]漏洞，因为 Jenkins 管理员可能被骗入创建数百个（并非总是短暂的）用户。
因此此功能已被删除。

在使用内部 Jenkins 用户数据库时，可以通过 _Manage Jenkins » Manage Users_ 创建新用户。

要恢复先前（不安全）的行为，请设置系统属性`hudson.model.User.allowUserCreationViaUrl`为 `true` ，如 link:https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties[wiki 页面]所述。

==== 安全警告管理监视器

https://issues.jenkins-ci.org/browse/JENKINS-40494[JENKINS-40494]

Jenkins现在将在安装的组件（插件或核心）出现安全问题时显示警告。
这些警告还会显示在插件管理器的 _Available_ 和 _Updates_ 标签中，以在安装易受攻击的插件或更新为易受攻击的版本之前发出警告。
由于这些警告是由您配置的更新站点发布的，因此通常每天更新一次。 请注意，第三方更新站点可能不支持此功能（尚未）。

==== Winstone-Jetty 支持在 Java 8 上创建临时证书

https://issues.jenkins-ci.org/browse/JENKINS-25333[JENKINS-25333]

在 Java 8上运行时，嵌入式 Winstone-Jetty 容器现在支持临时SSL证书生成。

但是，此功能使用内部 Oracle JRE API，因此将来可能会随时中断。
因此，仍建议管理员手动创建自签名证书并使用它们。
