==== 需要 Java 8 

Jenkins 2.60.1是第一个需要 Java 8的 LTS 版本。
这适用于主人和代理人。

如果您将 Maven 插件用于基于 Maven 的版本，请注意为其选择的 JDK 至少需要 Java 8 以及此更改。
如果配置了较旧的 JDK，则 Jenkins 会自动尝试查找更新的JDK。
如果您的Maven项目需要使用JDK 7构建，请考虑将它们转换为自由式项目，或者查看Maven工具链。

如果你使用的是 plugin:ssh-slaves[SSH Slaves] 插件, 它可能会尝试在不支持的JRE上启动代理进程，从而导致失败。
如果发生这种情况，请确保在代理系统上安装受支持的 JRE（8或更高版本），并使其在PATH上可用。
如果您依赖 SSH Slaves 插件在代理上自动安装 Java 运行时，请在升级到 SSH Slaves 1.17 或更高版本（建议 1.20，请参阅下文）后删除代理根目录中的现有内容。

==== Groovy 2.4.8 升级

https://issues.jenkins-ci.org/browse/JENKINS-33358[JENKINS-33358],
https://issues.jenkins-ci.org/browse/JENKINS-42189[JENKINS-42189]

Groovy 已经升级到 2.4.8 来修复内存泄漏。

如果您使用流水线，请注意您需要更新 plugin:workflow-cps[流水线: Groovy] 插件到版本 2.28 或更高版本。

==== Trilead SSH 库升级

https://issues.jenkins-ci.org/browse/JENKINS-42959[JENKINS-42959]

与 Jenkins 捆绑在一起的 Trilead SSH 库已经升级。
如果您使用SSH从属插件通过SSH连接代理，则升级导致的已知问题可能导致连接失败。

plugin:ssh-slaves[SSH Slaves] 插件应升级到 1.20 或更新版本。

==== RPM包装不再执行递归 `chown`

https://issues.jenkins-ci.org/browse/JENKINS-23273[JENKINS-23273]

RPM打包后安装步骤用于在 `JENKINS_HOME` 和其他目录上执行递归 `chown` 以确保正确的所有权。
特别是在 `JENKINS_HOME` 的情况下，这可能会导致运行时间非常长的安装和更新。

如果Jenkins主目录由不同于用户运行的用户所拥有，那么该优化只会执行递归`chown`。

NOTE: `JENKINS_HOME` 内的所有文件预计将由 Jenkins 用户拥有，可读和可写。

==== Windows 服务升级

https://issues.jenkins-ci.org/browse/JENKINS-39231[JENKINS-39231],
https://issues.jenkins-ci.org/browse/JENKINS-39237[JENKINS-39237]

Jenkins 2.60.1 包含 Windows 服务管理的重大改进，这些改进是从 Jenkins 2.50 到 2.60 引入的。
尤其是, link:https://github.com/kohsuke/winsw[Windows服务包装器 (WinSW)] 已更新至 2.x 基准。

新安装的代理和主实例将自动获取功能，但现有实例需要额外的配置。

查阅 link:windows[升级 Windows 主控和代理] 了解更多。
