---
layout: documentation
title:  Jenkins 升级指南
notitle: true
---

== 升级到 Jenkins LTS 2.235.x

每个部分涵盖了从之前的 LTS 版本升级，2.235.1 的部分涵盖了自 2.222.4 以来的升级。 

=== 升级到 Jenkins LTS 2.235.3

==== 仓库签名密钥更新

从 Jenkins LTS link:/changelog-stable/#v2.235.3[2.235.3] 版开始，将使用与每周仓库签名相同的 GPG 密钥对稳定的仓库进行签名。 Linux 系统管理员**必须**在 Linux 服务器上安装新的签名密钥，**然后**再安装 Jenkins 2.235.3。

===== Debian/Ubuntu

使用以下命令更新兼容 Debian 的操作系统（Debian、Ubuntu 和 Linux Mint Debian Edition 等）：

.Debian/Ubuntu
[source,bash]
----
# wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
----

===== Red Hat/CentOS

Update Red Hat compatible operating systems (Red Hat Enterprise Linux, CentOS, Fedora, Oracle Linux, Scientific Linux, etc.) 使用以下命令更新与 Red Hat 兼容的操作系统（Red Hat Enterprise Linux、CentOS、Fedora、Oracle Linux 和 Scientific Linux 等）：

.Red Hat/CentOS
[source,bash]
----
# rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
----

有关更多详细信息，请参见link:/blog/2020/07/27/repository-signing-keys-changing/[博客文章]。


=== 升级到 Jenkins LTS 2.235.2

升级没有需要特别注意的内容。


=== 升级到 Jenkins LTS 2.235.1

==== 插件管理改进

插件管理界面包括重大改进。
这些改进包括对“可用”标签的更改。

先前的“可用”标签列出了所有可用的插件，然后根据“搜索”字段中的值进行了过滤。
现在，“可用”选项卡中没有列出插件，直到用户在“搜索”字段中输入值为止。
以前浏览超过 1000 多个插件以找到其插件的用户现在需要在搜索字段中输入一个值。

==== 删除自动刷新

link:https://issues.jenkins-ci.org/browse/JENKINS-19828[JENKINS-19828]

Jenkins 2.235.1 已删除“启用自动刷新”功能。
如果用户在昂贵的页面上启用自动刷新并使浏览器在该页面上打开，则自动刷新会导致严重的 Jenkins 性能问题。
自动刷新通过要求必须在下一次刷新之前提交表单或输入的数据将丢失来中断表单数据输入。
自动刷新会中断可扩展列表视图。

页面刷新扩展可用于流行的 Web 浏览器，例如 Google Chrome 和 Mozilla Firefox。
需要自动刷新 Jenkins 页面的用户应安装这些扩展程序之一。
