---
layout: documentation
title:  Jenkins 升级指南
notitle: true
---

== 升级到 Jenkins LTS 2.235.x

每个部分涵盖了从之前的 LTS 版本升级，2.235.1 的部分涵盖了自 2.222.4 以来的升级。 

=== 升级到 Jenkins LTS 2.235.5

==== Docker Alpine 镜像大修

基于 Alpine 的 Jenkins Docker 镜像（`jenkins/jenkins:lts-alpine` 和类似镜像）的基础镜像和各种代理程序镜像已被替换，现在是基于 AdoptOpenJDK 项目提供的镜像。

有关详细信息，请参见发行说明:

// TODO Release note for core image
* https://github.com/jenkinsci/docker-agent/releases/tag/4.3-8
* https://github.com/jenkinsci/docker-inbound-agent/releases/tag/4.3-9
* https://github.com/jenkinsci/docker-ssh-agent/releases/tag/3.0.0


=== 升级到 Jenkins LTS 2.235.4

==== New Windows Installer

Beginning with Jenkins LTS release link:/changelog-stable/#v2.235.3[2.235.3], the same Windows installer is used in the stable release as has been used since April 2020 in the weekly release.
The new Windows installer was announced in a link:/blog/2019/02/01/windows-installers/[blog post].

Jenkins administrators on Windows may choose to continue using and upgrading their existing installation using the mechanism in the Jenkins UI, or they may choose to migrate to the new Windows installer.

===== Upgrade with existing installation

Jenkins administrators on Windows are offered new Jenkins versions from within the "Manage Jenkins" page of their installation.
After the initial installation of Jenkins on Windows, administrators perform upgrades through the "Manage Jenkins" page.
Administrators generally do not use the Jenkins MSI installer to perform a Jenkins upgrade because the upgrade is simple and easy from within Jenkins itself.

Administrators that choose to continue using their existing installation will continue to be able to upgrade to new Jenkins versions.
Settings in the Jenkins installation can be modified by editing the `jenkins.exe.config` file and other configuration files.

In this configuration, Jenkins will continue to use the 32 bit Java Runtime Environment that was included with the previous installer unless `jenkins.exe.config` has been modified to use a 64 bit Java Runtime Environment.
It will similarly continue to use the default port and service account unless it has been modified locally.

===== Upgrade with new Windows Installer

The new Windows installer provides the following additional features:

* Choose a 64 bit Java 8 or 64 bit Java 11 installation to run Jenkins
* Choose the port that Jenkins will use
* Choose the user account and password that will run the Jenkins service

In addition to those choices, the Jenkins home directory is created in the standard AppData location rather than in `C:\Program Files (x86)\Jenkins`.
You'll find the Jenkins home directory in the `%LocalAppData%` of the user account that runs the Jenkins service.
For example, if the user account running the Jenkins service is named `jservice`, then the Jenkins home directory will be in `C:\Users\jservice\AppData\Local\Jenkins.jenkins`.
Once Jenkins is running, the 'System Information' page within 'Manage Jenkins' displays the properties and variables that describe the Jenkins installation.

Upgrading an existing Windows installation to the new installer requires:

. Stop and disable the existing Jenkins service from the Windows Service Manager
. Run the new installer to create the new installation with desired settings
. Stop the newly installed Jenkins service
. Copy existing Jenkins configuration files to the new Jenkins home directory
. Start the newly installed Jenkins service
. Confirm newly installed Jenkins service is behaving as expected

See the link:/blog/2019/02/01/windows-installers/[Windows installer blog post] for more details.


=== 升级到 Jenkins LTS 2.235.3

==== 仓库签名密钥更新

从 Jenkins LTS link:/changelog-stable/#v2.235.3[2.235.3] 版开始，将使用与每周仓库签名相同的 GPG 密钥对稳定的仓库进行签名。 Linux 系统管理员**必须**在 Linux 服务器上安装新的签名密钥，**然后**再安装 Jenkins 2.235.3。

===== Debian/Ubuntu

使用以下命令更新兼容 Debian 的操作系统（Debian、Ubuntu 和 Linux Mint Debian Edition 等）：

.Debian/Ubuntu
[source,bash]
----
# wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
----

===== Red Hat/CentOS

Update Red Hat compatible operating systems (Red Hat Enterprise Linux, CentOS, Fedora, Oracle Linux, Scientific Linux, etc.) 使用以下命令更新与 Red Hat 兼容的操作系统（Red Hat Enterprise Linux、CentOS、Fedora、Oracle Linux 和 Scientific Linux 等）：

.Red Hat/CentOS
[source,bash]
----
# rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
----

有关更多详细信息，请参见link:/blog/2020/07/27/repository-signing-keys-changing/[博客文章]。


=== 升级到 Jenkins LTS 2.235.2

升级没有需要特别注意的内容。


=== 升级到 Jenkins LTS 2.235.1

==== 插件管理改进

插件管理界面包括重大改进。
这些改进包括对“可用”标签的更改。

先前的“可用”标签列出了所有可用的插件，然后根据“搜索”字段中的值进行了过滤。
现在，“可用”选项卡中没有列出插件，直到用户在“搜索”字段中输入值为止。
以前浏览超过 1000 多个插件以找到其插件的用户现在需要在搜索字段中输入一个值。

==== 删除自动刷新

link:https://issues.jenkins-ci.org/browse/JENKINS-19828[JENKINS-19828]

Jenkins 2.235.1 已删除“启用自动刷新”功能。
如果用户在昂贵的页面上启用自动刷新并使浏览器在该页面上打开，则自动刷新会导致严重的 Jenkins 性能问题。
自动刷新通过要求必须在下一次刷新之前提交表单或输入的数据将丢失来中断表单数据输入。
自动刷新会中断可扩展列表视图。

页面刷新扩展可用于流行的 Web 浏览器，例如 Google Chrome 和 Mozilla Firefox。
需要自动刷新 Jenkins 页面的用户应安装这些扩展程序之一。
