---
layout: documentation
title:  Jenkins 升级指南
notitle: true
---

== 升级到 Jenkins LTS 2.263.x

每个部分涵盖了从之前的 LTS 版本升级，2.263.1 的部分涵盖了自 2.249.3 以来的升级。 

=== 升级到 Jenkins LTS 2.263.1

==== SSHD 密钥交换和 MAC 算法

link:https://github.com/jenkinsci/sshd-module/blob/master/README.adoc[Jenkins SSHD 模块] 已在此版本中升级。
默认情况下，升级会禁用不推荐使用的密钥交换算法和不推荐使用的 MAC 算法。

如果管理员需要一种或多种不推荐使用的算法，则可以使用link:/doc/book/managing/system-properties/[系统属性]启用。
请注意，通常认为这些系统属性不受支持，并且可以随时删除。

* `org.jenkinsci.main.modules.sshd.SSHD.excludedKeyExchanges` 是用逗号分隔的要禁用的密钥交换算法字符串。
  默认情况下，这将禁用基于SHA-1的算法，因为它们不再被认为是安全的。
  使用空字符串禁用任何算法。
  可以使用link:/doc/book/system-administration/viewing-logs/[日志]在 `FINE` 级别上初始化期间的 `org.jenkinsci.main.modules.sshd.SSHD` 来查看受支持、已启用和已禁用算法的名称。
* `org.jenkinsci.main.modules.sshd.SSHD.excludedMacs` 是用逗号分隔的要禁用的 HMAC 算法字符串。
  默认情况下，这将禁用 MD5 和基于 SHA-1 的截断算法，因为它们不再被认为是安全的。
  使用空字符串禁用任何算法。
  可以使用link:/doc/book/system-administration/viewing-logs/[日志]在 `FINE` 级别上初始化期间的 `org.jenkinsci.main.modules.sshd.SSHD` 查看受支持、已启用和已禁用算法的名称。
