---
layout: pipelinesteps
title: "Anchore容器镜像扫描器插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Anchore容器镜像扫描器插件

plugin:anchore-container-scanner[在插件索引中查看此插件]

=== +anchore+: Anchore容器镜像扫描器
++++
<ul><li><code>name</code>
<div><div>
  Name of the file that contains a list of container images for anchore to analyze, evaluate policy, and run queries against. The format for each line is "imageId /path/to/Dockerfile", where the Dockerfile is optional. This file must be made available (created by a prior build step) to Anchore Container Image Scanner plugin. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>anchoreioPass</code> (optional)
<div><div>
  Your password for the associated username on https://anchore.io 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>anchoreioUser</code> (optional)
<div><div>
  Your username on https://anchore.io that has access to a custom policy bundle to sync with your local anchore installation 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>bailOnFail</code> (optional)
<div><div>
  If selected or set to 'true', the Anchore build step will cause the build to fail if the policy check result is STOP. Default value: 'true' 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>bailOnPluginFail</code> (optional)
<div><div>
  If selected or set to 'true', the Anchore build step will cause the build to fail if the plugin encounters an error. Default value: 'true' 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>bailOnWarn</code> (optional)
<div><div>
  If selected or set to 'true', the Anchore build step will cause the build to fail if the policy check result is WARN. Default value: 'false' 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>bundleFileOverride</code> (optional)
<div><div>
  Name of the file that contains a custom anchore policy bundle to be used by Anchore policy evaluation engine. If this file does not exist or the field is left blank, anchore will attempt to use any previously synced/cached policy bundles that you may have, or will fail evaluation if no bundle can be found or used. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>doCleanup</code> (optional)
<div><div>
  If selected or set to 'true', all images in the input file will be flushed from the Anchore database at the end of plugin execution. Default value: 'false' 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>engineRetries</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>globalWhiteList</code> (optional)
<div><div>
  Name of the file that contains a custom whitelist to be used by Anchore policy evaluation engine. If this file does not exist or the field is left blank, Anchore will use its default global whitelist. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>inputQueries</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>query</code>
<div><div>
  Any query that Anchore supports. Results of the query will be added to the anchore report upon plugin completion. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>policyEvalMethod</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>policyName</code> (optional)
<div><div>
  Name of the file that contains a custom policy to be used by Anchore policy evaluation engine. If this file does not exist or the field is left blank, Anchore will use its default policy. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useCachedBundle</code> (optional)
<div><div>
  Check this in order to use a previously synced policy bundle (if one exists) in the case where login to anchore.io or bundle sync fails for any reason. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>userScripts</code> (optional)
<div><div>
  Optional directory that contains user defined Anchore analyzer/gate/query modules that will be executed in addition to the built in analyzer/gate/queries modules. If this directory does not exist or the field is left blank, Anchore will run only its default modules. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
