---
layout: pipelinesteps
title: "Android Lint 插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Android Lint 插件

plugin:android-lint[在插件索引中查看此插件]

=== +androidLint+: 发布Android Lint结果
++++
<ul><li><code>canComputeNew</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>canResolveRelativePaths</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>canRunOnFailed</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>defaultEncoding</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedNewAll</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedNewHigh</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedNewLow</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedNewNormal</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedTotalAll</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedTotalHigh</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedTotalLow</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedTotalNormal</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>healthy</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pattern</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>shouldDetectModules</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>thresholdLimit</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unHealthy</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableNewAll</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableNewHigh</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableNewLow</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableNewNormal</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableTotalAll</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableTotalHigh</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableTotalLow</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableTotalNormal</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useDeltaValues</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>usePreviousBuildAsReference</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>useStableBuildAsReference</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
