---
layout: pipelinesteps
title: "Artifactory Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Artifactory Plugin

plugin:artifactory[View this plugin on the Plugins Index]

=== +AddInteractivePromotion+: Add Interactive promotion
++++
<ul><li><code>promotionConfig</code>
<ul><code>org.jfrog.hudson.pipeline.types.PromotionConfig</code>
</ul></li>
<li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
<li><code>displayName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +ArtifactoryGradleBuild+: run Artifactory gradle
++++
<ul><li><code>gradleBuild</code>
<ul><code>org.jfrog.hudson.pipeline.types.GradleBuild</code>
</ul></li>
<li><code>rootDir</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tasks</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>switches</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
</ul>


++++
=== +ArtifactoryMavenBuild+: run Artifactory maven
++++
<ul><li><code>mavenBuild</code>
<ul><code>org.jfrog.hudson.pipeline.types.MavenBuild</code>
</ul></li>
<li><code>pom</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>goals</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
</ul>


++++
=== +ConanAddRemote+: Add new repo to Conan config
++++
<ul><li><code>serverUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>conanHome</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +ConanAddUser+: Add new user to Conan config
++++
<ul><li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
<li><code>serverName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>conanHome</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +InitConanClient+: Create Conan Client
++++
<ul><li><code>client</code>
<ul><code>org.jfrog.hudson.pipeline.types.ConanClient</code>
</ul></li>
</ul>


++++
=== +MavenDescriptorStep+: Get Artifactory Maven descriptor
++++
<ul><li><code>pomFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>version</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>versionPerModule</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>failOnSnapshot</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>dryRun</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +RunConanCommand+: Run a Conan command
++++
<ul><li><code>command</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>conanHome</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildLogPath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
</ul>


++++
=== +artifactoryDistributeBuild+: Distribute build
++++
<ul><li><code>distributionConfig</code>
<ul><code>org.jfrog.hudson.pipeline.types.DistributionConfig</code>
</ul></li>
<li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
</ul>


++++
=== +artifactoryDownload+: Download artifacts
++++
<ul><li><code>spec</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
<li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
</ul>


++++
=== +artifactoryPromoteBuild+: Promote build
++++
<ul><li><code>promotionConfig</code>
<ul><code>org.jfrog.hudson.pipeline.types.PromotionConfig</code>
</ul></li>
<li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
</ul>


++++
=== +artifactoryUpload+: Upload artifacts
++++
<ul><li><code>spec</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
<li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
</ul>


++++
=== +collectEnv+: Collect environment variables and system properties
++++
<ul><li><code>env</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.Env</code>
</ul></li>
</ul>


++++
=== +deployArtifacts+: Deploy artifacts
++++
<ul><li><code>deployer</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
</ul>


++++
=== +dockerPullStep+: Artifactory docker pull
++++
<ul><li><code>image</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsConfig</code>
<ul><b>Nested Object</b>
<li><code>username</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>overridingCredentials</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
<li><code>host</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
</ul>


++++
=== +dockerPushStep+: Artifactory docker push
++++
<ul><li><code>image</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsConfig</code>
<ul><b>Nested Object</b>
<li><code>username</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>overridingCredentials</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
<li><code>host</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetRepo</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
<li><code>properties</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
</ul>


++++
=== +dockerPushWithProxyStep+: Artifactory docker push
++++
<ul><li><code>image</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsConfig</code>
<ul><b>Nested Object</b>
<li><code>username</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>overridingCredentials</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
<li><code>host</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetRepo</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
<li><code>properties</code>
<ul><code>java.lang.String></code>
</ul></li>
</ul>


++++
=== +getArtifactoryServer+: Get Artifactory server from Jenkins config
++++
<ul><li><code>artifactoryServerID</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +newArtifactoryServer+: Returns new Artifactory server
++++
<ul><li><code>url</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>username</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +newBuildInfo+: New buildInfo
++++
<ul></ul>


++++
=== +newGradleBuild+: New Artifactory gradle executor
++++
<ul></ul>


++++
=== +newMavenBuild+: New Artifactory maven
++++
<ul></ul>


++++
=== +publishBuildInfo+: Publish build Info to Artifactory
++++
<ul><li><code>buildInfo</code>
<ul><code>org.jfrog.hudson.pipeline.types.buildInfo.BuildInfo</code>
</ul></li>
<li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
</ul>


++++
=== +xrayScanBuild+: Xray build scanning
++++
<ul><li><code>xrayScanConfig</code>
<ul><code>org.jfrog.hudson.pipeline.types.XrayScanConfig</code>
</ul></li>
<li><code>server</code>
<ul><code>org.jfrog.hudson.pipeline.types.ArtifactoryServer</code>
</ul></li>
</ul>


++++
