---
layout: pipelinesteps
title: "AWS Lambda 插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== AWS Lambda 插件

plugin:aws-lambda[在插件索引中查看此插件]

=== +eventSourceLambda+: AWS Lambda事件源映射
++++
<ul><li><code>lambdaEventSourceBuildStepVariables</code>
<ul><b>Nested Object</b>
<li><code>awsRegion</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>functionName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>eventSourceArn</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsAccessKeyId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsSecretKey</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>functionAlias</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useInstanceCredentials</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
</ul>


++++
=== +invokeLambda+: AWS Lambda 调用
++++
<ul><li><code>lambdaInvokeBuildStepVariables</code>
<ul><b>Nested Object</b>
<li><code>awsRegion</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>functionName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>synchronous</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>awsAccessKeyId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsSecretKey</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>jsonParameters</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>envVarName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>jsonPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>payload</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useInstanceCredentials</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
</ul>


++++
=== +publishLambda+: AWS Lambda发布新版本和更新别名
++++
<ul><li><code>lambdaPublishBuildStepVariables</code>
<ul><b>Nested Object</b>
<li><code>awsRegion</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>functionARN</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>functionAlias</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>versionDescription</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsAccessKeyId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsSecretKey</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useInstanceCredentials</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
</ul>


++++
=== +deployLambda+: AWS Lambda d部署
++++
<ul><li><code>lambdaUploadBuildStepVariables</code>
<ul><b>Nested Object</b>
<li><code>awsRegion</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>functionName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>updateMode</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>alias</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactLocation</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsAccessKeyId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsSecretKey</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>createAlias</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>deadLetterQueueArn</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>enableDeadLetterQueue</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>environmentConfiguration</code> (optional)
<ul><b>Nested Object</b>
<li><code>environment</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>key</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>configureEnvironment</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>kmsArn</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>handler</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>memorySize</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>publish</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>role</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>runtime</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>securityGroups</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>subnets</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>timeout</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useInstanceCredentials</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
</ul>


++++
