---
layout: pipelinesteps
title: "AWS代码构建插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== AWS AWS代码构建插件

plugin:aws-codebuild[在插件索引中查看此插件]

=== +awsCodeBuild+: 调用AWS CodeBuild构建
++++
<ul><li><code>projectName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactLocationOverride</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactNameOverride</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactNamespaceOverride</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactPackagingOverride</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactPathOverride</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactTypeOverride</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsAccessKey</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsSecretKey</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildSpecFile</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildTimeoutOverride</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsType</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>envParameters</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>envVariables</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>gitCloneDepthOverride</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>proxyHost</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>proxyPort</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>region</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sourceControlType</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sourceVersion</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sseAlgorithm</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
