---
layout: pipelinesteps
title: "Azure Container Service Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Azure Container Service Plugin

plugin:azure-acs[View this plugin on the Plugins Index]

=== +acsDeploy+: Deploy to Azure Container Service / Kubernetes Service
++++
<ul><li><code>azureCredentialsId</code>
<div><div>
  The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul> 
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>resourceGroupName</code>
<div><div>
  Resource group of the target Azure Container Service. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>containerService</code>
<div><div>
  The name of the Azure Container Service. Refer to the following documentation on how to setup Azure Container Service: 
 <ul> 
  <li> <a href="https://docs.microsoft.com/en-us/azure/container-service/container-service-kubernetes-walkthrough" rel="nofollow"> Deploy Kubernetes cluster for Linux containers </a> </li> 
  <li> <a href="https://docs.microsoft.com/en-us/azure/container-service/container-service-dcos-quickstart" rel="nofollow"> Deploy a DC/OS cluster </a> </li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sshCredentialsId</code>
<div><div> 
 <p> The username and private key credential used to authenticate with the ACS clusters master node. This is the private key paired with the SSH RSA public key provided when you create the ACS cluster (see <a href="https://docs.microsoft.com/en-us/azure/container-service/container-service-deployment" rel="nofollow"> Deploy a Docker container hosting solution using the Azure portal </a>). </p> 
 <p> The username and key credentials can be updated from Azure Portal. Find the Virtual Machine for your ACS cluster master node from the portal, and you can update the credential from <b>SUPPORT + TROUBLESHOOTING &gt;&gt;&gt; Reset password</b> page. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>configFilePaths</code>
<div><div> 
 <p> The path patterns for the specific cluster (Kubernetes, DC/OS, Docker Swarm) configurations you want to deploy, in the form of <a href="https://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant glob syntax</a>. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>containerRegistryCredentials</code> (optional)
<div><div>
  All the credentials needed for pulling images from private repositories. Specify multiple entries if your deployments need to pull images from multiple, private repositories that require authentication. 
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>url</code>
<div><div>
  URL to the Docker registry you are using. May be left blank to use the public DockerHub registry (currently 
 <code>https://index.docker.io/v1/</code>). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>dcosDockerCredenditalsPathShared</code> (optional)
<div><div> 
 <p> Determine if the Docker credentials archive upload path specified above is shared among all the agents. </p> 
 <p> To ease the shared files access, we may create share file storage for all the DC/OS agent nodes as <a href="https://docs.microsoft.com/en-us/azure/container-service/container-service-dcos-fileshare" title="Create and mount a file share to a DC/OS cluster" rel="nofollow"> this documentation (Create and mount a file share to a DC/OS cluster) </a> suggests. With the help of the shared storage, we only need to upload the Docker credentials archive to the shared storage once, and all the agent nodes get the access to the resource immediately. </p> 
 <p> Check this option if the Docker credentials archive upload path is a shared storage path. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>dcosDockerCredentialsPath</code> (optional)
<div><div> 
 <p> The path on the DC/OS cluster agent nodes to store the docker credentials archive <code>docker.tar.gz</code>. Only absolute path is allowed here. Environment variable substitution is enabled for the path input. <i>Due to the limitation in the underlying Mesos fetcher used by Marathon, special characters that need URI escaping and the character set {single quote ('), back slash (\), nul (\0)}, are not allowed in the path, otherwise it will fail to load the resource before running the container.</i> </p> 
 <p> If not specified, the plugin will generate a path specific for the build with the following pattern. </p> 
 <pre><code>
/home/&lt;linuxAdminUser&gt;/acs-plugin-dcos.docker/&lt;unique-name-generated-for-the-build&gt;</code></pre> 
 <p> The plugin will generate the docker credentials archive with the credentials provided, and upload the archive to the given path for all the agents. You can use it to construct the URI used in your Marathon application definition. </p> 
 <pre><code>
"uris":  [
    "file://&lt;filled-path&gt;/docker.tar.gz"
]</code></pre> 
 <p> The URI will be exposed with the environment variable <code>$MARATHON_DOCKER_CFG_ARCHIVE_URI</code>. You can use this in your Marathon application definition when the "Enable Variable Substitution in Config" option is enabled. This helps when the upload path is not filled and generated by the build, or if the path changes frequently. </p> 
 <p> Note that if an archive exists in the target path already, the build will overwrite that file. </p> 
 <p> Reference: <a href="https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html" title="Using a Private Docker Registry" rel="nofollow"> Marathon: Using a Private Docker Registry </a> </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>enableConfigSubstitution</code> (optional)
<div><div>
  Substitute variables (in the form 
 <code>$VARIABLE</code> or 
 <code>${VARIABLE}</code>) in the configuration with values from Jenkins environment variables. 
 <p> This allows you to use dynamic values produced during the build in your Kubernetes or DC/OS configurations, e.g., a dynamically generated Docker image tag which will be used later in the deployment. </p>
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>secretName</code> (optional)
<div><div>
  The secret name that you can use in the Kubernetes Deployment configuration for the 
 <code>imagePullSecrets</code> entry. Environment variable substitution are supported for the name input, so you can use available environment variables to construct the name dynamically, e.g., 
 <code>some-secret-$BUILD_NUMBER</code>. The name should be in the pattern 
 <code>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*</code>, i.e., dot (.) concatenated sequences of hyphen (-) separated alphanumeric words. (See 
 <a href="https://kubernetes.io/docs/concepts/overview/working-with-objects/names/" title="Kubernetes Names" rel="nofollow"> Kubernetes Names</a>) 
 <p> If left blank, the plugin will generate a name based on the build name. </p>
 <p> The secret name will be exposed with the environment variable <code>$KUBERNETES_SECRET_NAME</code>. You can use this in your Kubernetes configuration to reference the updated secret when the "Enable Variable Substitution in Config" option is enabled. </p>
 <pre><code>
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: some.private.registry.domain/nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
</code></pre> 
 <p> Note that once the secret is created, it will only be updated by the plugin. You have to manually delete it when it is not used anymore. If this is a problem, you may use fixed name so every time the job runs, the secret gets updated and no new secret is created. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>secretNamespace</code> (optional)
<div><div>
  The Kubernetes namespace in which the secrets will be created with the credentials configured below. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>swarmRemoveContainersFirst</code> (optional)
<div><div>
  Stop and remove containers first. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
