---
layout: pipelinesteps
title: "Azure应用服务插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Azure应用服务插件

plugin:azure-app-service[在插件索引中查看此插件]

=== +azureWebAppPublish+: 发布Azure Web应用程序
++++
<ul><li><code>azureCredentialsId</code>
<div><div>
  The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul> 
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>appName</code>
<div><div>
  The Azure Web App name. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>resourceGroup</code>
<div><div>
  The resource group name that the app will be associated with. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>deleteTempImage</code> (optional)
<div><div>
  If checked, the intermediate docker image will be removed from your build agent after build succeeds. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>deployOnlyIfSuccessful</code> (optional)
<div><div>
  If checked, application will only be deployed to Azure if the build was successful. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>dockerFilePath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dockerImageName</code> (optional)
<div><div>
  The docker image name. Leave blank if you want to use the same name as it on Azure. 
 <br> Be sure to include the registry and account if any. See examples:
 <br> Docker hub format: &lt;username&gt;/&lt;name&gt; eg. bitname/mysql 
 <br> Azure registry format: &lt;namePrefix.azurecr.io&gt;/&lt;repo&gt; eg. xxx.azurecr.io/mysql, xxx.azurecr.io/yyy/mysql 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dockerImageTag</code> (optional)
<div><div>
  Tha tag for your image. It's recommended to use a different tag for every single build otherwise your previous images might be overridden. We suggest you to append the BuildNumber to your tag so you can easily know that with which image your web app is currently running. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dockerRegistryEndpoint</code> (optional)
<ul><b>Nested Object</b>
<li><code>url</code>
<div><div>
  URL to the Docker registry you are using. May be left blank to use the public DockerHub registry (currently 
 <code>https://index.docker.io/v1/</code>). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>filePath</code> (optional)
<div><div> 
 <p>The file paths that will be deployed.</p> 
 <p>You can use wildcards like <code>module/dist/**/*.py</code>. See the includes attribute of <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Ant fileset</a> for the exact format. Multiple files can be separated by '<code>,</code>'. The base directory is the workspace. You can only deploy files that are located in your workspace.</p> 
 <p>Examples:</p> 
 <ul> 
  <li> <p>Java</p> <pre><code>webapps/*.war</code></pre> <p>Note: For Java application, usually you should put your war file under the 'webapps' directory.</p> </li> 
  <li> <p>PHP</p> <pre><code>**/*.php,composer.json</code></pre> </li> 
  <li> <p>Python</p> <pre><code>**/*.py,requirements.txt</code></pre> </li> 
  <li> <p>Node.js</p> <pre><code>**/*.js,package.json,process.json</code></pre> </li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>publishType</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>slotName</code> (optional)
<div><div> 
 <p>If not blank, will deploy to this deployment slot instead of the default production slot.</p> 
 <p>See <a href="https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-staged-publishing" rel="nofollow">this article</a> for more details.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sourceDirectory</code> (optional)
<div><div>
  Source directory relative to the workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetDirectory</code> (optional)
<div><div>
  Target directory relative to the site root. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
