---
layout: pipelinesteps
title: "BearyChat Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== BearyChat Plugin

plugin:bearychat[View this plugin on the Plugins Index]

=== +bearychatSend+: Send BearyChat Message
++++
<div><div>
  Simple step for sending a BearyChat message to specified channel.
 <br> Use the advanced settings to override the BearyChat Plugin global configuration to include: 
 <code>webhook</code> and 
 <code>channel</code>.
 <br> Please see the BearyChat Plugin global configuration for more details on the fields. Usage Example:
 <br> 
 <code> bearychatSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (&lt;${env.BUILD_URL}|Open&gt;)" </code> 
</div></div>
<ul><li><code>message</code>
<div><div>
  This is the main text in a message attachment, and can contain standard message markup. The content will automatically collapse if it contains 700+ characters or 5+ linebreaks, and will display a "Show more..." link to expand the content. Message may include global variables, for example environment and currentBuild variables:
 <br> 
 <code> bearychatSend "Started [${env.JOB_NAME} #${env.BUILD_NUMBER}](${env.BUILD_URL})" </code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>attachmentText</code> (optional)
<div><div>
  Add an 
 <b>optional</b> attachment text for BearyChat Message. 
 <code>bearychatSend message: "Job ${env.JOB_NAME} Failed", color: "#ff0000", attachmentText: "Exception: NullPointerException"</code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>channel</code> (optional)
<div><div>
  Allows overriding the BearyChat Plugin channel specified in the global configuration.
 <br> 
 <code>bearychatSend channel: "#channel-name", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>color</code> (optional)
<div><div>
  An 
 <b>optional</b> value that can either be one of 
 <b>green</b>, 
 <b>red</b>, 
 <b>grey</b>, 
 <b>yellow</b>, or any 
 <b>hex color code</b> (eg. #439FE0). This value is used to color the border along the left side of the message attachment. (So you must use with `attachmentText`)
 <br> 
 <code>bearychatSend color: "#439FE0", attachmentText: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failOnError</code> (optional)
<div><div>
  If set to true, then the step will abort the Workflow run if there is an error sending message.
 <br> 
 <code>bearychatSend failOnError: true, message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>notification</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>title</code> (optional)
<div><div>
  Add attachment title for BearyChat message. 
 <code>bearychatSend title: "${env.JOB_NAME} #{env.JOB_NUMBER}", url: "{env.BUILD_URL}"</code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>url</code> (optional)
<div><div>
  You can specify a URL for attachment title. 
 <code>bearychatSend title: "${env.JOB_NAME} #{env.JOB_NUMBER}", url: "{env.BUILD_URL}"</code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>webhook</code> (optional)
<div><div>
  Allows overriding the Bearychat Plugin Webhook URL specified in the global configuration. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
