---
layout: pipelinesteps
title: "Black Duck Hub Plugin for Jenkins"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Black Duck Hub Plugin for Jenkins

plugin:blackduck-hub[View this plugin on the Plugins Index]

=== +hub_scan+: Black Duck Hub Integration
++++
<ul><li><code>scans</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>scanTarget</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>hubProjectName</code>
<div><div>
  Provide the name of the Hub project that you would like to link these scans to. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>hubProjectVersion</code>
<div><div>
  Provide the Version of the Hub project that you would like to link these scans to. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>hubVersionPhase</code>
<div><div>
  Choose the Phase at which this Version is in its life cycle. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>hubVersionDist</code>
<div><div>
  Choose how this Version is planned to be distributed. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>scanMemory</code>
<div><div>
  Specify the memory, in megabytes, you would like to allocate for the BlackDuck Scan. Default: 4096 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>shouldGenerateHubReport</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>projectLevelAdjustments</code>
<div><div>
  Always maintain component adjustments to all versions of this project. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>bomUpdateMaximumWaitTime</code>
<div><div>
  Maximum time to wait (in minutes) for the BOM to be updated with the scan results. 
 <br> This also gets used as the maximum time to wait for the Report to be generated. 
 <br> Default: 5 minutes 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dryRun</code>
<div><div>
  If checked, the scan results will be put in a json file within the log directory in /data/ 
 <br> When running a dry run the Report generation and Failure Conditions will be skipped. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>cleanupOnSuccessfulScan</code>
<div><div>
  If checked, then the plugin will delete the log files produced by the CLI if the scan is successful. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>excludePatterns</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>exclusionPattern</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>codeLocationName</code>
<div><div>
  This will change the name of the Code Location that is created by this scan. 
 <br> An example of a consistent Code Location across nodes and builds would be ${JENKINS_URL}-${JOB_NAME} 
 <br> WARNING: This will only work with a single target specified. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unmapPreviousCodeLocations</code>
<div>Any Code Locations that were not part of the current scan, and are mapped to this Project and Version, will be unmapped from this Version.</div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>deletePreviousCodeLocations</code>
<div>Any Code Locations that were not part of the current scan, and are mapped to this Project and Version, will be deleted.</div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +hub_scan_failure+: Black Duck Hub Failure Conditions (Hub 3.0+)
++++
<ul><li><code>failBuildForPolicyViolations</code>
<div><div>
  This will check the the Version of the Project specified to see if any of the BOM entries violate policies defined in the Hub. 
 <br> If there are BOM entries that do violate Policies, the Build will be set to FAILURE 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>buildStateOnFailure</code>
<div><div>
  If the Failure Condition is met, then the Build will be set to this state on completion. 
 <br> Success = Will not fail the Build 
 <br> Unstable = Will set the Build Result to Unstable 
 <br> Failure = Will set the Build Result to Failure 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
