---
layout: pipelinesteps
title: "Cerberus测试插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Cerberus测试插件

plugin:cerberus-testing[在插件索引中查看此插件]

=== +executeCerberusCampaign+: 执行 Cerberus 活动
++++
<ul><li><code>campaignName</code>
<div><div>
  Enter the campaign name. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>platform</code>
<div><div>
  - either robot
 <br> - or Robot server ip + Robot server port + browser + browser version + platform
 <br> If you enter a robot, no need to enter Robot server ip + Robot server port + browser + browser version + platform 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code>
<div><div>
  Environment Cerberus must use 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>browser</code>
<div><div>
  - either robot
 <br> - or Robot server ip + Robot server port + browser + browser version + platform
 <br> If you enter a robot, no need to enter Robot server ip + Robot server port + browser + browser version + platform 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>browserVersion</code>
<div><div>
  - either robot
 <br> - or Robot server ip + Robot server port + browser + browser version + platform
 <br> If you enter a robot, no need to enter Robot server ip + Robot server port + browser + browser version + platform 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>screenshot</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>verbose</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>pageSource</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>seleniumLog</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>timeOut</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>retries</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>tag</code>
<div><div>
  Tag for this campaign. Tag is use to display campaign report, it is the id of campaign execution.
 <br> Use 
 <strong>$[current_timestamp]</strong> to print the current timestamp to the tag. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ss_p</code>
<div><div>
  - either robot
 <br> - or Robot server ip + Robot server port + browser + browser version + platform
 <br> If you enter a robot, no need to enter Robot server ip + Robot server port + browser + browser version + platform 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>screensize</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ssIp</code>
<div><div>
  - either robot
 <br> - or Robot server ip + Robot server port + browser + browser version + platform
 <br> If you enter a robot, no need to enter Robot server ip + Robot server port + browser + browser version + platform 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>robot</code>
<div><div>
  - either robot
 <br> - or Robot server ip + Robot server port + browser + browser version + platform
 <br> If you enter a robot, no need to enter Robot server ip + Robot server port + browser + browser version + platform 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
