---
layout: pipelinesteps
title: "Cloud Foundry Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Cloud Foundry Plugin

plugin:cloudfoundry[View this plugin on the Plugins Index]

=== +pushToCloudFoundry+: Push to Cloud Foundry
++++
<ul><li><code>target</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>organization</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>cloudSpace</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>manifestChoice</code> (optional)
<ul><b>Nested Object</b>
<li><code>appName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>appPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildpack</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>command</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>domain</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>envVars</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>key</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>hostname</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>instances</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>manifestFile</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>memory</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>noRoute</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>servicesNames</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>stack</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>timeout</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>value</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>pluginTimeout</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>selfSigned</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>servicesToCreate</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>type</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>plan</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>resetService</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
</ul>


++++
