---
layout: pipelinesteps
title: "Cobertura Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Cobertura Plugin

plugin:cobertura[View this plugin on the Plugins Index]

=== +cobertura+: Publish Cobertura Coverage Report
++++
<ul><li><code>autoUpdateHealth</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>autoUpdateStability</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>classCoverageTargets</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>coberturaReportFile</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>conditionalCoverageTargets</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failNoReports</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failUnhealthy</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failUnstable</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>fileCoverageTargets</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>lineCoverageTargets</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>maxNumberOfBuilds</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>methodCoverageTargets</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>onlyStable</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>packageCoverageTargets</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sourceEncoding</code> (optional)
<ul><li><b>Values:</b> <code>ASCII</code>, <code>Big5</code>, <code>Big5_HKSCS</code>, <code>Big5_Solaris</code>, <code>Cp037</code>, <code>Cp1006</code>, <code>Cp1025</code>, <code>Cp1026</code>, <code>Cp1046</code>, <code>Cp1047</code>, <code>Cp1097</code>, <code>Cp1098</code>, <code>Cp1112</code>, <code>Cp1122</code>, <code>Cp1123</code>, <code>Cp1124</code>, <code>Cp1140</code>, <code>Cp1141</code>, <code>Cp1142</code>, <code>Cp1143</code>, <code>Cp1144</code>, <code>Cp1145</code>, <code>Cp1146</code>, <code>Cp1147</code>, <code>Cp1148</code>, <code>Cp1149</code>, <code>Cp1250</code>, <code>Cp1251</code>, <code>Cp1252</code>, <code>Cp1253</code>, <code>Cp1254</code>, <code>Cp1255</code>, <code>Cp1256</code>, <code>Cp1257</code>, <code>Cp1258</code>, <code>Cp1381</code>, <code>Cp1383</code>, <code>Cp273</code>, <code>Cp277</code>, <code>Cp278</code>, <code>Cp280</code>, <code>Cp284</code>, <code>Cp285</code>, <code>Cp297</code>, <code>Cp33722</code>, <code>Cp420</code>, <code>Cp424</code>, <code>Cp437</code>, <code>Cp500</code>, <code>Cp737</code>, <code>Cp775</code>, <code>Cp838</code>, <code>Cp850</code>, <code>Cp852</code>, <code>Cp855</code>, <code>Cp856</code>, <code>Cp857</code>, <code>Cp858</code>, <code>Cp860</code>, <code>Cp861</code>, <code>Cp862</code>, <code>Cp863</code>, <code>Cp864</code>, <code>Cp865</code>, <code>Cp866</code>, <code>Cp868</code>, <code>Cp869</code>, <code>Cp870</code>, <code>Cp871</code>, <code>Cp874</code>, <code>Cp875</code>, <code>Cp918</code>, <code>Cp921</code>, <code>Cp922</code>, <code>Cp930</code>, <code>Cp933</code>, <code>Cp935</code>, <code>Cp937</code>, <code>Cp939</code>, <code>Cp942</code>, <code>Cp942C</code>, <code>Cp943</code>, <code>Cp943C</code>, <code>Cp948</code>, <code>Cp949</code>, <code>Cp949C</code>, <code>Cp950</code>, <code>Cp964</code>, <code>Cp970</code>, <code>EUC_CN</code>, <code>EUC_JP</code>, <code>EUC_JP_LINUX</code>, <code>EUC_JP_Solaris</code>, <code>EUC_KR</code>, <code>EUC_TW</code>, <code>GB18030</code>, <code>GBK</code>, <code>ISCII91</code>, <code>ISO2022_CN_CNS</code>, <code>ISO2022_CN_GB</code>, <code>ISO2022CN</code>, <code>ISO2022JP</code>, <code>ISO2022KR</code>, <code>ISO8859_1</code>, <code>ISO8859_13</code>, <code>ISO8859_15</code>, <code>ISO8859_2</code>, <code>ISO8859_3</code>, <code>ISO8859_4</code>, <code>ISO8859_5</code>, <code>ISO8859_6</code>, <code>ISO8859_7</code>, <code>ISO8859_8</code>, <code>ISO8859_9</code>, <code>JISAutoDetect</code>, <code>KOI8_R</code>, <code>MacArabic</code>, <code>MacCentralEurope</code>, <code>MacCroatian</code>, <code>MacCyrillic</code>, <code>MacDingbat</code>, <code>MacGreek</code>, <code>MacHebrew</code>, <code>MacIceland</code>, <code>MacRoman</code>, <code>MacRomania</code>, <code>MacSymbol</code>, <code>MacThai</code>, <code>MacTurkish</code>, <code>MacUkraine</code>, <code>MS874</code>, <code>MS932</code>, <code>MS936</code>, <code>MS949</code>, <code>MS950</code>, <code>MS950_HKSCS</code>, <code>PCK</code>, <code>SJIS</code>, <code>TIS620</code>, <code>UnicodeBig</code>, <code>UnicodeBigUnmarked</code>, <code>UnicodeLittle</code>, <code>UnicodeLittleUnmarked</code>, <code>UTF_16</code>, <code>UTF_8</code>, <code>x_iso_8859_11</code>, <code>x_Johab</code></li></ul></li>
<li><code>zoomCoverageChart</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
