---
layout: pipelinesteps
title: "CodeSonar Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== CodeSonar Plugin

plugin:codesonar[View this plugin on the Plugins Index]

=== +codesonar+: Codesonar
++++
<ul><li><code>conditions</code>
<div><div>
 Choose the condition you want Codesonar to use for build verification
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>warningCountIncreaseNewOnly</code></li>
<div><p> Condition will trigger the warranted result if the amount of warnings that did not exist until the current analysis is exceeded by more than the designated percentage. </p> 
<p> Maximum percentage increase - if the percentage of warnings exceed this amount it will mark build with the desired result [default 5.0] </p> 
<p> Mark build as - the desired result if the condition is triggered. </p></div>
<ul><li><code>percentage</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>warrantedResult</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>cyclomaticComplexity</code></li>
<div><p> Condition will change the result of the build if the cyclomatic complexity of procedures exceeds the preset value. </p> 
<p> Cyclomatic complexity limit - The procedures with cyclomatic complexity that exceeds this value will change the build result. [default 30] </p> 
<p> Mark build as - the desired result if the condition is triggered. </p></div>
<ul><li><code>maxCyclomaticComplexity</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>warrantedResult</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>redAlerts</code></li>
<div><p> Condition will change the result of the build if the amount of red alerts exceed the predefined value. </p> 
<p> Maximum amount of alerts - the maximum allowed amount of red alerts [default 1] </p> 
<p> Mark build as - the desired result if the condition is triggered. </p></div>
<ul><li><code>alertLimit</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>warrantedResult</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>warningCountIncreaseOverall</code></li>
<div><p> Condition will change the result of the build if the amount of warnings the analysis produces is greater than the preset percentage. </p> 
<p> Maximum percentage increase - if the percentage of warnings exceed this amount it will mark build with the desired result [default 5.0] </p> 
<p> Mark build as - the desired result if the condition is triggered. </p></div>
<ul><li><code>percentage</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>warrantedResult</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>warningCountIncreaseSpecifiedScoreAndHigher</code></li>
<div><p> Condition will change the result of the build if the percentage of warnings bellow the predefined rank increases above a certain percentage. </p> 
<p> Rank of warnings - Only warnings that are bellow this rank will be checked. [default 30] </p> 
<p> Maximum percentage increase - if the percentage of warnings exceed this amount it will mark build with the desired result [default 5.0] </p> 
<p> Mark build as - the desired result if the condition is triggered. </p></div>
<ul><li><code>rankOfWarnings</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>warningPercentage</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>warrantedResult</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>yellowAlerts</code></li>
<div><p> Condition will change the result of the build if the amount of yellow alerts exceed the predefined value. </p> 
<p> Maximum amount of alerts - the maximum allowed amount of yellow alerts [default 1] </p> 
<p> Mark build as - the desired result if the condition is triggered. </p></div>
<ul><li><code>alertLimit</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>warrantedResult</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>protocol</code>
<div><div>
 Choose http or https
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>hubAddress</code>
<div><div>
 IP address of the Codesonar hub
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>projectName</code>
<div><div>
 The name of the project. All characters allowed
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialId</code>
<div><div>
 Codesonar credentials
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
