---
layout: pipelinesteps
title: "Codefresh Integration Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Codefresh Integration Plugin

plugin:codefresh[View this plugin on the Plugins Index]

=== +codefreshLaunch+: Launch a Codefresh Composition
++++
<ul><li><code>cfComposition</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>cfVars</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>Variable</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>Value</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
=== +codefreshRun+: Trigger a Codefresh Pipeline
++++
<ul><li><code>cfBranch</code> (optional)
<div><div>
  Optionally enter the name of the branch to use for the build. Leave empty to use the default branch. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>cfPipeline</code> (optional)
<div><div>
  Choose the pipeline to trigger from the list of all your defined Codefresh pipelines. If the list is empty - verify your Codefresh authentication in Jenkins system config section. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>cfVars</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>Variable</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>Value</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
