---
layout: pipelinesteps
title: "CollabNet Plugins"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== CollabNet Plugins

plugin:collabnet[View this plugin on the Plugins Index]

=== +publishEventQ+: Notify TeamForge EventQ
++++
<ul><li><code>serverUrl</code>
<div><div>
  This is the URL to your TeamForge EventQ message-queue server. It should not have any path information in it. For example: 
 <em>amqp://mq.example.com:5672</em> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<div><div> 
 <p>If none is given, global TeamForge credentials will be used for this job.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludeCommitInfo</code> (optional)
<div><div>
  Whether to exclude associated commit information in EventQ notification. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>markUnstable</code> (optional)
<div><div>
  Mark current job as 
 <strong>unstable</strong> if this step fails to notify EventQ. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>sourceKey</code> (optional)
<div><div>
  This is the key to the build source on your TeamForge EventQ server. You can find it by visiting the configuration page for the source to which builds should be reported. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>status</code> (optional)
<div><div>
  (Optional) Specify EventQ status explicitly. If not provided, it will be determined based on the current run result. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
