---
layout: pipelinesteps
title: "Compuware ISPW操作插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Compuware ISPW操作插件

plugin:compuware-ispw-operations[在插件索引中查看此插件]

=== +ispwOperation+: 执行Compuware ISPW Rest API请求并返回JSON对象
++++
<div><div> 
 <p> Performs an ISPW Rest API request, and returns a JSON object. </p> 
</div></div>
<ul><li><code>connectionId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>consoleLogResponseBody</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ispwAction</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ispwRequestBody</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +ispwRegisterWebhook+: 创建并返回可供外部系统用来通知管道的ISPW webhook
++++
<div><div>
  Returns a unique webhook that can be used with 
 <code>waitForWebhook</code> to block pipeline execution until external notification. The returned webhook has 
 <code>String getToken()</code> and 
 <code>String getURL()</code> methods. 
</div></div>
<ul></ul>


++++
=== +ispwWaitForWebhook+: 等待ISPW webhook被外部系统发布
++++
<div><div>
  Blocks on a webhook created with 
 <code>registerWebhook</code> until the registered webhook is posted to. In general, should not be used inside of a 
 <code>node</code> block. 
</div></div>
<ul><li><code>webhookToken</code>
<ul><code>com.compuware.ispw.restapi.WebhookToken</code>
</ul></li>
</ul>


++++
