---
layout: pipelinesteps
title: "Confluence 发布程序"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Confluence 发布程序

plugin:confluence-publisher[在插件索引中查看此插件]

=== +publishConfluence+: 发布到Confluence
++++
<ul><li><code>siteName</code>
<div><div>
  Choose the Confluence site to connect to. These sites are configured in the 
 <a rel="nofollow">Global Configuration</a>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>spaceName</code>
<div><div>
  Enter the Space name of the wiki page. E.g., the string after "display" in the page's URL: http://confluence.example.com/display/
 <u>Space</u>/Page 
 <p></p> If the Space name contains a build-time variable, the validity of the name cannot be verified until build-time. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pageName</code>
<div><div>
  Enter the Space name of the wiki page. E.g., the string after the Space name in the page's URL: http://confluence.example.com/display/Space/
 <u>Page</u> 
 <p></p> If the Space name or Page name contains a build-time variable, the validity of the page cannot be verified until build-time. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>attachArchivedArtifacts</code> (optional)
<div><div>
  If checked, the plugin will automatically upload all of the archived artifacts (from the Artifact Archiver plugin). In that case, you don't need to reiterate the fileset pattern that is configured for the archiver. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>buildIfUnstable</code> (optional)
<div><div>
  If checked, the plugin will continue publishing, even if the build was not successful. In that case, you can use the ${BUILD_RESULT} build variable to indicate the current build result. 
 <p></p> If this box is 
 <b>not</b> checked, then ${BUILD_RESULT} can always only be "SUCCESS". 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>editorList</code> (optional)
<div><div>
  Configure wiki markup generation and replacement/insertion settings. 
 <p></p> Available markup generators:
 <ul> 
  <p>You can get links of uploaded attachments. Variable like $LINK[n] will be replaced with link which match link of uploaded attachment on Confluence.Where <b>n</b> is position number of attached file(links in array LINK[] will be provided in uploading order on Confluence). Example of usage: </p>
  <p> &lt;a href="$LINK[0]"&gt;$JOB_NAME build artifact&lt;/a&gt;</p>
  <p></p> 
  <li><b>Plain text</b><br> Enter custom text for the replacement. Build variables in the replacement text will be expanded.</li> 
 </ul> Available editors:
 <ul> 
  <li><b>Prepend</b><br> Content is added to the very beginning of the page</li> 
  <li><b>Append</b><br> Content is added to the very end of the page.</li> 
  <li><b>Before Token</b><br> Content is inserted before a configurable marker token.</li> 
  <li><b>After Token</b><br> Content is inserted after a configurable marker token.</li> 
  <li><b>Between Tokens</b><br> Content is inserted between two configurable start/end marker tokens. Existing content between the tokens is replaced.</li> 
 </ul> 
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>confluenceAfterToken</code></li>
<div><div>
  The generated content will be inserted immediately after the marker token (with a newline separator). 
 <p></p> Example:
 <ul> 
  <li>Token = "{jenkins-marker:after}"</li> 
  <li>Generated text = "2011-06-19"</li> 
  <li>Existing content:
   <blockquote>
    <pre>Lorem ipsum
{jenkins-marker:after}
Ipsum lorem</pre>
   </blockquote></li> 
  <li>New content:
   <blockquote>
    <pre>Lorem ipsum
{jenkins-marker:after}
2011-06-19
Ipsum lorem</pre>
   </blockquote></li> 
 </ul> 
 <p></p> If you have administrative access to your Confluence installation, consider creating a custom user macro: 
 <ul> 
  <li>Name: jenkins-marker</li> 
  <li>[ ] Macro has a body (<i><b>uncheck</b> the box</i>)</li> 
  <li>"Macro generates HTML markup"</li> 
  <li>Template: <i>**blank**</i></li> 
 </ul> This will create a new macro ("{jenkins-marker}"), which you can use to mark the location after which content will be inserted. Using the confluence macro tag parameter capability, you can reuse this single tag configuration for several single-token (Before/After) editors, by simply making the string after the colon unique (e.g., "{jenkins-marker:build-url-inserted-after-this}"). 
 <p></p> This token configuration does not render in the wiki output. 
</div></div>
<ul><li><code>generator</code>
<ul><b>Nested Choice of Objects</b>
<li><code>confluenceFile</code></li>
<ul><li><code>filename</code>
<div><div>
  Enter a filename relative to the workspace directory. The file's contents will be used as markup replacement for the editor. Note: the file should be in text format, and should contain text content that is already suitable for wiki rendering. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceText</code></li>
<ul><li><code>text</code>
<div><div>
  Enter custom text for the replacement. Build variables in the replacement text will be expanded. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>markerToken</code>
<div><div> 
 <p>Enter the marker token where the content should be inserted. The replacement content will be inserted <b>after</b> this token.</p> 
 <p>The token should already exist in the configured Confluence page markup.</p> 
 <p>Example: "<i>{jenkins-marker:build-urls}</i>"</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceAppendPage</code></li>
<div><div>
  The generated content will be inserted at the end of the page content (e.g., "&lt;existing-content&gt; + &lt;newline&gt; + &lt;generated&gt;"). 
</div></div>
<ul><li><code>generator</code>
<ul><b>Nested Choice of Objects</b>
<li><code>confluenceFile</code></li>
<ul><li><code>filename</code>
<div><div>
  Enter a filename relative to the workspace directory. The file's contents will be used as markup replacement for the editor. Note: the file should be in text format, and should contain text content that is already suitable for wiki rendering. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceText</code></li>
<ul><li><code>text</code>
<div><div>
  Enter custom text for the replacement. Build variables in the replacement text will be expanded. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul><li><code>confluenceBeforeToken</code></li>
<div><div>
  The generated content will be inserted immediately before the marker token (with a newline separator). 
 <p></p> Example:
 <ul> 
  <li>Token = "{jenkins-marker:before}"</li> 
  <li>Generated text = "2011-06-19"</li> 
  <li>Existing content:
   <blockquote>
    <pre>Lorem ipsum
{jenkins-marker:before}
Ipsum lorem</pre>
   </blockquote></li> 
  <li>New content:
   <blockquote>
    <pre>Lorem ipsum
2011-06-19
{jenkins-marker:before}
Ipsum lorem</pre>
   </blockquote></li> 
 </ul> 
 <p></p> If you have administrative access to your Confluence installation, consider creating a custom user macro: 
 <ul> 
  <li>Name: jenkins-marker</li> 
  <li>[ ] Macro has a body (<i><b>uncheck</b> the box</i>)</li> 
  <li>"Macro generates HTML markup"</li> 
  <li>Template: <i>**blank**</i></li> 
 </ul> This will create a new macro ("{jenkins-marker}"), which you can use to mark the location before which content will be inserted. Using the confluence macro tag parameter capability, you can reuse this single tag configuration for several single-token (Before/After) editors, by simply making the string after the colon unique (e.g., "{jenkins-marker:build-url-inserted-before-this}"). 
 <p></p> This token configuration does not render in the wiki output. 
</div></div>
<ul><li><code>generator</code>
<ul><b>Nested Choice of Objects</b>
<li><code>confluenceFile</code></li>
<ul><li><code>filename</code>
<div><div>
  Enter a filename relative to the workspace directory. The file's contents will be used as markup replacement for the editor. Note: the file should be in text format, and should contain text content that is already suitable for wiki rendering. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceText</code></li>
<ul><li><code>text</code>
<div><div>
  Enter custom text for the replacement. Build variables in the replacement text will be expanded. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>markerToken</code>
<div><div> 
 <p>Enter the marker token where the content should be inserted. The replacement content will be inserted <b>before</b> this token.</p>  
 <p>The token should already exist in the configured Confluence page markup.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceBetweenTokens</code></li>
<div><div>
  The generated content will be inserted between the START and END markers. Both markers must exist in the page. Any existing content between the markers will be 
 <b>replaced</b>. 
 <p></p> Example:
 <ul> 
  <li>Start Token = "{jenkins-between:start|token=replaced-section}"</li> 
  <li>End Token = "{jenkins-between:end|token=replaced-section}"</li> 
  <li>Generated text = "2011-06-19"</li> 
  <li>Existing content:
   <blockquote>
    <pre>Lorem ipsum
{jenkins-between:start|token=replaced-section}
previous content
{jenkins-between:end|token=replaced-section}
Ipsum lorem</pre>
   </blockquote></li> 
  <li>New content:
   <blockquote>
    <pre>Lorem ipsum
{jenkins-between:start|token=replaced-section}
2011-06-19
{jenkins-between:end|token=replaced-section}
Ipsum lorem</pre>
   </blockquote></li> 
 </ul> 
 <p></p> If you have administrative access to your Confluence installation, consider creating a custom user macro: 
 <ul> 
  <li>Name: jenkins-between</li> 
  <li>[X] Macro has a body</li> 
  <li>"Use unprocessed macro body"</li> 
  <li>"Macro generates wiki markup"</li> 
  <li>Template: <i>**blank**</i></li> 
 </ul> This will create a new macro ("{jenkins-between}"), which you can use to mark the start/end tokens. Using the Confluence macro tag parameter capability, you can use this single tag configuration for several "Between start/end token" edits, and simply make each individual editor configuration use a unique parameter (also remember to make the start/end tags unique as well). 
 <p></p> This token configuration maintains the Wiki rendering aspect of the replacement text, and the token does not render in the formatted wiki output. 
</div></div>
<ul><li><code>generator</code>
<ul><b>Nested Choice of Objects</b>
<li><code>confluenceFile</code></li>
<ul><li><code>filename</code>
<div><div>
  Enter a filename relative to the workspace directory. The file's contents will be used as markup replacement for the editor. Note: the file should be in text format, and should contain text content that is already suitable for wiki rendering. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceText</code></li>
<ul><li><code>text</code>
<div><div>
  Enter custom text for the replacement. Build variables in the replacement text will be expanded. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>startMarkerToken</code>
<div><div>
  Enter the token where the marked section should 
 <b>begin</b>. The replacement content will be inserted after this token. 
 <p></p> Both tokens should already exist in the configured Confluence page markup. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>endMarkerToken</code>
<div><div>
  Enter the token where the marked section should 
 <b>end</b>. The replacement content will be inserted before this token. 
 <p></p> Both tokens should already exist in the configured Confluence page markup. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceWritePage</code></li>
<div><div>
  The generated content will replace the entire page's content. 
 <b>Use with care</b> 
</div></div>
<ul><li><code>generator</code>
<ul><b>Nested Choice of Objects</b>
<li><code>confluenceFile</code></li>
<ul><li><code>filename</code>
<div><div>
  Enter a filename relative to the workspace directory. The file's contents will be used as markup replacement for the editor. Note: the file should be in text format, and should contain text content that is already suitable for wiki rendering. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceText</code></li>
<ul><li><code>text</code>
<div><div>
  Enter custom text for the replacement. Build variables in the replacement text will be expanded. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul><li><code>confluencePrependPage</code></li>
<div><div>
  The generated content will be inserted at the beginning of the page content (e.g., "&lt;generated&gt; + &lt;newline&gt; + &lt;existing-content&gt;"). 
</div></div>
<ul><li><code>generator</code>
<ul><b>Nested Choice of Objects</b>
<li><code>confluenceFile</code></li>
<ul><li><code>filename</code>
<div><div>
  Enter a filename relative to the workspace directory. The file's contents will be used as markup replacement for the editor. Note: the file should be in text format, and should contain text content that is already suitable for wiki rendering. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>confluenceText</code></li>
<ul><li><code>text</code>
<div><div>
  Enter custom text for the replacement. Build variables in the replacement text will be expanded. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul></ul></li>
<li><code>fileSet</code> (optional)
<div><div>
  Can use wildcards like 'module/dist/**/*.zip'. See 
 <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the @includes of Ant fileset</a> for the exact format. The base directory is 
 <a rel="nofollow">the workspace</a>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>labels</code> (optional)
<div><div>
  Comma, or space, separated list of labels to apply to the Confluence page. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>parentId</code> (optional)
<div><div>
  (Optional) Enter the page ID of the parent wiki page. You can find this identifier by accessing the parent page in question, and then selecting "Page Information" or "Page History" from the Confluence 
 <em>Tools</em> menu. The pageId will appear as a query parameter in the address bar. e.g. (
 <code>pageId=1234567</code>) 
 <p></p> If a parent is not specified, the space home will be used as the parent. 
 <p></p> This field is used for creating new pages only. If the page already exists, then parentId is discarded. 
</div></div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>replaceAttachments</code> (optional)
<div><div>
  If checked, the plugin will automatically replace the existing file with the new file with the same name. For correct work jenkins user should have permission to delete files from selected page. 
 <b>BE CAREFULE WITH THIS OPTION</b> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
