---
layout: pipelinesteps
title: "复制工件插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== 复制工件插件

plugin:copyartifact[在插件索引中查看此插件]

=== +copyArtifacts+: 从另一个项目复制工件
++++
<ul><li><code>projectName</code>
<div><div>
  Name of source project for copying of artifact(s). 
 <p></p> If a Maven project is specified, artifacts from all of its modules will be copied. Enter JOBNAME/MODULENAME here to copy from a particular module; you may copy/paste this from the URL for that module when browsing Jenkins. Example: MyMavenJob/my.group$MyModule 
 <p></p> If a multiconfiguration (matrix) project is specified, artifacts from all of its configurations will be copied, each into a subdirectory with the name of the configuration as seen in its URL when browsing Jenkins. Example: If target directory is given as fromMatrix then the copy could create $WORKSPACE/fromMatrix/label=slaveA/dist/mybuild.jar and $WORKSPACE/fromMatrix/label=slaveB/dist/mybuild.jar. 
 <br> To copy from a particular configuration, enter JOBNAME/AXIS=VALUE,.. as seen in the URL for that configuration. Example: MyMatrixJob/jdk=Java6u17 
 <br> To copy artifacts from one matrix project to another, use a parameter to select the matching configuration in the source project. Example: OtherMatrixJob/jdk=$jdk 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludes</code> (optional)
<div><div>
  Specify paths or patterns of artifacts to exclude, even if specified in "Artifacts to copy". Can be blank. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>filter</code> (optional)
<div><div>
  Relative paths to artifact(s) to copy or leave blank to copy all artifacts. This works just as a filter, and doesn't care whether all specified artifacts really exists. Check the /artifact/ browser of a build to see the relative paths to use here, as the build page typically hides intermediate directories. Can use wildcards like module/dist/**/*.zip, and use comma (followed by optional whitespace) to separate multiple entries. See the @includes of 
 <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Ant fileset</a> for the exact format. May also contain references to build parameters like $PARAM. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>fingerprintArtifacts</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>flatten</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>optional</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>parameters</code> (optional)
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
 <p> You shoudn't use "Build selector for Copy Artifact" parameters here, as it doesn't preserve compatibility when you upgrade plugins, and doesn't work for builds built before upgrading. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>resultVariableSuffix</code> (optional)
<div><div>
  The build number of the selected build will be recorded into the variable named COPYARTIFACT_BUILD_NUMBER_(SUFFIX) for later build steps to reference. You can specify that suffix part for that variable here. 
 <p> If not specified, the source project name will be used instead (in all uppercase, and sequences of characters other than A-Z replaced by a single underscore). </p>
 <p><strong>Example</strong>: </p>
 <table> 
  <tbody>
   <tr> 
    <th>Source project name</th> 
    <th>Suffix to be used</th> 
   </tr> 
   <tr> 
    <td>Project-ABC</td> 
    <td>PROJECT_ABC</td> 
   </tr> 
   <tr> 
    <td>tool1-release1.2</td> 
    <td>TOOL_RELEASE_</td> 
   </tr> 
  </tbody>
 </table> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>selector</code> (optional)
<div><div>
  How to select the build to copy artifacts from, such as latest successful or stable build, or latest "keep forever" build. Other plugins may provide additional selections. 
 <br> The build number of the selected build will be recorded in the environment for later build steps to reference. For details, see the help of "Result variable suffix" in "Advanced" section. 
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>downstream</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>lastCompleted</code></li>
<ul></ul><li><code>$class: 'MultiJobBuildSelector'</code></li>
<ul></ul><li><code>buildParameter</code></li>
<ul><li><code>parameterName</code>
<div><div>
  Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p> You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>permalink</code></li>
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PromotedBuildSelector'</code></li>
<ul><li><code>level</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul><li><code>latestSavedBuild</code></li>
<ul></ul><li><code>specific</code></li>
<ul><li><code>buildNumber</code>
<div><div>
  While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). The display name of a build and permalinks (e.g. "lastSuccessfulBuild", "lastBuild"...) can be used as well. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>lastSuccessful</code></li>
<ul><li><code>stable</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>upstream</code></li>
<ul><li><code>fallbackToLastSuccessful</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>upstreamFilterStrategy</code>
<div><div>
  Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System". 
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
<li><code>allowUpstreamDependencies</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>workspace</code></li>
<ul></ul></ul></li>
<li><code>target</code> (optional)
<div><div>
  Target base directory for copy, or leave blank to use the 
 <a rel="nofollow">workspace</a>. Directory (and parent directories, if any) will be created if needed. May contain references to build parameters like $PARAM. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
