---
layout: pipelinesteps
title: "Coverity plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Coverity插件

plugin:coverity[在插件索引中查看此插件]

=== +coverityResults+: 发布覆盖率查看结果
++++
<div><div> 
 <p> The Publish Coverity View Results step will retrieve issues from the configured Coverity Connect Instance, Project, and View. This step does not run any Coverity Analysis tools, it only retrieves the latest issues for the configured Project and View. It is recommended to run Coverity analyze and commit as prior step(s) in the pipeline to retrieve up to date results. </p> 
 <p> The Instance is configured in the Global Configuration, use the name of the instance or this step. The Project is the string name identifier of the Coverity Connect project. The View is the name or numeric ID of the view to retrieve issues from. Any filtering details for issue results this pipeline step will use can be configured in the Coverity Connect UI, it is recommended to use a custom "Issues: By Snapshot" view for this pipeline. </p> 
 <p> <b>Note:</b> if the are multiple streams in the project the view should be configured so the view filter uses only the stream for this pipeline. Additionally, it is recommended to filter the status value to not retrieve any Fixed or Dismissed issues. </p> 
</div></div>
<ul><li><code>connectInstance</code> (optional)
<div><div>
  Select the Coverity Connect instance that should be used to fetch results. Instances can be added in the global configuration page under the Coverity section. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>connectView</code> (optional)
<div><div>
  The Coverity Connect view that will be used to fetch the issues. This view should be configured to show issues for the project and stream which this pipeline is for. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>projectId</code> (optional)
<div><div> 
 <p> The Coverity Connect Project to fetch issues from. Projects will be listed in the Coverity Connect UI under Configuration -&gt; Projects &amp; Streams or by using the top right search to view all projects. The plain text project name can be used here. </p> 
 <p> <b>Note:</b> by default all Streams within a project will be used, so the View specified in conjunction with this value can filter the stream appropriately. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>abortPipeline</code> (optional)
<div><div>
  Abort the pipeline run if issues are found in the specified view. Optional value which defaults to false. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failPipeline</code> (optional)
<div><div>
  Mark the pipeline run as a failure if issues are found in the specified view. Optional value which defaults to false. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>unstable</code> (optional)
<div><div>
  Mark the pipeline run as unstable if issues are found in the specified view. Optional value which defaults to false. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +withCoverityEnv+: 将Coverity工具路径和Coverity 链接实例信息绑定到环境变量
++++
<div><div>
  This step will use the specified Coverity Tool Installation and add the bin/ directory to PATH for any steps that are wrapped. This will allow the pipeline script to access Coverity tools (like cov-build, cov-analyze, and cov-commit-defects) directly from a script step (such as a Shell Script or Windows Batch Script). Also, this step optionally allows users to bind the Coverity Connect Instance information (Host/Port/Credentials) to environment variables. 
</div></div>
<ul><li><code>coverityToolName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>connectInstance</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>hostVariable</code> (optional)
<div><div>
  Name of an environment variable to be set to the host of Coverity Connect during the build. Default environment variable name is "COVERITY_HOST" if not specified. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>passwordVariable</code> (optional)
<div><div>
  Name of an environment variable to be set to the password for connection to Coverity Connect during the build. Default environment variable name is "COVERITY_PASSPHRASE" if not specified. The value of this environment variable will be masked with "******" in the Console Output of the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>portVariable</code> (optional)
<div><div>
  Name of an environment variable to be set to the port for connection to Coverity Connect during the build. Default environment variable name is "COVERITY_PORT" if not specified. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>usernameVariable</code> (optional)
<div><div>
  Name of an environment variable to be set to the username for connection to Coverity Connect during the build. Default environment variable name is "COV_USER" if not specified. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
