---
layout: pipelinesteps
title: "Credentials Binding Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Credentials Binding Plugin

plugin:credentials-binding[View this plugin on the Plugins Index]

=== +withCredentials+: Bind credentials to variables
++++
<div><p> Allows various kinds of credentials (secrets) to be used in idiosyncratic ways. Each binding will define an environment variable active within the scope of the step. You can then use them directly from any other steps that expect environment variables to be set: </p> 
<pre><code>node {
  withCredentials([usernameColonPassword(credentialsId: 'mylogin', variable: 'USERPASS')]) {
    sh '''
      set +x
      curl -u $USERPASS https://private.server/ &gt; output
    '''
  }
}</code></pre> 
<p> As another example (use <i>Snippet Generator</i> to see all options): </p> 
<pre><code>node {
  withCredentials([string(credentialsId: 'mytoken', variable: 'TOKEN')]) {
    sh '''
      set +x
      curl -H "Token: $TOKEN" https://some.api/
    '''
  }
}</code></pre> 
<p> or retrieve values from Groovy code via the <code>env</code> magic variable: </p> 
<pre><code>def password = env.PASSWORD</code></pre> 
<p> Note that some steps explicitly ask for credentials of a particular kind, usually as a <code>credentialsId</code> parameter, in which case this step is unnecessary. </p> 
<p> For bindings which store a secret file, beware that </p> 
<pre><code>node {
  dir('subdir') {
    withCredentials([file(credentialsId: 'secret', variable: 'FILE')]) {
      sh 'use $FILE'
    }
  }
}</code></pre> 
<p> is not safe, as <code>$FILE</code> might be inside the workspace (in <code>subdir@tmp/secretFiles/</code>), and thus visible to anyone able to browse the job’s workspace. If you need to run steps in a different directory than the usual workspace, you should instead use </p> 
<pre><code>node {
  withCredentials([file(credentialsId: 'secret', variable: 'FILE')]) {
    dir('subdir') {
      sh 'use $FILE'
    }
  }
}</code></pre> 
<p> to ensure that the secrets are outside the workspace; or choose a different workspace entirely: </p> 
<pre><code>node {
  ws {
    withCredentials([file(credentialsId: 'secret', variable: 'FILE')]) {
      sh 'use $FILE'
    }
  }
}</code></pre></div>
<ul><li><code>bindings</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>$class: 'AmazonWebServicesCredentialsBinding'</code></li>
<div><div>
  Sets one variable to the AWS access key and another one to the secret key given in the credentials. 
</div></div>
<ul><li><code>accessKeyVariable</code>
<div><div>
  Environment variable name for the AWS Access Key Id. If empty, 
 <code>AWS_ACCESS_KEY_ID</code> will be used. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>secretKeyVariable</code>
<div><div>
  Environment variable name for the AWS Secret Access Key. If empty, 
 <code>AWS_SECRET_ACCESS_KEY</code> will be used. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'AwsBucketCredentialsBinding'</code></li>
<div><div>
  Does something. 
</div></div>
<ul><li><code>usernameVariable</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>passwordVariable</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>azureServicePrincipal</code></li>
<ul><li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>clientIdVariable</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>clientSecretVariable</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>subscriptionIdVariable</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tenantIdVariable</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'AzurePublisherSettingsBinding'</code></li>
<div><div>
  Set a variable to point to Azure Publisher Settings file. 
</div></div>
<ul><li><code>variable</code>
<div><div>
  Name of an environment variable to be set during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>certificate</code></li>
<div><div>
  Sets one variable to the username and one variable to the password given in the credentials. 
</div> 
<div> 
 <strong>Warning</strong>: if the master or slave node has multiple executors, any other build running concurrently on the same node will be able to read the text of the secret, for example on Linux using 
 <code>ps e</code>. 
</div></div>
<ul><li><code>keystoreVariable</code>
<div><div>
  Name of an environment variable to be set to the temporary keystore location during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>aliasVariable</code> (optional)
<div><div>
  Name of an environment variable to be set to the keystore alias name of the certificate during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>passwordVariable</code> (optional)
<div><div>
  Name of an environment variable to be set to the password during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>dockerCert</code></li>
<ul><li><code>variable</code>
<div><div>
  Name of an environment variable to be set during the build.
 <br> Its value will be the absolute path of the directory where the 
 <code>{ca,cert,key}.pem</code> files will be created.
 <br> You probably want to call this variable 
 <code>DOCKER_CERT_PATH</code>, which will be understood by the docker client binary.
 <br> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>file</code></li>
<div><div>
  Copies the file given in the credentials to a temporary location, then sets the variable to that location. (The file is deleted when the build completes.) 
</div> 
<div> 
 <strong>Warning</strong>: if the master or slave node has multiple executors, any other build running concurrently on the same node will be able to read the contents of this file. 
</div></div>
<ul><li><code>variable</code>
<div><div>
  Name of an environment variable to be set during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>sshUserPrivateKey</code></li>
<div><div>
  Copies the SSH key file given in the credentials to a temporary location, then sets a variable to that location. (The file is deleted when the build completes.) Also optionally sets variables for the SSH key's username and passphrase. 
</div> 
<div> 
 <strong>Warning</strong>: if the master or slave node has multiple executors, any other build running concurrently on the same node will be able to read the contents of this file. 
</div></div>
<ul><li><code>keyFileVariable</code>
<div><div>
  Name of an environment variable to be set to the temporary path of the SSH key file during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>passphraseVariable</code> (optional)
<div><div>
  Name of an environment variable to be set to the password during the build. (optional) 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>usernameVariable</code> (optional)
<div><div>
  Name of an environment variable to be set to the username during the build. (optional) 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>string</code></li>
<div><div>
  Sets a variable to the text given in the credentials. 
</div> 
<div> 
 <strong>Warning</strong>: if the master or slave node has multiple executors, any other build running concurrently on the same node will be able to read the text of the secret, for example on Linux using 
 <code>ps e</code>. 
</div></div>
<ul><li><code>variable</code>
<div><div>
  Name of an environment variable to be set during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>usernameColonPassword</code></li>
<div><div>
  Sets a variable to the username and password given in the credentials, separated by a colon (
 <code>:</code>). 
</div> 
<div> 
 <strong>Warning</strong>: if the master or slave node has multiple executors, any other build running concurrently on the same node will be able to read the text of the secret, for example on Linux using 
 <code>ps e</code>. 
</div></div>
<ul><li><code>variable</code>
<div><div>
  Name of an environment variable to be set during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>usernamePassword</code></li>
<div><div>
  Sets one variable to the username and one variable to the password given in the credentials. 
</div> 
<div> 
 <strong>Warning</strong>: if the master or slave node has multiple executors, any other build running concurrently on the same node will be able to read the text of the secret, for example on Linux using 
 <code>ps e</code>. 
</div></div>
<ul><li><code>usernameVariable</code>
<div><div>
  Name of an environment variable to be set to the username during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>passwordVariable</code>
<div><div>
  Name of an environment variable to be set to the password during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>zip</code></li>
<div><div>
  Unpacks the ZIP file given in the credentials to a temporary directory, then sets the variable to that location. (The directory is deleted when the build completes.) 
</div> 
<div> 
 <strong>Warning</strong>: if the master or slave node has multiple executors, any other build running concurrently on the same node will be able to read the contents of this directory. 
</div></div>
<ul><li><code>variable</code>
<div><div>
  Name of an environment variable to be set during the build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Credentials of an appropriate type to be set to the variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul>


++++
