---
layout: pipelinesteps
title: "Cucumber Living Documentation Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Cucumber Living Documentation Plugin

plugin:cucumber-living-documentation[View this plugin on the Plugins Index]

=== +livingDocs+: Living documentation
++++
<div><p>Generates BDD <b>living documentation</b> based on Cucumber tests results</p> 
<p>This plugin expects <b>Cucumber json output</b> from your tests to generate the documentation of your project. The plugin uses the json report to produce html and pdf documentation that will be available after build execution. </p> 
<p>To build the documentation from your tests results you need to use cucumber <b>json formatter</b>: </p>
<pre>
    import cucumber.junit.Cucumber;
	import org.junit.runner.RunWith;

	@RunWith(Cucumber.class)
	@Cucumber.Options(format = "json:target/cucumber.json")
	public class CucumberTest {
	}
</pre> 
<p>Note that <b>format</b> option was replaced by <b>plugin</b> in newer cucumber versions.</p> 
<p>If you face <b>java.lang.ClassCircularityError: org/jruby/RubyClass</b> you probably hit issue <a href="https://issues.jenkins-ci.org/browse/JENKINS-31019" rel="nofollow">JENKINS-31019</a>, to solve that need to upgrade your installation to <b>v1.640</b> or newer.</p> 
<p>Cucumber living documentation plugin is backed by <a href="http://github.com/rmpestano/cukedoctor" rel="nofollow">Cukedoctor</a>, a BDD living documentation tool which integrates <a href="https://cucumber.io/" rel="nofollow">Cucumber.</a> and <a href="http://asciidoctor.org" rel="nofollow">Asciidoctor</a></p></div>
<ul><li><code>featuresDir</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code> (optional)
<ul><li><b>Values:</b> <code>HTML</code>, <code>pdf</code>, <code>ALL</code></li></ul></li>
<li><code>toc</code> (optional)
<ul><li><b>Values:</b> <code>RIGHT</code>, <code>LEFT</code>, <code>CENTER</code></li></ul></li>
<li><code>numbered</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>sectAnchors</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>title</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>hideFeaturesSection</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>hideSummary</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>hideScenarioKeyword</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>hideStepTime</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>hideTags</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
