---
layout: pipelinesteps
title: "OWASP Dependency-Check Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== OWASP Dependency-Check Plugin

plugin:dependency-check-jenkins-plugin[View this plugin on the Plugins Index]

=== +dependencyCheckAnalyzer+: Invoke Dependency-Check analysis
++++
<ul><li><code>scanpath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>outdir</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>datadir</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>suppressionFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>hintsFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>zipExtensions</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>isAutoupdateDisabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>includeHtmlReports</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>includeVulnReports</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>includeJsonReports</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>includeCsvReports</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>skipOnScmChange</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>skipOnUpstreamChange</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +dependencyCheckPublisher+: Publish Dependency-Check results
++++
<ul><li><code>canComputeNew</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>canResolveRelativePaths</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>canRunOnFailed</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>defaultEncoding</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedNewAll</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedNewHigh</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedNewLow</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedNewNormal</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedTotalAll</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedTotalHigh</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedTotalLow</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedTotalNormal</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>healthy</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pattern</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>shouldDetectModules</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>thresholdLimit</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unHealthy</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableNewAll</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableNewHigh</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableNewLow</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableNewNormal</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableTotalAll</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableTotalHigh</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableTotalLow</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableTotalNormal</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useDeltaValues</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>usePreviousBuildAsReference</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>useStableBuildAsReference</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +dependencyCheckUpdateOnly+: Invoke Dependency-Check NVD update only
++++
<ul><li><code>datadir</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +dependencyTrackPublisher+: Publish results to Dependency-Track
++++
<ul><li><code>projectId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifact</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactType</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
