---
layout: pipelinesteps
title: "Docker Pipeline"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Docker Pipeline

plugin:docker-workflow[View this plugin on the Plugins Index]

=== +dockerFingerprintFrom+: Record trace of a Docker image used in FROM
++++
<div><div>
  Normally used implicitly by method calls on the 
 <code>docker</code> global variable. Records the fact that a Docker image was built from another. 
</div></div>
<ul><li><code>dockerfile</code>
<div><div>
  Workspace-relative path of a 
 <code>Dockerfile</code> which will be parsed for its 
 <code>FROM</code> instruction. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>image</code>
<div><div>
  ID or tag of the image which was just built, like 
 <code>--tag</code> of 
 <code>docker build</code>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildArgs</code> (optional)
<ul><code>java.lang.String></code>
</ul></li>
<li><code>toolName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +dockerFingerprintRun+: Record trace of a Docker image run in a container
++++
<div><div>
  Normally used implicitly by method calls on the 
 <code>docker</code> global variable. Records the fact that a Docker image was used by this build. 
</div></div>
<ul><li><code>containerId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +withDockerContainer+: Run build steps inside a Docker container
++++
<div><div>
  Normally used implicitly by method calls on the 
 <code>docker</code> global variable. Takes an image ID or symbolic name 
 <em>which must already have been pulled locally</em> and starts a container based on that image. Runs all nested 
 <code>sh</code> steps inside that container. The workspace is mounted read-write into the container. 
</div></div>
<ul><li><code>image</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>args</code> (optional)
<div><div>
  Any other arguments to pass to 
 <code>docker run</code>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +withDockerRegistry+: Sets up Docker registry endpoint
++++
<div><div>
  Normally used implicitly by method calls on the 
 <code>docker</code> global variable. Sets up connection details for a Docker registry. 
</div></div>
<ul><li><code>registry</code>
<ul><b>Nested Object</b>
<li><code>url</code>
<div><div>
  URL to the Docker registry you are using. May be left blank to use the public DockerHub registry (currently 
 <code>https://index.docker.io/v1/</code>). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
=== +withDockerServer+: Sets up Docker server endpoint
++++
<div><div>
  Normally used implicitly by method calls on the 
 <code>docker</code> global variable. Sets up connection details for a Docker server. 
</div></div>
<ul><li><code>server</code>
<ul><b>Nested Object</b>
<li><code>uri</code>
<div><div>
  URI to the Docker Host you are using. May be left blank to use the Docker default (defined by DOCKER_HOST environment variable) (typically 
 <code>unix:///var/run/docker.sock</code> or 
 <code>tcp://127.0.0.1:2376</code>). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
