---
layout: pipelinesteps
title: "External Workspace Manager Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== External Workspace Manager Plugin

plugin:external-workspace-manager[View this plugin on the Plugins Index]

=== +exws+: Use external workspace
++++
<div><div>
  Based on the input parameter, it defines the local path to the workspace, and switches to it. The complete workspace path follows the pattern: 
 <p> <i>/nodeMountPoint/physicalPathOnDisk/$JOB_NAME/$BUILD_NUMBER</i> </p> where 
 <ul> 
  <li> <i>nodeMountPoint</i> is defined either in the Node configuration, External Workspace section, or in the Jenkins global config, the <i>External Workspace Template</i> section. Firstly it searches for the disk definition in the Jenkins global config (the <i>Template</i> lookup is done based on the <i>Node label</i> parameter), then it fallbacks to searching in the Node configuration. </li> 
  <li> <i>physicalPathOnDisk</i> is defined in the Jenkins global config, the <i>External Workspace Definitions</i> section. </li> 
 </ul> 
</div></div>
<ul><li><code>externalWorkspace</code>
<div><div> 
 <p> The object returned by the <i>exwsAllocate</i> step. </p> 
 <p> Basic usage: </p> 
 <pre>
    def extWorkspace = exwsAllocate diskPoolId: 'diskpool1'
    node ('linux') {
        exws (extWorkspace) {
            scm checkout
            sh 'mvn clean install -DskipTests'
        }
    }
    node ('test') {
        exws (extWorkspace) {
            sh 'mvn test'
        }
    }
    </pre> 
</div></div>

<ul><code>org.jenkinsci.plugins.ewm.model.ExternalWorkspace</code>
</ul></li>
</ul>


++++
=== +exwsAllocate+: Allocate external workspace
++++
<div><div> 
 <p> Allocates a disk from the given <i>Disk Pool Ref ID</i>. By default, the disk with the most available space is selected. On that disk, it computes the workspace path based on the formula: <i>physicalPathOnDisk/$JOB_NAME/$BUILD_NUMBER</i>, where <i>physicalPathOnDisk</i> is defined in the Jenkins global config, <i>External Workspace Definitions</i> section. </p> 
 <p> If you provide the <i>Upstream</i> parameter, then the <i>Disk Pool Ref ID</i> parameter will be ignored. In this case, the step will allocate the same workspace as used by its upstream job. By default, it will select the workspace used by the last stable build from the upstream job. </p> 
</div></div>
<ul><li><code>diskPoolId</code>
<div><div>
  The reference to the Disk Pool ID defined in the Jenkins global config. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>path</code> (optional)
<div><div> 
 <p> The workspace path on the Disk can be configured within the Build DSL. If the <i>path</i> parameter is provided, the <i>exwsAllocate</i> step will allocate this workspace path on the Disk. If it's not provided, the <i>exwsAllocate</i> step will fallback to using the <i>Workspace path template</i> parameter defined in the Jenkins global config, <i>External Workspace Definitions</i> section, if any. </p> 
 <p> Basic Pipeline example: </p> 
 <pre>
    def customPath = "${env.JOB_NAME}/${PULL_REQUEST_NUMBER_PARAM}/${env.BUILD_NUMBER}"
    def extWorkspace = exwsAllocate diskPoolId: 'diskpool1', path: customPath
    ...
    </pre> 
 <p> Note: It's recommended to use <i>${ }</i> for variable declaration, instead of standalone <i>$</i> symbol, as shown in the examples. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>selectedRun</code> (optional)
<div><div> 
 <p> If you provide this parameter, the <i>exwsAllocate</i> step will allocate the first workspace used by the selected run. </p> 
 <p> This is a <i>RunWrapper</i> object. You can get a reference by using the <i>runSelector</i> step from the <i>Run Selector Plugin</i>. </p> 
 <p> Basic usage example: </p> 
 <pre>
    def run = selectRun 'upstream-project-name'
    def extWorkspace = exwsAllocate selectedRun: run
    ...
    </pre> 
</div></div>

<ul><code>org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper</code>
</ul></li>
<li><code>strategy</code> (optional)
<div><div> 
 <p> Provide Disk allocation strategy as step parameter. This will override the strategy defined in the Jenkins global config. </p> 
 <p> <b>Note:</b> Some Disk allocation strategies may require additional information to be provided. For example, if you choose the fastest read/write speed strategy, then you must provide, for each disk, its read/write speeds. These values should be set in the <i>Disk Information</i> section, for each <i>Disk</i> entry from the Jenkins global config. </p> 
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>fastestReadSpeed</code></li>
<ul><li><code>estimatedWorkspaceSize</code> (optional)
<div><div> 
 <p> Optional parameter. It indicates the estimated size that the workspace may have. It has to be in MB. </p> 
 <p> If provided, the Disk allocation strategy ensures that the selected disk has at least as much usable space left as the estimated workspace size. </p> 
 <p> For example, let's suppose we want to select the disk with the highest read speed, but that has a minimum usable space of 100 MB. The Pipeline code for that is: </p> 
 <pre>
    def extWorkspace = exwsAllocate diskPoolId: 'diskpool1', strategy: fastestReadSpeed(estimatedWorkspaceSize: 100)
    // ...
    </pre> 
</div></div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
</ul><li><code>fastestWriteSpeed</code></li>
<ul><li><code>estimatedWorkspaceSize</code> (optional)
<div><div> 
 <p> Optional parameter. It indicates the estimated size that the workspace may have. It has to be in MB. </p> 
 <p> If provided, the Disk allocation strategy ensures that the selected disk has at least as much usable space left as the estimated workspace size. </p> 
 <p> For example, let's suppose we want to select the disk with the highest read speed, but that has a minimum usable space of 100 MB. The Pipeline code for that is: </p> 
 <pre>
    def extWorkspace = exwsAllocate diskPoolId: 'diskpool1', strategy: fastestReadSpeed(estimatedWorkspaceSize: 100)
    // ...
    </pre> 
</div></div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
</ul><li><code>mostUsableSpace</code></li>
<ul><li><code>estimatedWorkspaceSize</code> (optional)
<div><div> 
 <p> Optional parameter. It indicates the estimated size that the workspace may have. It has to be in MB. </p> 
 <p> If provided, the Disk allocation strategy ensures that the selected disk has at least as much usable space left as the estimated workspace size. </p> 
 <p> For example, let's suppose we want to select the disk with the highest read speed, but that has a minimum usable space of 100 MB. The Pipeline code for that is: </p> 
 <pre>
    def extWorkspace = exwsAllocate diskPoolId: 'diskpool1', strategy: fastestReadSpeed(estimatedWorkspaceSize: 100)
    // ...
    </pre> 
</div></div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
</ul></ul></li>
</ul>


++++
