---
layout: pipelinesteps
title: "Fedora Module Build System Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Fedora Module Build System Plugin

plugin:fedora-module-build-system[View this plugin on the Plugins Index]

=== +queryModuleBuildRequest+: Query Module Build Request
++++
<ul><li><code>mbsUrl</code> (optional)
<div><div> 
 <p>Base URL of MBS system. This should usually be https://mbs.fedoraproject.org/ </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>moduleRequestId</code> (optional)
<div><div> 
 <p>ID of the module build request.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +submitModuleBuildRequest+: Submit Module Build Request
++++
<ul><li><code>moduleName</code> (optional)
<div><div> 
 <p>Name of the module to build.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>revision</code> (optional)
<div><div> 
 <p>Revision of the module to build.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>branch</code> (optional)
<div><div> 
 <p>Branch of the module to build.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>mbsUrl</code> (optional)
<div><div> 
 <p>Base URL of MBS system. This should usually be https://mbs.fedoraproject.org/ </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>password</code> (optional)
<div><div> 
 <p>Password to use to connect to MBS. Note: it is recommended to use withCredentials for this.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>user</code> (optional)
<div><div> 
 <p>User name to use to connect to MBS</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
