---
layout: pipelinesteps
title: "File Operations Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== 文件操作插件

plugin:file-operations[在插件索引中查看此插件]

=== +fileOperations+: 文件操作
++++
<ul><li><code>fileOperations</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>fileCopyOperation</code></li>
<ul><li><code>includes</code>
<div><div>
  Files included to copy, this supports ant-style file pattern ex: target/*/final*.xml 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludes</code>
<div><div>
  Files excluded from copying, this supports ant-style file pattern ex: target/*/final*.xml 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetLocation</code>
<div><div>
  Destination folder location to copy the files. Base directory is workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>flattenFiles</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>fileCreateOperation</code></li>
<ul><li><code>fileName</code>
<div><div>
  Path and Name of the file to be created in workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>fileContent</code>
<div><div>
  File content to be created, use environment variables where needed. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fileDeleteOperation</code></li>
<ul><li><code>includes</code>
<div><div>
  Files included to delete, this supports ant-style file pattern ex: target/*/final*.xml 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludes</code>
<div><div>
  Files excluded from deleting, this supports ant-style file pattern ex: target/*/final*.xml 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fileDownloadOperation</code></li>
<ul><li><code>url</code>
<div><div>
  Url of the file to download. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>userName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetLocation</code>
<div><div>
  Destination location to download the file. Base directory is workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetFileName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fileJoinOperation</code></li>
<ul><li><code>sourceFile</code>
<div><div>
  Source file path to copy the content. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetFile</code>
<div><div>
  Target file path to append the content from source file. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>filePropertiesToJsonOperation</code></li>
<ul><li><code>sourceFile</code>
<div><div>
  Source file path of properties. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetFile</code>
<div><div>
  Target file path to create or update with json data. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fileRenameOperation</code></li>
<ul><li><code>source</code>
<div><div>
  File to be renamed. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>destination</code>
<div><div>
  Destination file location to rename. Base directory is workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fileTransformOperation</code></li>
<ul><li><code>includes</code>
<div><div>
  Files included to copy, this supports ant-style file pattern ex: target/*/final*.xml 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludes</code>
<div><div>
  Files excluded from copying, this supports ant-style file pattern ex: target/*/final*.xml 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fileUnTarOperation</code></li>
<ul><li><code>filePath</code>
<div><div>
  Source tar file location. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetLocation</code>
<div><div>
  Destination folder location to untar the files. Base directory is workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>isGZIP</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>fileUnZipOperation</code></li>
<ul><li><code>filePath</code>
<div><div>
  Source zip file location. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targetLocation</code>
<div><div>
  Destination folder location to unzip the files. Base directory is workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fileZipOperation</code></li>
<ul><li><code>folderPath</code>
<div><div>
  Path of the folder to create zip file in workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>folderCopyOperation</code></li>
<ul><li><code>sourceFolderPath</code>
<div><div>
  Folder to be copied. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>destinationFolderPath</code>
<div><div>
  Destination folder location to copy the files. Base directory is workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>folderCreateOperation</code></li>
<ul><li><code>folderPath</code>
<div><div>
  Path and Name of the folder to be created in workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>folderDeleteOperation</code></li>
<ul><li><code>folderPath</code>
<div><div>
  Path and Name of the folder to be deleted in workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>folderRenameOperation</code></li>
<ul><li><code>source</code>
<div><div>
  Folder to be renamed. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>destination</code>
<div><div>
  Destination folder name to rename. Base directory is workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul>


++++
