---
layout: pipelinesteps
title: "Gerrit 触发器"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Gerrit 触发器

plugin:gerrit-trigger[在插件索引中查看此插件]

=== +setGerritReview+:设置Gerrit评论
++++
<div><div> 
 <p> Allows influencing how the build results are reported back to Gerrit when the build finishes. All input values are optional. If the step occurs multiple times in a workflow, the last value set for each parameter is used. </p> 
 <p> If the build is not triggered by Gerrit Trigger, or if the trigger is configured to not report back to Gerrit when the build finishes, this step does nothing. </p> 
</div></div>
<ul><li><code>customUrl</code> (optional)
<div><div>
  Custom URL for a message to send back to Gerrit. If empty, URL to post from Gerrit Trigger configuration will be used. Same expansion is done as for the URL to post configuration option. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unsuccessfulMessage</code> (optional)
<div><div>
  Additional details to post back to Gerrit if the build is not successful. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
