---
layout: pipelinesteps
title: "HipChat 插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== HipChat 插件

plugin:hipchat[在插件索引中查看此插件]

=== +hipchatSend+: 发送 HipChat 消息
++++
<div><div>
  Simple step for sending a HipChat message to designated room.
 <br> Use the advanced settings to override the HipChat Plugin global configuration to include: HipChat Server, API Token, API Version (1 or 2) and Send As (v1 API only).
 <br> Please see the HipChat Plugin global configuration for more details on the fields. Usage Example:
 <br> 
 <code> hipchatSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<a rel="nofollow">Open</a>)" </code> 
</div></div>
<ul><li><code>message</code>
<div><div> 
 <b>REQUIRED</b> The message body
 <br> Valid length range: 1 - 10000.
 <br> Message may include global variables, for example environment and currentBuild variables:
 <br> 
 <code> hipchatSend "${env.JOB_NAME} ${env.BUILD_NUMBER} status: ${currentBuild.result} (<a rel="nofollow">Open</a>)" </code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>color</code> (optional)
<div><div> 
 <b>OPTIONAL</b> Background color for message.
 <br> Valid values: YELLOW, GREEN, RED, PURPLE, GRAY, RANDOM.
 <br> Defaults to 'GRAY'.
 <br> 
 <code>hipchatSend color: "YELLOW", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code> 
</div></div>

<ul><li><b>Values:</b> <code>YELLOW</code>, <code>GREEN</code>, <code>RED</code>, <code>PURPLE</code>, <code>GRAY</code>, <code>RANDOM</code></li></ul></li>
<li><code>credentialId</code> (optional)
<div><div>
  The credential selected here will be used to send out the notification. If no credential is specified here, the credential selected in the global configuration will be used instead. 
 <br> In case a new credential needs to be created, make sure that the newly created credential uses "Secret text" kind. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failOnError</code> (optional)
<div><div>
  If set to true, then the step will abort the Workflow run as a failure if there is an error sending message.
 <br> 
 <code>hipchatSend failOnError: true, message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>notify</code> (optional)
<div><div> 
 <b>OPTIONAL</b> Whether this message should trigger a user notification (change the tab color, play a sound, notify mobile phones, etc). Each recipient's notification preferences are taken into account.
 <br> Defaults to 
 <b>false</b>.
 <br> 
 <code>hipchatSend notify: true, message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>room</code> (optional)
<div><div>
  Allows overriding the HipChat Plugin default room.
 <br> 
 <code>hipchatSend room: "room-name", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sendAs</code> (optional)
<div><div>
  Allows overriding the HipChat Plugin default Send As value (v1 API only). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>server</code> (optional)
<div><div>
  Allows overriding the HipChat Plugin default HipChat Server. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>textFormat</code> (optional)
<div><div>
  Enable this setting to send the notification in text format. HTML format is used if this setting is disabled. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>token</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>v2enabled</code> (optional)
<div><div>
  Allows overriding the HipChat Plugin default API Version to use - v1 or v2.
 <br> hipchatSend Workflow step defaults to v2 API 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
