---
layout: pipelinesteps
title: "HTML Publisher plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== HTML Publisher plugin

plugin:htmlpublisher[View this plugin on the Plugins Index]

=== +publishHTML+: Publish HTML reports
++++
<ul><li><code>target</code>
<ul><b>Nested Object</b>
<li><code>reportName</code>
<div><div>
  The name of the report to display for the build/project, such as "Code Coverage" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reportDir</code>
<div><div>
  The path to the HTML report directory relative to the workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reportFiles</code>
<div><div>
  The file(s) to provide links inside the report directory 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reportTitles</code>
<div><div>
  The optional title(s) for the report files, which will be used as the tab names. If this is not provided, file names will be used instead. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>keepAll</code>
<div><div>
  If checked, archive reports for all successful builds, otherwise only the most recent 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>alwaysLinkToLastBuild</code>
<div><div>
  If this control and "Keep past HTML reports" are checked, publish the link on project level even if build failed. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>allowMissing</code>
<div><div>
  If checked, will allow report to be missing and build will not fail on missing report 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>includes</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
