---
layout: pipelinesteps
title: "IBM Cloud DevOps"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== IBM Cloud DevOps

plugin:ibm-cloud-devops[在插件索引中查看此插件]

=== +evaluateGate+: IBM Cloud DevOps 网关
++++
<ul><li><code>policy</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>forceDecision</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +notifyOTC+: 发送通知到 OTC
++++
<ul><li><code>stageName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>status</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>webhookUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +publishBuildRecord+: 将构建记录发布到IBM Cloud DevOps
++++
<ul><li><code>result</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>gitRepo</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>gitBranch</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>gitCommit</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +publishDeployRecord+: 将部署记录发布到 IBM Cloud DevOps
++++
<ul><li><code>result</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>appUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +publishSQResults+: 将SonarQube测试结果发布到IBM Cloud DevOps
++++
<ul><li><code>SQHostURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>SQAuthToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>SQProjectKey</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +publishTestResult+: 将测试结果发布到IBM Cloud DevOps
++++
<ul><li><code>type</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>fileLocation</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +sendDeployableMessage+: 向OTC发送可部署的映射消息
++++
<ul><li><code>status</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>webhookUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
