---
layout: pipelinesteps
title: "IBM Cloud DevOps"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== IBM Cloud DevOps

plugin:ibm-cloud-devops[View this plugin on the Plugins Index]

=== +evaluateGate+: IBM Cloud DevOps Gate
++++
<ul><li><code>policy</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>forceDecision</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +notifyOTC+: Send notification to OTC
++++
<ul><li><code>stageName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>status</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>webhookUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +publishBuildRecord+: Publish build record to IBM Cloud DevOps
++++
<ul><li><code>result</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>gitRepo</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>gitBranch</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>gitCommit</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +publishDeployRecord+: Publish deploy record to IBM Cloud DevOps
++++
<ul><li><code>result</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>appUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +publishSQResults+: Publish SonarQube test results to IBM Cloud DevOps
++++
<ul><li><code>SQHostURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>SQAuthToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>SQProjectKey</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +publishTestResult+: Publish test result to IBM Cloud DevOps
++++
<ul><li><code>type</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>fileLocation</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildNumber</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>orgName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>toolchainId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +sendDeployableMessage+: Send deployable mapping message to OTC
++++
<ul><li><code>status</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>webhookUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
