---
layout: pipelinesteps
title: "JIRA 流水线步骤"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== JIRA 流水线步骤

plugin:jira-steps[在插件索引中查看此插件]

=== +jiraAddComment+: JIRA Steps: 添加提交
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>comment</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraAddWatcher+: JIRA Steps: 添加观察者
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>userName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraAssignIssue+: JIRA Steps: 分配问题
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>userName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraAssignableUserSearch+: JIRA步骤：通过给定项目/ issueKey的用户名，姓名或电子邮件地址搜索可分配的JIRA用户
++++
<ul><li><code>project</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>issueKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>maxResults</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>queryStr</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>startAt</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul>


++++
=== +jiraDeleteIssueLink+: JIRA步骤：删除IssueLink
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraDeleteIssueRemoteLink+: JIRA步骤：通过linkId删除问题的远程链接。
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>linkId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraDeleteIssueRemoteLinks+: JIRA步骤：通过globalId删除问题的远程链接。
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>globalId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraEditComment+: JIRA步骤：编辑问题评论
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>commentId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>comment</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraEditComponent+: JIRA步骤：编辑组件
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>component</code>



++++
=== +jiraEditIssue+: JIRA步骤：编辑问题
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>issue</code>



++++
=== +jiraEditVersion+: JIRA步骤：编辑版本
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>version</code>



++++
=== +jiraGetComment+: JIRA步骤：获取问题评论
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>commentId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetComments+: JIRA步骤：获取问题评论
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetComponent+:JIRA步骤：获取组件
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetComponentIssueCount+: JIRA步骤：获取组件问题数
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetFields+: JIRA步骤：获取字段
++++
<ul><li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetIssue+: JIRA步骤：获取问题
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetIssueLink+: JIRA步骤：获取IssueLink
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetIssueLinkTypes+: JIRA步骤：获取问题链接类型
++++
<ul><li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetIssueRemoteLink+: JIRA步骤：通过linkId获取问题的远程链接。
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>linkId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetIssueRemoteLinks+: JIRA步骤：通过globalId获取问题的远程链接。
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>globalId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetIssueTransitions+: JIRA步骤：获取问题转换
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetIssueWatches+: JIRA步骤：获取问题手表查看
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetProject+: JIRA步骤：获取项目
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetProjectComponents+: JIRA步骤：获取项目组件
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetProjectStatuses+: JIRA步骤：获取项目状态
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetProjectVersions+: JIRA步骤：获取项目版本
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetProjects+: JIRA步骤：获取项目
++++
<ul><li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraGetVersion+: JIRA Steps: Get Version
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraJqlSearch+: JIRA步骤：JQL搜索
++++
<ul><li><code>jql</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>maxResults</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>startAt</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul>


++++
=== +jiraLinkIssues+: JIRA步骤：链接问题
++++
<ul><li><code>type</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>inwardKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>outwardKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>comment</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraNewComponent+: JIRA步骤：创建新组件
++++
<ul><li><code>component</code>



++++
=== +jiraNewIssue+: JIRA步骤：创建新问题
++++
<ul><li><code>issue</code>
<ul><b>Nested Object</b>
<li><code>update</code>
<ul><code>java.lang.Object></code>
</ul></li>
<li><code>fields</code>
<ul><code>java.lang.Object></code>
</ul></li>
</ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraNewIssueRemoteLink+: JIRA步骤：为给定问题创建新的远程链接。
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>remoteLink</code>



++++
=== +jiraNewIssues+: JIRA步骤：创建新问题
++++
<ul><li><code>issues</code>
<ul><b>Nested Object</b>
<li><code>issueUpdates</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>update</code>
<ul><code>java.lang.Object></code>
</ul></li>
<li><code>fields</code>
<ul><code>java.lang.Object></code>
</ul></li>
</ul></li>
<li><code>issues</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>update</code>
<ul><code>java.lang.Object></code>
</ul></li>
<li><code>fields</code>
<ul><code>java.lang.Object></code>
</ul></li>
</ul></li>
</ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +jiraNewVersion+: JIRA步骤：创建新版本
++++
<ul><li><code>version</code>



++++
=== +jiraNotifyIssue+: JIRA步骤：通知问题
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>notify</code>



++++
=== +jiraTransitionIssue+: JIRA Steps: Transition Issue
++++
<ul><li><code>idOrKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>input</code>



++++
=== +jiraUserSearch+: JIRA步骤：通过用户名，姓名或电子邮件地址搜索活跃的JIRA用户。
++++
<ul><li><code>queryStr</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>auditLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>maxResults</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>site</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>startAt</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul>


++++
