---
layout: pipelinesteps
title: "JMS Messaging Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== JMS Messaging Plugin

plugin:jms-messaging[View this plugin on the Plugins Index]

=== +sendCIMessage+: CI Notifier
++++
<ul><li><code>providerName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>overrides</code>
<ul><b>Nested Object</b>
<li><code>topic</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>messageType</code>
<div><div> 
 <p>Type of CI message to be sent.</p> 
</div></div>

<ul><li><b>Values:</b> <code>CodeQualityChecksDone</code>, <code>ComponentBuildDone</code>, <code>Custom</code>, <code>EarlyPerformanceTestingDone</code>, <code>EarlySecurityTestingDone</code>, <code>ImageUploaded</code>, <code>FunctionalTestCoverageDone</code>, <code>FunctionalTestingDone</code>, <code>NonfunctionalTestingDone</code>, <code>OotbTestingDone</code>, <code>PeerReviewDone</code>, <code>ProductAcceptedForReleaseTesting</code>, <code>ProductBuildDone</code>, <code>ProductBuildInStaging</code>, <code>ProductTestCoverageDone</code>, <code>PullRequest</code>, <code>SecurityChecksDone</code>, <code>TestingStarted</code>, <code>TestingCompleted</code>, <code>Tier0TestingDone</code>, <code>Tier1TestingDone</code>, <code>Tier2IntegrationTestingDone</code>, <code>Tier2ValidationTestingDone</code>, <code>Tier3TestingDone</code>, <code>UnitTestCoverageDone</code>, <code>UpdateDefectStatus</code></li></ul></li>
<li><code>messageProperties</code>
<div><div> 
 <p>KEY=value pairs, one per line (Java properties file format) to be used as message properties. Backslashes are used for escaping, so use "\\" for a single backslash. Current build parameters and/or environment variables can be used in form: ${PARAM}. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>messageContent</code>
<div><div> 
 <p>Content of CI message to be sent. Environment variable values may be used in the content to allow customization of the message. Environment variables should use the familiar bash shell format, e.g. ${VARIABLE}. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failOnError</code>
<div><div> 
 <p> Whether you want to fail the build if there is an error sending a message. By default, it is false. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +waitForCIMessage+: CI Subscriber
++++
<div><div> 
 <p>Subscribe to the CI message bus and wait for a message matching the specified JMS selector.</p> 
 <p>The timeout value specifies the maximum number of minutes to wait for a message matching the JMS selector to appear.</p> 
 <p>This step returns the value of the Message content as a string</p> 
 <p></p>
 <pre>
node {
  def messageContent = waitForCIMessage selector: "CI_TYPE = 'code-quality-checks-done' and CI_STATUS = 'failed'"
  // The message content is now available as a variable
  echo messageContent
  // The message content is set as an environment variable
  env.messageContent = messageContent
  sh 'path/to/a/script.sh'
}
</pre>
 <p></p> 
</div></div>
<ul><li><code>providerName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>overrides</code>
<ul><b>Nested Object</b>
<li><code>topic</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>selector</code>
<div><div> 
 <p>JMS selector use to select message to receive.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>timeout</code>
<div><div> 
 <p>Value (in minutes) to wait for a message matching the specified JMS selector.</p> 
</div></div>

<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>checks</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>field</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>expectedValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
