---
layout: pipelinesteps
title: "Klocwork社区插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Klocwork 社区插件

plugin:klocwork[在插件索引中查看此插件]

=== +klocworkIncremental+: Klocwork - 增量差异分析
++++
<ul><li><code>desktopConfig</code>
<ul><b>Nested Object</b>
<li><code>buildSpec</code>
<div><div>
  Build specification to use for analysis. Path is relative to the workspace 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>projectDir</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>cleanupProject</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>reportFile</code>
<div><div>
  XML report file to store Klocwork results in. Optional in case you want to use the XML report for something custom, otherwise a default file is created for the post-build step 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>additionalOpts</code>
<div><div>
  Additional options added to the kwcheck run command. For example, specify the number of jobs/threads to use (--jobs-num) or which filters you would like to apply (e.g. --severity  --taxonomy  --system) 
</div> 
<div> 
 <a href="https://support.roguewave.com/documentation/klocwork/en/current/kwcheck/" rel="nofollow">Documentation</a> - look at subsection "kwcheck run" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>incrementalAnalysis</code>
<div><div> 
 <h3>Klocwork Quality Gateway</h3> 
 <p> This feature allows for quick, incremental analyses of changed source files to enable pre/post-checkin/commit like behaviour. The idea is that only changed files are analysed using the Klocwork Desktop/User tools to replicate the analysis developers would perform using Visual Studio, Eclipse or the command line utility. </p> 
 <h4>Diff File List</h4> 
 <p> The diff file list is the file to contain the changed source files that Klocwork should analyse. It is required that any analysed files should exist in the build specification generated by kwinject </p> 
 <p> IMPORTANT: It is required that any files to be analysed must also exist in the build specification specified </p> 
 <h5>Using Git</h5> 
 <p> If using Git, please provide the previous commit that Git should perform a "diff" with. The change list between the current commit and the specified previous commit will then be added to the diff file list for Klocwork to process by automatically calling "git diff &lt;previous_commit&gt;" during the build. </p> 
 <h5>Manual</h5> 
 <p> If you are not using Git, or want to manually generate the change list using Git, then please select this option. You will need to generate the diff file list with a custom build-step (or similar). Future support for more SCM tools (such as SVN, perforce) may be added depending on demand. The format of the file should be a changed source file per line </p> 
 <p> Future support for more SCM tools (such as SVN, perforce) may be added depending on demand. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>diffAnalysisConfig</code>
<ul><b>Nested Object</b>
<li><code>diffType</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>gitPreviousCommit</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>diffFileList</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul></li>
</ul>


++++
=== +klocworkIntegrationStep1+: Klocwork - 全面整合分析（第1步 - 分析）
++++
<ul><li><code>serverConfig</code>
<ul><b>Nested Object</b>
<li><code>buildSpec</code>
<div><div>
  Build specification to use for analysis. Path is relative to the workspace 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tablesDir</code>
<div><div>
  Specify the location of the tables directory, e.g. ${MY_VAR}/kwtables 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>incrementalAnalysis</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>ignoreCompileErrors</code>
<div><div>
  Ignore compile errors encountered by kwbuildproject. This will not ignore a return code that indicates that kwbuildproject failed to the extent that no results are generated. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>importConfig</code>
<div><div>
  Optional, provide config files to import to the project before running the analysis. If you version control the checker configuration (e.g. analysis_profile.pconf) you can provide the file here and it will be automatically imported each build 
</div> 
<div>
  Specify multiple files separated by comma (",") 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>additionalOpts</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>disableKwdeploy</code>
<div><div>
  By default kwdeploy is run before the analysis to ensure the checkers are up to date. Enabling this setting disables it from running. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
</ul>


++++
=== +klocworkIntegrationStep2+: Klocwork - 全面整合分析（第1步 - 分析）
++++
<ul><li><code>serverConfig</code>
<ul><b>Nested Object</b>
<li><code>tablesDir</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildName</code>
<div><div>
  Specify the name of the build for the Klocwork server, e.g. ${MY_VAR}-${GIT_COMMIT}. If empty, Klocwork uses an auto increment to name the builds 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>additionalOpts</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
=== +klocworkIssueSync+: Klocwork - 跨项目问题同步
++++
<ul><li><code>syncConfig</code>
<ul><b>Nested Object</b>
<li><code>dryRun</code>
<div><div>
  Running the cross synchronisation means reading and writing to the Klocwork database. Therefore we strongly recommend that you first try a Dry Run of the command (which skips the writing) and verify that the command works as expected. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>lastSync</code>
<div><div>
  Specify the "last synchronisation" date (i.e. how far back Klocwork should go when synchronising issue citations). 
</div> 
<div>
  Format is "DD-MM-YYYY hh:mm:ss" 
</div> 
<div>
  For example, "03-00-0000 00:00:00" will go back in time 3 days. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>projectRegexp</code>
<div><div>
  A regular expression that is used to retrieve Klocwork projects that should be processed during synchronisation. For all projects leave empty. 
</div> 
<div>
  For example, if you prepend projects with "DEPT-" to indicate a particular department the regular expression "^DEPT-" will match all these projects 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>statusAnalyze</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>statusIgnore</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>statusNotAProblem</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>statusFix</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>statusFixInNextRelease</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>statusFixInLaterRelease</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>statusDefer</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>statusFilter</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>additionalOpts</code>
<div><div>
  Additional options added to the kwxsync command 
</div> 
<div> 
 <a href="https://support.roguewave.com/documentation/klocwork/en/current/kwxsync/" rel="nofollow">Documentation</a> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
=== +klocworkQualityGateway+: Klocwork - 质量门户
++++
<ul><li><code>gatewayConfig</code>
<ul><b>Nested Object</b>
<li><code>enableServerGateway</code>
<div><div> 
 <h2>Full Integration Analysis Gateway</h2> 
 <p> Create multiple gateways using queries that are sent to the Klocwork server using the web api. </p> 
 <p> Filter issues based on the search query, then provide the status to set the build to, along with the threshold (number of issues to meet this criteria) </p> 
 <p> Note: unless specified the query will run with issue grouping turned off (grouping:off) </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>gatewayServerConfigs</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>jobResult</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>query</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>threshold</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>conditionName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>enableDesktopGateway</code>
<div><div> 
 <h2>Incremental Diff Analysis Gateway</h2> 
 <p> Set a threshold for the incremental diff analsysis gateway. Pass the build if threshold not exceeded, fail otherwise. </p> 
 <p> This checks the XML report generated by the incremental diff analysis build-step. You can filter which issues appear in this report by providing additional options to the incremental diff analysis build-step. </p> 
 <p> This gateway simply counts the total number of issues in the XML report. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>gatewayDesktopConfig</code>
<ul><b>Nested Object</b>
<li><code>threshold</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reportFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul></li>
</ul>


++++
=== +klocworkWrapper+: Klocwork - 构建环境设置
++++
<ul><li><code>serverConfig</code>
<div><div>
  Server configurations are created on the 
 <a rel="nofollow">Configure System</a> page 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>installConfig</code>
<div><div>
  Install configurations are created on the 
 <a rel="nofollow">Configure System</a> page. When used, the specified PATHs are added to the launcher to be used by any build step 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverProject</code>
<div><div>
  The Klocwork server project to run a server build against or to connect a Klocwork desktop analysis to 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ltoken</code>
<div><div>
  (Optional) Specify a custom ltoken location. The Klocwork ltoken is used to authenticate with the Klocwork server. The default ltoken location is in the user's home directory, that is the user running the process. 
 <a href="https://support.roguewave.com/documentation/klocwork/en/current/klocworkltoken/" rel="nofollow">More information</a> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
