---
layout: pipelinesteps
title: "Kubernetes :: Pipeline :: DevOps Steps"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Kubernetes :: Pipeline :: DevOps Steps

plugin:kubernetes-pipeline-devops-steps[View this plugin on the Plugins Index]

=== +approveReceivedEvent+: Updates an Approve event in Elasticsearch
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>approved</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +approveRequestedEvent+: Creates an Approve requested event in Elasticsearch
++++
<ul><li><code>app</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +createEvent+: Creates a JSON payload event in Elasticsearch
++++
<ul><li><code>json</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>index</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +kubernetesApply+: Apply resources to Kubernetes, lazily creating environments and routes
++++
<ul><li><code>file</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>registry</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>readinessTimeout</code>
<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>createNewResources</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>servicesOnly</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>ignoreServices</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>ignoreRunningOAuthClients</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>processTemplatesLocally</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>deletePodsOnReplicationControllerUpdate</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rollingUpgrades</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rollingUpgradePreserveScale</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
