---
layout: pipelinesteps
title: "Kubernetes :: 流水线 :: DevOps 步骤"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Kubernetes :: 流水线 :: DevOps 步骤

plugin:kubernetes-pipeline-devops-steps[在插件索引中查看此插件]

=== +approveReceivedEvent+: 在Elasticsearch中更新批准事件
++++
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>approved</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +approveRequestedEvent+: 在Elasticsearch中创建一个批准请求事件
++++
<ul><li><code>app</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +createEvent+: 在Elasticsearch中创建一个JSON负载事件
++++
<ul><li><code>json</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>index</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +kubernetesApply+: 将资源应用于Kubernetes，懒散地创建环境和路线
++++
<ul><li><code>file</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environment</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>registry</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>readinessTimeout</code>
<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>createNewResources</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>servicesOnly</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>ignoreServices</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>ignoreRunningOAuthClients</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>processTemplatesLocally</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>deletePodsOnReplicationControllerUpdate</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rollingUpgrades</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rollingUpgradePreserveScale</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
