---
layout: pipelinesteps
title: "Kubernetes :: 流水线 :: Arquillian 步骤"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Kubernetes :: 流水线 :: Arquillian Steps

plugin:kubernetes-pipeline-arquillian-steps[在插件索引中查看此插件]

=== +createEnvironment+: 创建测试环境。 找到，安装并等待已安装的资源准备就绪
++++
<ul><li><code>cloud</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>prefix</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>labels</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>annotations</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>scriptEnvironmentVariables</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>environmentSetupScriptUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentTeardownScriptUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentConfigUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentDependencies</code>
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitTimeout</code>
<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>waitForServiceList</code>
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespaceLazyCreateEnabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>namespaceCleanupEnabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>namespaceDestroyEnabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +currentNamespace+: 返回当前命名空间
++++
<ul><li><code>fallbackNamespace</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +inNamespace+: 在arquillian多维数据集kubernetes托管命名空间内运行构建步骤
++++
<ul><li><code>cloud</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>name</code>
<div>The name of the namespace/project to use/create.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>prefix</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>labels</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>annotations</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>namespaceLazyCreateEnabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>namespaceDestroyEnabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +inSession+: 在Arquillian Cube Kubernetes Session中运行构建步骤
++++
<ul><li><code>cloud</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>name</code>
<div>The name of the namespace/project to use/create.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>prefix</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>labels</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>annotations</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>scriptEnvironmentVariables</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>environmentSetupScriptUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentTeardownScriptUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentConfigUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentDependencies</code>
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitTimeout</code>
<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>waitForServiceList</code>
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespaceLazyCreateEnabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>namespaceCleanupEnabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>namespaceDestroyEnabled</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
