---
layout: pipelinesteps
title: "Kubernetes持续部署插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Kubernetes持续部署插件

plugin:kubernetes-cd[在插件索引中查看此插件]

=== +kubernetesDeploy+:部署到 Kubernetes
++++
<ul><li><code>configs</code> (optional)
<div><div> 
 <p> The path patterns for the Kubernetes configurations you want to deploy, in the form of <a href="https://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant glob syntax</a>. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsType</code> (optional)
<div><div> 
 <p> Choose how to get the <a href="https://kubernetes.io/docs/concepts/cluster-administration/authenticate-across-clusters-kubeconfig/" rel="nofollow"> kubeconfig file</a> to authenticate with the Kubernetes cluster management endpoint. </p> 
 <p> 3 options are supported: </p> 
 <ol> 
  <li><b>Authenticate with Kube config file</b> - Get the kubeconfig file from the workspace path.</li> 
  <li><b>Fetch cluster details through SSH connection to the master node</b> - Get the <code>~/.kube/config</code> file through an SSH connection to the master node.</li> 
  <li><b>Fill credentials details directly</b> - Fill the contents in kubeconfig file directly.</li> 
 </ol> 
 <p> See also: <a href="https://kubernetes.io/docs/tasks/tools/install-kubectl/#configure-kubectl" rel="nofollow">Configure kubectl</a> </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dockerCredentials</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>url</code>
<div><div>
  URL to the Docker registry you are using. May be left blank to use the public DockerHub registry (currently 
 <code>https://index.docker.io/v1/</code>). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>enableConfigSubstitution</code> (optional)
<div><div> 
 <p> Substitute variables (in the form <code>$VARIABLE</code> or <code>${VARIABLE}</code>) in the configuration with values from Jenkins environment variables. </p> 
 <p> This allows you to use dynamic values produced during the build in your Kubernetes configurations, e.g., a dynamically generated Docker image tag which will be used later in the deployment. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>kubeConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>path</code> (optional)
<div><div>
  The 
 <code>kubeconfig</code> file path relative to the current Jenkins workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>secretName</code> (optional)
<div><div>
  The secret name that you can use in the Kubernetes Deployment configuration for the 
 <code>imagePullSecrets</code> entry. Environment variable substitution are supported for the name input, so you can use available environment variables to construct the name dynamically, e.g., 
 <code>some-secret-$BUILD_NUMBER</code>. The name should be in the pattern 
 <code>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*</code>, i.e., dot (.) concatenated sequences of hyphen (-) separated alphanumeric words. (See 
 <a href="https://kubernetes.io/docs/concepts/overview/working-with-objects/names/" title="Kubernetes Names" rel="nofollow"> Kubernetes Names</a>) 
 <p> If left blank, the plugin will generate a name based on the build name. </p>
 <p> The secret name will be exposed with the environment variable <code>$KUBERNETES_SECRET_NAME</code>. You can use this in your Kubernetes configuration to reference the updated secret when the "Enable Variable Substitution in Config" option is enabled. </p>
 <pre><code>
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: some.private.registry.domain/nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
</code></pre> 
 <p> Note that once the secret is created, it will only be updated by the plugin. You have to manually delete it when it is not used anymore. If this is a problem, you may use fixed name so every time the job runs, the secret gets updated and no new secret is created. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>secretNamespace</code> (optional)
<div><div>
  The Kubernetes namespace in which the secrets will be created with the credentials configured below. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ssh</code> (optional)
<ul><b>Nested Object</b>
<li><code>sshCredentialsId</code> (optional)
<div><div>
  The SSH login credentials. Can be: 
 <ul> 
  <li>Username with password, or</li> 
  <li>SSH Username with private key</li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sshServer</code> (optional)
<div><div>
  The SSH server address (
 <code>&lt;host&gt;[:&lt;port&gt;]</code>) of the Kubernetes master node. If port is omitted, the default SSH port 22 will be used. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>textCredentials</code> (optional)
<ul><b>Nested Object</b>
<li><code>certificateAuthorityData</code> (optional)
<div><div>
  The 
 <code>clusters.cluster.certificate-authority-data</code> value in the 
 <code>kubeconfig</code> file. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>clientCertificateData</code> (optional)
<div><div>
  The 
 <code>users.user.client-certificate-data</code> value in the 
 <code>kubeconfig</code> file. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>clientKeyData</code> (optional)
<div><div>
  The 
 <code>users.user.client-key-data</code> value in the 
 <code>kubeconfig</code> file. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverUrl</code> (optional)
<div><div>
  The 
 <code>clusters.cluster.server</code> address in the 
 <code>kubeconfig</code>. Generally, it should start with 
 <code>https://</code>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
