---
layout: pipelinesteps
title: "Kubernetes :: Pipeline :: Kubernetes Steps"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Kubernetes :: Pipeline :: Kubernetes Steps

plugin:kubernetes-pipeline-steps[View this plugin on the Plugins Index]

=== +buildImage+: Builds a Docker Image
++++
<div><div>
  Builds a docker image. 
</div></div>
<ul><li><code>name</code>
<div>The  The name of the docker image.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>email</code> (optional)
<div>This email will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ignorePatterns</code> (optional)
<ul><code>java.util.ArrayList</code>
</ul></li>
<li><code>password</code> (optional)
<div>The  This password will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>path</code> (optional)
<div>The  The path of the folder that contains the docker image.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>rm</code> (optional)
<div>The  Flag to remove intermediate layers.</div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>timeout</code> (optional)
<div>The  The amount of time to wait for the build to complete.</div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>username</code> (optional)
<div>The  This username will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +pushImage+: Pushes a Docker Image
++++
<div><div>
  Pushes a docker image to a docker registry. 
</div></div>
<ul><li><code>name</code>
<div>The  The name of the docker image.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>email</code> (optional)
<div>This email will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>password</code> (optional)
<div>The  This password will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>registry</code> (optional)
<div>The  Explicitly specify a remote registry if not present in the image repository.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tag</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>timeout</code> (optional)
<div>The  The amount of time to wait for the push to complete.</div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>username</code> (optional)
<div>The  This username will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +tagImage+: Tags a Docker Image
++++
<div><div>
  Tags a docker image. 
</div></div>
<ul><li><code>name</code>
<div>The  The name of the docker image.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tag</code>
<div>The  The tag.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>email</code> (optional)
<div>This email will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>force</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>password</code> (optional)
<div>The  This password will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repo</code> (optional)
<div>The  The image repository in which the tag will be created.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>username</code> (optional)
<div>The  This username will be used in the fallback docker auth config object, that will be used if matching configuration is found for the registry.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +withPod+: Run build steps in a MyPod
++++
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>containers</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>name</code> (optional)
<div>The name for the container to be run. One container is automatically created with name 
<code>jnlp</code>, and runs the Jenkins JNLP agent service. In order to replace the default JNLP agent, the name of the container with the custom JNLP image must be 
<code>jnlp</code>.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>image</code> (optional)
<div>Docker image ID for a jenkins JNLP agent. This image is responsible to run a jenkins jnlp bootstrap agent and connect to Jenkins master. Secret key and agent name as well as jenkins callback URL are passed as argument as expected by 
<code>hudson.remoting.jnlp.Main</code>.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>alwaysPullImage</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>args</code> (optional)
<div>Arguments to pass to the command. ${computer.jnlpmac} and ${computer.name} are replaced with the agent secret and name respectively.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>command</code> (optional)
<div>Override the image entrypoint with a different one</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>envVars</code> (optional)
<div>The environment variables to pass to the container.</div>

<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>containerEnvVar</code></li>
<ul><li><code>key</code>
<div>The environment variable key.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<div>The environment variable value.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>envVar</code></li>
<ul><li><code>key</code>
<div>The environment variable key.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<div>The environment variable value.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>podEnvVar</code></li>
<ul><li><code>key</code>
<div>The environment variable key.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<div>The environment variable value.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>secretEnvVar</code></li>
<ul><li><code>key</code>
<div>The environment variable key.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>secretName</code>
<div>Name of secret to lookup from Kubernetes.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>secretKey</code>
<div>Key of secret to lookup from Kubernetes.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>livenessProbe</code> (optional)
<ul><b>Nested Object</b>
<li><code>execArgs</code>
<div>Command executed by the liveness probe.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>timeoutSeconds</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>initialDelaySeconds</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>failureThreshold</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>periodSeconds</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>successThreshold</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul></li>
<li><code>ports</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>name</code> (optional)
<div>The name of the port</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>containerPort</code> (optional)
<div>Port to expose into the pod</div>

<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>hostPort</code> (optional)
<div>Port to expose onto the host</div>

<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul></li>
<li><code>privileged</code> (optional)
<div>Flag to mark the container as privileged.</div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>resourceLimitCpu</code> (optional)
<div>Kubernetes Resources Limit of CPU This value can be set to control the CPU resource limit passed when creating the Jenkins agent Docker container in Kubernetes. Unlike a resource request, this is the upper limit of resources used by your Jenkins Agent container. When left blank, the defaults of your Kubernetes cluster will be used. For more info, see the 
<a href="http://kubernetes.io/docs/user-guide/compute-resources/" rel="nofollow">Kubernetes docs.</a> e.g. `500m`.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>resourceLimitMemory</code> (optional)
<div>Kubernetes Resources Limit of Memory This value can be set to control the memory resource limit passed when creating the Jenkins agent Docker container in Kubernetes. Unlike a resource request, this is the upper limit of resources used by your Jenkins Agent container. When left blank, the defaults of your Kubernetes cluster will be used. For more info, see the 
<a href="http://kubernetes.io/docs/user-guide/compute-resources/" rel="nofollow">Kubernetes docs.</a> e.g. `250Mi`.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>resourceRequestCpu</code> (optional)
<div>Kubernetes Resources Request of CPU This value can be set to control the CPU resources requested when creating the Jenkins agent Docker container in Kubernetes. When left blank, the defaults of your Kubernetes cluster will be used. For more info, see the 
<a href="http://kubernetes.io/docs/user-guide/compute-resources/" rel="nofollow">Kubernetes docs.</a> e.g. `500m`.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>resourceRequestMemory</code> (optional)
<div>Kubernetes Resources Request of Memory This value can be set to control the memory resources requested when creating the Jenkins agent Docker container in Kubernetes. When left blank, the defaults of your Kubernetes cluster will be used. For more info, see the 
<a href="http://kubernetes.io/docs/user-guide/compute-resources/" rel="nofollow">Kubernetes docs.</a> e.g. `250Mi`.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ttyEnabled</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>workingDir</code> (optional)
<div>Path to the root of the workspace from the view point of this node, such as "/home/jenkins", this need not be absolute provided that the launcher establishes a consistent working directory, such as "./.jenkins-agent".</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>envVars</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>volumes</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>configMapVolume</code></li>
<ul><li><code>mountPath</code>
<div>Path to mount this volume inside the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>configMapName</code>
<div>The name of the Kubernetes Config Map to mount into the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>emptyDirVolume</code></li>
<ul><li><code>mountPath</code>
<div>Path to mount this volume inside the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>memory</code>
<div>Flag for in-memory volume.</div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>hostPathVolume</code></li>
<ul><li><code>hostPath</code>
<div>File or directory on the host node's filesystem to mount into the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>mountPath</code>
<div>Path to mount this volume inside the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>nfsVolume</code></li>
<ul><li><code>serverAddress</code>
<div>NFS Server Address.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverPath</code>
<div>NFS Server Path.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>readOnly</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>mountPath</code>
<div>Path to mount this volume inside the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>persistentVolumeClaim</code></li>
<ul><li><code>mountPath</code>
<div>Path to mount this volume inside the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>claimName</code>
<div>The claim name.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>readOnly</code>
<div>Flag for read-only volume.</div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>secretVolume</code></li>
<ul><li><code>mountPath</code>
<div>Path to mount this volume inside the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>secretName</code>
<div>The name of the Kubernetes Secret to mount into the pod.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>serviceAccount</code>
<div>The service account to use.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>nodeSelector</code>
<div>Specify which nodes the pod should operate on by providing a comma separated list of node labels: `label1=value1,label2=value2`.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>workingDir</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>labels</code>
<ul><code>java.lang.String></code>
</ul></li>
</ul>


++++
