---
layout: pipelinesteps
title: "Liquibase Runner"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Liquibase Runner

plugin:liquibase-runner[在插件索引中查看此插件]

=== +liquibaseDbDoc+: 生成 Liquibase DbDoc
++++
<ul><li><code>changeLogFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>basePath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeLogParameterList</code> (optional)
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeLogParameters</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classpath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>contexts</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>databaseEngine</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultSchemaName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>driverClassname</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>labels</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>liquibasePropertiesPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>outputDirectory</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>url</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +liquibaseRollback+: 回滚liquibase更改
++++
<ul><li><code>changeLogFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>basePath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeLogParameterList</code> (optional)
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeLogParameters</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classpath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>contexts</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>databaseEngine</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultSchemaName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>driverClassname</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>labels</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>liquibasePropertiesPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>rollbackCount</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>rollbackLastHours</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>rollbackToDate</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>rollbackToTag</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>url</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +liquibaseUpdate+: 评估liquibase变更集
++++
<ul><li><code>changeLogFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>basePath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeLogParameterList</code> (optional)
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeLogParameters</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classpath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>contexts</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>databaseEngine</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultSchemaName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>driverClassname</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dropAll</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>labels</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>liquibasePropertiesPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tagOnSuccessfulBuild</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>testRollbacks</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>url</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
