---
layout: pipelinesteps
title: "Questa VRM"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Questa VRM

plugin:mentor-questa-vrm[在插件索引中查看此插件]

=== +questavrm+: 发布Questa VRM回归结果
++++
<ul><li><code>vrmdata</code>
<div><div> 
 <b>VRMDATA Directory</b> 
 <p>Specify the location of where the regression results will be stored. By default, VRM creates a directory called <em>VRMDATA</em> which will be located in the CWD where the regression is invoked. Alternatively this can be overridden by specifying a directory upon invocation as follows:</p> 
 <p>&nbsp;&nbsp;<em>vrun -vrmdata &lt;my_directory&gt; ...</em></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>collectCoverage</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>extraArgs</code> (optional)
<div><div> 
 <b>Extra VRM status report options </b> 
 <p>Extra options to be passed to <em>vrun -status</em>.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>healthScaleFactor</code> (optional)
<ul><li><b>Type:</b> <code>double</code></li></ul></li>
<li><code>htmlReport</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>testDataPublishers</code> (optional)
<ul><b>Array/List</b><br/>
<code>hudson.tasks.junit.TestDataPublisher</code>
</ul></li>
<li><code>vrmhtmldir</code> (optional)
<div><div> 
 <b>VRM HTML Directory</b> 
 <p>Specify the directory where the html report will be stored.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>vrunExec</code> (optional)
<div><div> 
 <b>Questa VRM Executables Directory</b> 
 <p>Set path to Questa VRM executable. This can be just <em>"vrun"</em> or a complete path. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
