---
layout: pipelinesteps
title: "Nexus平台插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Nexus平台插件

plugin:nexus-jenkins-plugin[在插件索引中查看此插件]

=== +nexusPolicyEvaluation+: 调用Nexus策略评估
++++
<ul><li><code>iqStage</code>
<div><div>
  Controls the stage the policy evaluation will be run against on the Nexus IQ Server. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>iqApplication</code>
<div><div>
  Select an IQ Application from a list of available IQ Applications. Determines the policy elements (policies, labels, and license threat groups) to associate with this build, and is managed via the Nexus IQ Server. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failBuildOnNetworkError</code> (optional)
<div><div>
  Controls the build outcome if there is a failure in communicating with the Nexus IQ Server (e.g. network outage). If checked, the build will be marked as failed. Otherwise, the build is only marked as unstable. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>iqScanPatterns</code> (optional)
<div><div>
  A list of 
 <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant-style patterns</a> relative to the workspace root that denote the files/archives to be scanned, e.g. 
 <code>**/target/*.war</code> or 
 <code>**/target/*.ear</code>. If unspecified, the scan will default to the patterns 
 <code>**/*.jar, **/*.war, **/*.ear, **/*.zip, **/*.tar.gz</code>. 
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>scanPattern</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>jobCredentialsId</code> (optional)
<div><div>
  To use the IQ server credentials configured in Nexus global configuration for this job select 
 <code>- none -</code>, otherwise select different credentials. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>moduleExcludes</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>moduleExclude</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
=== +nexusPublisher+: Nexus 仓库管理程序发布者
++++
<ul><li><code>nexusInstanceId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>nexusRepositoryId</code>
<div>The publisher currently supports hosted release Maven 2 repositories. This list is limited to repositories which meet this requirement.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>packages</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>$class: 'MavenPackage'</code></li>
<ul><li><code>mavenCoordinate</code>
<ul><b>Nested Object</b>
<li><code>groupId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>version</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>packaging</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>mavenAssetList</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>filePath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classifier</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>extension</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul></ul></li>
</ul>


++++
