---
layout: pipelinesteps
title: "Nexus Artifact Uploader"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Nexus Artifact Uploader

plugin:nexus-artifact-uploader[View this plugin on the Plugins Index]

=== +nexusArtifactUploader+: Nexus Artifact Uploader
++++
<ul><li><code>nexusVersion</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>protocol</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>nexusUrl</code>
<div><div>
 If Nexus Url is 
 <em>http://mynexusrepo:8081/nexus</em> the value for this field is 
 <em>mynexusrepo:8081/nexus</em>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>groupId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>version</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repository</code>
<div><div>
 RepositoryId of the Repository in Nexus to which this artifact to be uploaded.
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifacts</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>artifactId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>type</code>
<div><div>
 Extension of the artifact for ex: artifact file name is 
 <em>artifact.zip</em> the extension is 
 <em>zip</em>.
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classifier</code>
<div><div>
 Classifier of the artifact.
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>file</code>
<div><div>
 File path in the workspace. ex:
 <em>artifact.zip or artifact.jar</em>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
