---
layout: pipelinesteps
title: "OctoPerf Load Testing Plugin."
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== OctoPerf Load Testing Plugin.

plugin:octoperf[View this plugin on the Plugins Index]

=== +octoPerfTest+: Runs test in OctoPerf Cloud
++++
<ul><li><code>credentialsId</code> (optional)
<div><div>
 Select the Octoperf credentials to use.
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>scenarioId</code> (optional)
<div><div>
  OctoPerf's plugin for Jenkins allows users to automate load tests from the Cloud. 
 <br> Just choose the scenario you want to run. Let Jenkins start and stop the test and document the results. 
 <br> After the run, a test report will be generated directly into Jenkins and 
 <a href="https://app.octoperf.com" rel="nofollow">your OctoPerf account.</a> 
 <br> If the test list is empty, you must insert your unique OctoPerf Username and password into the 
 <a rel="nofollow">Jenkins settings</a>, or create a test in 
 <a href="https://app.octoperf.com" rel="nofollow">your OctoPerf account.</a> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>stopConditions</code> (optional)
<ul><b>Array/List</b><br/>
<code>org.jenkinsci.plugins.octoperf.conditions.TestStopCondition</code>
</ul></li>
</ul>


++++
