---
layout: pipelinesteps
title: "Office 365 Connector"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Office 365 Connector

plugin:Office-365-Connector[View this plugin on the Plugins Index]

=== +office365ConnectorSend+: office365ConnectorSend
++++
<div><div>
  This is the main text in a message attachment, and can contain standard message markup. The content will automatically collapse if it contains 700+ characters or 5+ linebreaks, and will display a "Show more..." link to expand the content. Message may include global variables, for example environment and currentBuild variables:
 <br> 
 <code> office365ConnectorSend message:"started ${env.JOB_NAME} ${env.BUILD_NUMBER} (&lt;${env.BUILD_URL}|Open&gt;)" </code> 
</div></div>
<ul><li><code>webhookUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>color</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>message</code> (optional)
<div><div>
  This is the main text in a message attachment, and can contain standard message markup. The content will automatically collapse if it contains 700+ characters or 5+ linebreaks, and will display a "Show more..." link to expand the content. Message may include global variables, for example environment and currentBuild variables:
 <br> 
 <code> office365ConnectorSend message:"started ${env.JOB_NAME} ${env.BUILD_NUMBER} (&lt;${env.BUILD_URL}|Open&gt;)" </code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>status</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
