---
layout: pipelinesteps
title: "OpenShift Pipeline Jenkins Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== OpenShift Pipeline Jenkins Plugin

plugin:openshift-pipeline[View this plugin on the Plugins Index]

=== +openshiftBuild+: Trigger OpenShift Build
++++
<ul><li><code>bldCfg</code>
<div><div>
  If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildName</code> (optional)
<div><div>
  The value here is what you supply with the --from-build option when invoking the OpenShift `oc start-build` command. It allows you to point to OpenShift build to a previously run build, and run another build with exactly the same source and destination metadata. If you do not supply a value, the plugin will generate a new OpenShift build based on the Build Configuration referenced. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>checkForTriggeredDeployments</code> (optional)
<div><div>
  This flag is the toggle for turning on or off the verification that any deployments triggered by this build's output fired. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>commitID</code> (optional)
<div><div>
  The value here is what you supply with the --commit option when invoking the OpenShift `oc start-build` command. It allows you to point the OpenShift build to a specific commit hash from the git-log of the source repository. If you do not supply a value, the plugin assumes the latest version from the source repository should be used. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>env</code> (optional)
<div><div>
  Specify a list of environment variables to include in the build (see `oc start-build -e ...`). 
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>name</code>
<div><div>
  The name of the environment variable to set. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<div><div>
  The value for the environment variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>showBuildLogs</code> (optional)
<div><div>
  Indicates whether the build logs get dumped to the console of the Jenkins build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitTime</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitUnit</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftCreateResource+: Create OpenShift Resource(s)
++++
<ul><li><code>jsonyaml</code>
<div><div>
  The JSON or YAML formatted text that conforms to the schema for defining the various OpenShift resources. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftDeleteResourceByJsonYaml+: Delete OpenShift Resource(s) from JSON or YAML
++++
<ul><li><code>jsonyaml</code>
<div><div>
  The JSON or YAML formatted text that conforms to the schema for defining the various OpenShift resources. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftDeleteResourceByKey+: Delete OpenShift Resource(s) by Key
++++
<ul><li><code>types</code>
<div><div>
  The comma separated list of types of API objects to delete. See https://docs.openshift.org/latest/rest_api/index.html for the supported types. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>keys</code>
<div><div>
  The comma separated list of keys of the API objects to delete. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftDeleteResourceByLabels+: Delete OpenShift Resource(s) using Labels
++++
<ul><li><code>types</code>
<div><div>
  The comma separated list of types of API objects to delete, where those objects have labels corresponding to the specified key/value pairs. See https://docs.openshift.org/latest/rest_api/index.html for the supported types. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>keys</code>
<div><div>
  The comma separated list of keys of the labels in the API objects to delete. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>values</code>
<div><div>
  The comma separated list of values of the labels in the API objects to delete. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftDeploy+: Trigger OpenShift Deployment
++++
<ul><li><code>depCfg</code>
<div><div>
  If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitTime</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitUnit</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftExec+: OpenShift Exec
++++
<ul><li><code>pod</code>
<div><div>
  The pod in which to execute a command. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>arguments</code> (optional)
<div><div>
  Specify a list of arguments to pass to the command. 
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>value</code>
<div><div>
  The value for the environment variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>command</code> (optional)
<div><div>
  The name of the command to execute. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>container</code> (optional)
<div><div>
  The container in which to execute a command. If not specified, the first container in the pod will be used. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitTime</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitUnit</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftImageStream+: OpenShift ImageStreams
++++
<ul><li><code>name</code> (optional)
<div><div>
  The name of the ImageStream is what shows up in the NAME column if you dump all the ImageStream's with the `oc get is` command invocation. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tag</code> (optional)
<div><div>
  The specific image tag within the ImageStream to monitor. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changelog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>poll</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftScale+: Scale OpenShift Deployment
++++
<ul><li><code>depCfg</code>
<div><div>
  If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>replicaCount</code>
<div><div>
  The value here should be the number of started pods desired for the deployment specified. It is the equivalent of the value supplied to --replicas with an `oc scale` command invocation. This is a required parameter. If an integer is not specified here, this build step can not be added to the job. Note: specifying a 0 is allowed, and means you do not want any pods for the specified deployment config running. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verifyReplicaCount</code> (optional)
<div><div>
  This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitTime</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitUnit</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftTag+: Tag OpenShift Image
++++
<ul><li><code>srcStream</code>
<div><div>
  The name of the ImageStream for the existing tag. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>srcTag</code>
<div><div>
  The name of the existing tag, or an actual, existing image ID. The image referenced will have the new tag applied to it. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>destStream</code>
<div><div>
  One or more ImageStream names in a comma delimited list. If multiple streams and multiple destination tags are specified, the two lists must contain the same number of elements. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>destTag</code>
<div><div>
  One or more tag names in a comma delimited list. If multiple streams and multiple destination tags are specified, the two lists must contain the same number of elements. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>alias</code> (optional)
<div><div>
  This flag is the equivalent of the `--alias` option for the `oc tag` command. When false, the destination tag type is "ImageStreamImage", and when true, the destination tag type is "ImageStreamTag". 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>destinationAuthToken</code> (optional)
<div><div>
  The value here is what you supply with the --token option when invoking the OpenShift `oc` command. If you do not supply a value, the plugin will assume it is running in the OpenShift Jenkins image and attempt to load the kubernetes service account token stored in that image. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>destinationNamespace</code> (optional)
<div><div>
  The value here should match the value from the output from `oc project` if you created the resources related to this task from the command line. If nothing is specified, the plugin will inspect the PROJECT_NAME environment variable. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftVerifyBuild+: Verify OpenShift Build
++++
<ul><li><code>bldCfg</code>
<div><div>
  If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>checkForTriggeredDeployments</code> (optional)
<div><div>
  This flag is the toggle for turning on or off the verification that any deployments triggered by this build's output fired. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitTime</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitUnit</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftVerifyDeployment+: Verify OpenShift Deployment
++++
<ul><li><code>depCfg</code>
<div><div>
  If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>replicaCount</code> (optional)
<div><div>
  This optional field's value represents the number expected running pods for the deployment for the DeploymentConfig specified. If no value is specified it will work the number of running pods against the desired replica count in the DeploymentConfig. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verifyReplicaCount</code> (optional)
<div><div>
  This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitTime</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>waitUnit</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +openshiftVerifyService+: Verify OpenShift Service
++++
<ul><li><code>svcName</code>
<div><div>
  The equivalent to the name supplied to a `oc get service` command line invocation. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>apiURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>namespace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>retryCount</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
