---
layout: pipelinesteps
title: "OpenShift Client Jenkins Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== OpenShift Client Jenkins Plugin

plugin:openshift-client[View this plugin on the Plugins Index]

=== +_OcAction+: Internal utility function for OpenShift DSL
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>project</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>skipTLSVerify</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>caPath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verb</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>advArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>verbArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>userArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>options</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>token</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>streamStdOutToConsolePrefix</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reference</code>
<ul><code>java.lang.String></code>
</ul></li>
<li><code>logLevel</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul>


++++
=== +_OcContextInit+: Internal utility function for OpenShift DSL
++++
<ul></ul>


++++
=== +_OcWatch+: Internal utility function for OpenShift DSL
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>project</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>skipTLSVerify</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>caPath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verb</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>advArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>verbArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>userArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>options</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>token</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>logLevel</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul>


++++
