---
layout: pipelinesteps
title: "P4 Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== P4 Plugin

plugin:p4[View this plugin on the Plugins Index]

=== +p4+: P4 Groovy
++++
<ul><li><code>credential</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>workspace</code>
<ul><b>Nested Choice of Objects</b>
<li><code>manualSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>Workspace name</b> 
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>spec</code>
<ul><b>Nested Object</b>
<li><code>allwrite</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>clobber</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>compress</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>locked</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modtime</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rmdir</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>streamName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>line</code>
<div><div> 
 <b>Line Endings</b> 
 <p>Set line-ending character(s) for client text files.</p> 
 <ul> 
  <li> <b>UNIX</b> <p>linefeed: UNIX style.</p> </li> 
  <li> <b>MAC</b> <p>carriage return: Macintosh style. (obsolete)</p> </li> 
  <li> <b>WIN</b> <p>carriage return-linefeed: Windows style.</p> </li> 
  <li> <b>SHARE</b> <p>hybrid: writes UNIX style but reads UNIX, Mac or Windows style.</p> </li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>view</code>
<div><div> 
 <b>View</b> 
 <p>Lines to map depot files into the client workspace.</p> 
 <p>Maps files in the depot to files in your client workspace. Defines the files that you want in your client workspace and specifies where you want them to reside. The default view maps all depot files onto the client. See 'p4 help views' for view syntax. A new view takes effect on the next 'p4 sync'.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeView</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>type</code>
<div><div> 
 <b>Type</b> 
 <p>Type of client: writeable/readonly/partitioned/graph</p> 
 <p>By default all clients are 'writeable', certain clients are short lived and perform long sync and build cycles. Over time these build clients can fragment the 'db.have' table which is used to track what files a client has synced. Setting a type of 'readonly' gives the client its own personal 'db.have' database table. A 'readonly' client cannot 'edit' or 'submit' files, however for build automation this is not usually a requirement and the performance tradeoff is worth considering if your build automation is causing issues with the 'db.have' table. This option requires that an administrator has first configured the 'client.readonly.dir' setting. If it is necessary to submit changes as part of your build, you may specify a 'partitioned' client: like a 'reaonly' client, this type also has a separate 'db.have' table under the 'client.readonly.dir' directory, but allows journalled 'edit' and 'submit' of files.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverID</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>backup</code>
<div><div> 
 <b>Backup</b> 
 <p>Client's participation in backup enable/disable. If not specified backup of a writable client defaults to enabled.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>specFileSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>An existing workspace</b> 
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>specPath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>staticSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>An existing workspace</b> 
 <p>Specify the name of an existing workspace in Perforce to be used as the Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>streamSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>streamName</code>
<div><div> 
 <b>Stream codeline</b> 
 <p>Specify the full Perforce depot path for the given stream. If connected to a Perforce server the auto-text fill should list possible streams.</p> 
 <i>For example: //stream-depot/main-stream</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code>
<div><div> 
 <b>Workspace name formatter</b> 
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p> 
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>templateSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>templateName</code>
<div><div> 
 <b>Templace workspace</b> 
 <p>Specify the name of an existing workspace in Perforce used to create or update a Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code>
<div><div> 
 <b>Workspace name formatter</b> 
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p> 
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul>


++++
=== +p4approve+: P4 ApproveImpl Review
++++
<ul><li><code>credential</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>review</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>status</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +p4publish+: P4 Publish
++++
<ul><li><code>credential</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>workspace</code>
<ul><b>Nested Choice of Objects</b>
<li><code>manualSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>Workspace name</b> 
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>spec</code>
<ul><b>Nested Object</b>
<li><code>allwrite</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>clobber</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>compress</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>locked</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modtime</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rmdir</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>streamName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>line</code>
<div><div> 
 <b>Line Endings</b> 
 <p>Set line-ending character(s) for client text files.</p> 
 <ul> 
  <li> <b>UNIX</b> <p>linefeed: UNIX style.</p> </li> 
  <li> <b>MAC</b> <p>carriage return: Macintosh style. (obsolete)</p> </li> 
  <li> <b>WIN</b> <p>carriage return-linefeed: Windows style.</p> </li> 
  <li> <b>SHARE</b> <p>hybrid: writes UNIX style but reads UNIX, Mac or Windows style.</p> </li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>view</code>
<div><div> 
 <b>View</b> 
 <p>Lines to map depot files into the client workspace.</p> 
 <p>Maps files in the depot to files in your client workspace. Defines the files that you want in your client workspace and specifies where you want them to reside. The default view maps all depot files onto the client. See 'p4 help views' for view syntax. A new view takes effect on the next 'p4 sync'.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeView</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>type</code>
<div><div> 
 <b>Type</b> 
 <p>Type of client: writeable/readonly/partitioned/graph</p> 
 <p>By default all clients are 'writeable', certain clients are short lived and perform long sync and build cycles. Over time these build clients can fragment the 'db.have' table which is used to track what files a client has synced. Setting a type of 'readonly' gives the client its own personal 'db.have' database table. A 'readonly' client cannot 'edit' or 'submit' files, however for build automation this is not usually a requirement and the performance tradeoff is worth considering if your build automation is causing issues with the 'db.have' table. This option requires that an administrator has first configured the 'client.readonly.dir' setting. If it is necessary to submit changes as part of your build, you may specify a 'partitioned' client: like a 'reaonly' client, this type also has a separate 'db.have' table under the 'client.readonly.dir' directory, but allows journalled 'edit' and 'submit' of files.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverID</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>backup</code>
<div><div> 
 <b>Backup</b> 
 <p>Client's participation in backup enable/disable. If not specified backup of a writable client defaults to enabled.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>specFileSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>An existing workspace</b> 
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>specPath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>staticSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>An existing workspace</b> 
 <p>Specify the name of an existing workspace in Perforce to be used as the Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>streamSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>streamName</code>
<div><div> 
 <b>Stream codeline</b> 
 <p>Specify the full Perforce depot path for the given stream. If connected to a Perforce server the auto-text fill should list possible streams.</p> 
 <i>For example: //stream-depot/main-stream</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code>
<div><div> 
 <b>Workspace name formatter</b> 
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p> 
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>templateSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>templateName</code>
<div><div> 
 <b>Templace workspace</b> 
 <p>Specify the name of an existing workspace in Perforce used to create or update a Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code>
<div><div> 
 <b>Workspace name formatter</b> 
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p> 
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>publish</code>
<ul><b>Nested Choice of Objects</b>
<li><code>shelve</code></li>
<ul><li><code>description</code>
<div><div> 
 <p>The change description used to shelve or submit the assets to Perforce. ${VAR} variables are expanded base on the system environment. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>onlyOnSuccess</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>delete</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>revert</code>
<div><div> 
 <p>Reverts open files in the pending changelist, but leaves the content in the workspace unchanged ('p4 revert -k')</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>submit</code></li>
<ul><li><code>description</code>
<div><div> 
 <p>The change description used to shelve or submit the assets to Perforce. ${VAR} variables are expanded base on the system environment. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>onlyOnSuccess</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>delete</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>reopen</code>
<div><div> 
 <p>Submitted files are reopened, allowing subsequent modification.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>purge</code>
<div><div> 
 <p>The Perforce server only stores n number of revisions, where n is a number 1-10 or 16,32,64,128,256,512. Older revisions are then purged as new revisions are added. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul>


++++
=== +p4sync+: P4 Sync
++++
<ul><li><code>credential</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changelog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>charset</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>depotPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>poll</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>populate</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>autoClean</code></li>
<ul><li><code>replace</code>
<div><div> 
 <b>REPLACE missing/modified files</b> 
 <p>Perforce will check out and overwrite any depot files which are either missing from workspace, or have been modified locally.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>delete</code>
<div><div> 
 <b>DELETE generated files</b> 
 <p>Perforce will delete any local files that are not in the depot.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>tidy</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modtime</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>quiet</code>
<div><div> 
 <b>Suppressing info messages</b> 
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>pin</code>
<div><div> 
 <b>Pinning a build at Perforce Label</b> 
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will sync only to the specified label. Any other specified change or label will be ignored.</p> 
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>parallel</code>
<ul><b>Nested Object</b>
<li><code>enable</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>path</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>threads</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>minfiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>minbytes</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul><li><code>previewOnly</code></li>
<ul><li><code>quiet</code>
<div><div> 
 <b>Suppressing info messages</b> 
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>pin</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>flushOnly</code></li>
<ul><li><code>quiet</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>pin</code>
<div><div> 
 <b>Pinning a build at Perforce Label</b> 
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will flush only to the specified label or changelist number. Any other specified change or label will be ignored.</p> 
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>forceClean</code></li>
<ul><li><code>have</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>quiet</code>
<div><div> 
 <b>Suppressing info messages</b> 
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>pin</code>
<div><div> 
 <b>Pinning a build at Perforce Label</b> 
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will sync only to the specified label. Any other specified change or label will be ignored.</p> 
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>parallel</code>
<ul><b>Nested Object</b>
<li><code>enable</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>path</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>threads</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>minfiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>minbytes</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul><li><code>graphClean</code></li>
<ul><li><code>quiet</code>
<div><div> 
 <b>Suppressing info messages</b> 
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>pin</code>
<div><div> 
 <b>Pinning a build at Perforce Label</b> 
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will sync only to the specified label. Any other specified change or label will be ignored.</p> 
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>parallel</code>
<ul><b>Nested Object</b>
<li><code>enable</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>path</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>threads</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>minfiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>minbytes</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul><li><code>syncOnly</code></li>
<ul><li><code>revert</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>have</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>force</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modtime</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>quiet</code>
<div><div> 
 <b>Suppressing info messages</b> 
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>pin</code>
<div><div> 
 <b>Pinning a build at Perforce Label</b> 
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will sync only to the specified label. Any other specified change or label will be ignored.</p> 
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>parallel</code>
<ul><b>Nested Object</b>
<li><code>enable</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>path</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>threads</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>minfiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>minbytes</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul></ul></li>
<li><code>source</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>depotSource</code></li>
<ul><li><code>depot</code>
<div><div> 
 <p>List of depot paths</p> 
 <p>For example <code>//depot/A/...</code></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>graphSource</code></li>
<ul><li><code>graph</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>streamSource</code></li>
<ul><li><code>stream</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>templateSource</code></li>
<ul><li><code>template</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>stream</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>template</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>workspace</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>manualSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>Workspace name</b> 
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>spec</code>
<ul><b>Nested Object</b>
<li><code>allwrite</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>clobber</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>compress</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>locked</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modtime</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rmdir</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>streamName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>line</code>
<div><div> 
 <b>Line Endings</b> 
 <p>Set line-ending character(s) for client text files.</p> 
 <ul> 
  <li> <b>UNIX</b> <p>linefeed: UNIX style.</p> </li> 
  <li> <b>MAC</b> <p>carriage return: Macintosh style. (obsolete)</p> </li> 
  <li> <b>WIN</b> <p>carriage return-linefeed: Windows style.</p> </li> 
  <li> <b>SHARE</b> <p>hybrid: writes UNIX style but reads UNIX, Mac or Windows style.</p> </li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>view</code>
<div><div> 
 <b>View</b> 
 <p>Lines to map depot files into the client workspace.</p> 
 <p>Maps files in the depot to files in your client workspace. Defines the files that you want in your client workspace and specifies where you want them to reside. The default view maps all depot files onto the client. See 'p4 help views' for view syntax. A new view takes effect on the next 'p4 sync'.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeView</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>type</code>
<div><div> 
 <b>Type</b> 
 <p>Type of client: writeable/readonly/partitioned/graph</p> 
 <p>By default all clients are 'writeable', certain clients are short lived and perform long sync and build cycles. Over time these build clients can fragment the 'db.have' table which is used to track what files a client has synced. Setting a type of 'readonly' gives the client its own personal 'db.have' database table. A 'readonly' client cannot 'edit' or 'submit' files, however for build automation this is not usually a requirement and the performance tradeoff is worth considering if your build automation is causing issues with the 'db.have' table. This option requires that an administrator has first configured the 'client.readonly.dir' setting. If it is necessary to submit changes as part of your build, you may specify a 'partitioned' client: like a 'reaonly' client, this type also has a separate 'db.have' table under the 'client.readonly.dir' directory, but allows journalled 'edit' and 'submit' of files.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverID</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>backup</code>
<div><div> 
 <b>Backup</b> 
 <p>Client's participation in backup enable/disable. If not specified backup of a writable client defaults to enabled.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>specFileSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>An existing workspace</b> 
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>specPath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>staticSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>An existing workspace</b> 
 <p>Specify the name of an existing workspace in Perforce to be used as the Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>streamSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>streamName</code>
<div><div> 
 <b>Stream codeline</b> 
 <p>Specify the full Perforce depot path for the given stream. If connected to a Perforce server the auto-text fill should list possible streams.</p> 
 <i>For example: //stream-depot/main-stream</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code>
<div><div> 
 <b>Workspace name formatter</b> 
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p> 
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>templateSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>templateName</code>
<div><div> 
 <b>Templace workspace</b> 
 <p>Specify the name of an existing workspace in Perforce used to create or update a Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code>
<div><div> 
 <b>Workspace name formatter</b> 
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p> 
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul>


++++
=== +p4tag+: P4 Tag
++++
<ul><li><code>rawLabelName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>rawLabelDesc</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +p4unshelve+: P4 Unshelve
++++
<ul><li><code>credential</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>workspace</code>
<ul><b>Nested Choice of Objects</b>
<li><code>manualSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>Workspace name</b> 
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>spec</code>
<ul><b>Nested Object</b>
<li><code>allwrite</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>clobber</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>compress</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>locked</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modtime</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rmdir</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>streamName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>line</code>
<div><div> 
 <b>Line Endings</b> 
 <p>Set line-ending character(s) for client text files.</p> 
 <ul> 
  <li> <b>UNIX</b> <p>linefeed: UNIX style.</p> </li> 
  <li> <b>MAC</b> <p>carriage return: Macintosh style. (obsolete)</p> </li> 
  <li> <b>WIN</b> <p>carriage return-linefeed: Windows style.</p> </li> 
  <li> <b>SHARE</b> <p>hybrid: writes UNIX style but reads UNIX, Mac or Windows style.</p> </li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>view</code>
<div><div> 
 <b>View</b> 
 <p>Lines to map depot files into the client workspace.</p> 
 <p>Maps files in the depot to files in your client workspace. Defines the files that you want in your client workspace and specifies where you want them to reside. The default view maps all depot files onto the client. See 'p4 help views' for view syntax. A new view takes effect on the next 'p4 sync'.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changeView</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>type</code>
<div><div> 
 <b>Type</b> 
 <p>Type of client: writeable/readonly/partitioned/graph</p> 
 <p>By default all clients are 'writeable', certain clients are short lived and perform long sync and build cycles. Over time these build clients can fragment the 'db.have' table which is used to track what files a client has synced. Setting a type of 'readonly' gives the client its own personal 'db.have' database table. A 'readonly' client cannot 'edit' or 'submit' files, however for build automation this is not usually a requirement and the performance tradeoff is worth considering if your build automation is causing issues with the 'db.have' table. This option requires that an administrator has first configured the 'client.readonly.dir' setting. If it is necessary to submit changes as part of your build, you may specify a 'partitioned' client: like a 'reaonly' client, this type also has a separate 'db.have' table under the 'client.readonly.dir' directory, but allows journalled 'edit' and 'submit' of files.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverID</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>backup</code>
<div><div> 
 <b>Backup</b> 
 <p>Client's participation in backup enable/disable. If not specified backup of a writable client defaults to enabled.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>specFileSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>An existing workspace</b> 
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>specPath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>staticSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>name</code>
<div><div> 
 <b>An existing workspace</b> 
 <p>Specify the name of an existing workspace in Perforce to be used as the Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>streamSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>streamName</code>
<div><div> 
 <b>Stream codeline</b> 
 <p>Specify the full Perforce depot path for the given stream. If connected to a Perforce server the auto-text fill should list possible streams.</p> 
 <i>For example: //stream-depot/main-stream</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code>
<div><div> 
 <b>Workspace name formatter</b> 
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p> 
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>templateSpec</code></li>
<ul><li><code>charset</code>
<div><div> 
 <b>P4CHARSET</b> 
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pinHost</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>templateName</code>
<div><div> 
 <b>Templace workspace</b> 
 <p>Specify the name of an existing workspace in Perforce used to create or update a Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>format</code>
<div><div> 
 <b>Workspace name formatter</b> 
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p> 
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>syncID</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>shelf</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>resolve</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tidy</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>ignoreEmpty</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +cleanup+: Perforce: Cleanup
++++
<ul><li><code>deleteClient</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
