---
layout: pipelinesteps
title: "性能签名：Dynatrace AppMon"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== 性能签名：Dynatrace AppMon

plugin:performance-signature-dynatrace[在插件索引中查看此插件]

=== +createDeploymentEvent+: 创建Dynatrace部署事件
++++
<ul><li><code>dynatraceProfile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +activateDTConfiguration+: 激活Dynatrace配置文件配置
++++
<ul><li><code>dynatraceProfile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>configuration</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +createMemoryDump+: 创建内存转储
++++
<ul><li><code>dynatraceProfile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>agent</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>host</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>autoPostProcess</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>capturePrimitives</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>captureStrings</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>dogc</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>lockSession</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>type</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +perfSigReports+: 发布性能签名报告
++++
<ul><li><code>dynatraceProfile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>configurationTestCases</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>$class: 'GenericTestCase'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>singleDashboards</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>dashboard</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>comparisonDashboards</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>dashboard</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>xmlDashboard</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>clientDashboard</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'UnitTestCase'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>singleDashboards</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>dashboard</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>comparisonDashboards</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>dashboard</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>xmlDashboard</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>clientDashboard</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>deleteSessions</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>exportSessions</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>nonFunctionalFailure</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>removeConfidentialStrings</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +startSession+: 开始Dynatrace会话录制停止Dynatrace会话记录
++++
<ul><li><code>dynatraceProfile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>testCase</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>lockSession</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>recordingOption</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +stopSession+: 停止Dynatrace会话记录
++++
<ul><li><code>dynatraceProfile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +createThreadDump+: 创建线程转储
++++
<ul><li><code>dynatraceProfile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>agent</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>host</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>lockSession</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
