---
layout: pipelinesteps
title: "Performance Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== 性能插件

plugin:performance[在插件索引中查看此插件]

=== +perfReport+: 发布性能测试结果报告
++++
<ul><li><code>sourceDataFiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>compareBuildPrevious</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>configType</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>constraints</code> (optional)
<ul><b>Array/List</b><br/>
<code>hudson.plugins.performance.constraints.AbstractConstraint</code>
</ul></li>
<li><code>errorFailedThreshold</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>errorUnstableResponseTimeThreshold</code> (optional)
<div><div>
  The thresholds settings should be delimited by a new line character "\n". 
</div> 
<div>
  The actual threshold number should be seperated from the test file name by a colon ":" 
</div> 
<pre>
Example:
-------------------------------------
JMeterResultsOrders.jtl:2000
JMeterResultsGetCustomer.jtl:500
JMeterResultsCreateCustomer.jtl:700
-------------------------------------
</pre></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>errorUnstableThreshold</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>excludeResponseTime</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failBuildIfNoResultFile</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>graphType</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ignoreFailedBuilds</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>ignoreUnstableBuilds</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>junitOutput</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>modeEvaluation</code> (optional)
<div><div> 
 <p> Standard Mode activates upper box and ignores lower box. </p> 
 <p> Expert Mode activates lower box and ignores upper box. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modeOfThreshold</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modePerformancePerTestCase</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>modeThroughput</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>nthBuildNumber</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>parsers</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>$class: 'IagoParser'</code></li>
<ul><li><code>glob</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>percentiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'JMeterCsvParser'</code></li>
<ul><li><code>glob</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>percentiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'JMeterParser'</code></li>
<ul><li><code>glob</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>percentiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'JUnitParser'</code></li>
<ul><li><code>glob</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>percentiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'JmeterSummarizerParser'</code></li>
<ul><li><code>glob</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>percentiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'LoadRunnerParser'</code></li>
<ul><li><code>glob</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>percentiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'TaurusParser'</code></li>
<ul><li><code>glob</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>percentiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'WrkSummarizerParser'</code></li>
<ul><li><code>glob</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>percentiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>percentiles</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>persistConstraintLog</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>relativeFailedThresholdNegative</code> (optional)
<ul><li><b>Type:</b> <code>double</code></li></ul></li>
<li><code>relativeFailedThresholdPositive</code> (optional)
<ul><li><b>Type:</b> <code>double</code></li></ul></li>
<li><code>relativeUnstableThresholdNegative</code> (optional)
<ul><li><b>Type:</b> <code>double</code></li></ul></li>
<li><code>relativeUnstableThresholdPositive</code> (optional)
<ul><li><b>Type:</b> <code>double</code></li></ul></li>
</ul>


++++
=== +bzt+: 运行性能测试
++++
<div><div>
  Execute 
 <a href="http://gettaurus.org/?utm_source=jenkins&amp;utm_medium=link&amp;utm_campaign=build_step_help" rel="nofollow">Taurus</a> with configuration files and options. You can simply specify JMX file to run, or give list of Taurus config files and options to execute. 
</div></div>
<ul><li><code>params</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>alwaysUseVirtualenv</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>bztVersion</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>generatePerformanceTrend</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>printDebugOutput</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>useBztExitCode</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>useSystemSitePackages</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>workingDirectory</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>workspace</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
