---
layout: pipelinesteps
title: "Pipeline: Input Step"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Pipeline: Input Step

plugin:pipeline-input-step[View this plugin on the Plugins Index]

=== +input+: Wait for interactive input
++++
<div><div> 
 <p> This step pauses Pipeline execution and allows the user to interact and control the flow of the build. Only a basic "process" or "abort" option is provided in the stage view. </p> 
 <p> You can optionally request information back, hence the name of the step. The parameter entry screen can be accessed via a link at the bottom of the build console log or via link in the sidebar for a build. </p> 
</div></div>
<ul><li><code>message</code>
<div><p> This parameter gives a prompt which will be shown to a human: </p>
<pre>    Ready to go?
    Proceed or Abort
    </pre> 
<p></p> 
<p> If you click "Proceed" the build will proceed to the next step, if you click "Abort" the build will be aborted. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>id</code> (optional)
<div><p> Every <code>input</code> step has an unique ID. It is used in the generated URL to proceed or abort. </p> 
<p> A specific ID could be used, for example, to mechanically respond to the input from some external process/tool. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ok</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>parameters</code> (optional)
<div><p> Request that the submitter specify one or more parameter values when approving. If just one parameter is listed, its value will become the value of the <code>input</code> step. If multiple parameters are listed, the return value will be a map keyed by the parameter names. If parameters are not requested, the step returns nothing if approved. </p> 
<p> On the parameter entry screen you are able to enter values for parameters that are defined in this field. </p></div>

<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>$class: 'AppDetectorParamaterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>appName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'AutoCompleteStringParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>displayExpression</code>
<div><div> 
 <p>Display is the text the user will see when inserting tokens. Use this field to control how the text will be shown to the user</p> 
 <ul> 
  <li>When this field is empty, the value will be whole value</li> 
  <li>Specify the JSON field name</li> 
  <li>Write a javascript expression between {}'s and use the fields as if they were variables</li> 
 </ul> 
 <p>If the data provider returns a simple list of strings, each value can be referred by the variable 'value' in javascript expressions</p> 
 <p>Some examples. Let's assume the data provider resulted in the following json:</p> 
 <pre>
[
	{"name": "Eddard Stark","id":"estark", "house":"Stark"},
	{"name": "John Snow","id":"jsnow", "house":"Stark"},
	{"name": "Tyrion Lannister","id":"tlannister", "house":"Lannister"},
	...
]
</pre> Some valid examples: 
 <ul> 
  <li>name</li> 
  <li>house</li> 
  <li>{name}</li> 
  <li>{name+" ("+house+")"}</li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>valueExpression</code>
<div><div> 
 <p>Value is the text the job will receive in the parameter. Use this field to control how the text will provided to the job</p> 
 <ul> 
  <li>When this field is empty, the value will be whole value (the whole json)</li> 
  <li>Specify the JSON field name to choose a specific field</li> 
  <li>Write a javascript expression between {}'s and use the fields as if they were variables</li> 
 </ul> 
 <p>If the data provider returns a simple list of strings, each value can be referred by the variable 'value' in javascript expressions</p> 
 <p>Some examples. Let's assume the data provider resulted in the following json:</p> 
 <pre>
[
	{"name": "Eddard Stark","id":"estark", "house":"Stark"},
	{"name": "John Snow","id":"jsnow", "house":"Stark"},
	{"name": "Tyrion Lannister","id":"tlannister", "house":"Lannister"},
	...
]
</pre> Some valid examples: 
 <ul> 
  <li>name</li> 
  <li>house</li> 
  <li>{name}</li> 
  <li>{name+" ("+house+")"}</li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>allowUnrecognizedTokens</code>
<div><div>
  If enabled, will allow the user to input tokens that are not in the data set. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>dataProvider</code>
<div><div>
  Choose a data provider to specify how to fetch the content to auto complete. 
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'GroovyDataProvider'</code></li>
<ul><li><code>script</code>
<div><div>
  A groovy script that results in an array or collection of objects. It will work as long the elements in the result can be converted to JSON. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sandbox</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>classpath</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>path</code>
<div><div>
  A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul><li><code>$class: 'InlineJsonDataProvider'</code></li>
<ul><li><code>autoCompleteData</code>
<div><div>
  A json array of objects. For example: 
 <pre>
[
	{"name": "Eddard Stark","id":"estark", "house":"Stark"},
	{"name": "John Snow","id":"jsnow", "house":"Stark"},
	{"name": "Tyrion Lannister","id":"tlannister", "house":"Lannister"},
	...
]
</pre> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'RemoteDataProvider'</code></li>
<ul><li><code>autoCompleteUrl</code>
<div><div>
  The remote end point. The endpoint response should be a json array of objects 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  The credentials to access the endpoint, if needed. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'SimpleTextProvider'</code></li>
<ul><li><code>autoCompleteData</code>
<div><div>
  A list of values, one per line 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul><li><code>booleanParam</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>choice</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>choices</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'ClearCaseUcmBaselineParameterDefinition'</code></li>
<div><div>
  When used, this parameter will display a field at build-time so that the user is able to select the ClearCase UCM baseline from which to download the content to be worked with by this project.
 <br> To use this parameter, you MUST also set the SCM to be the ClearCase UCM baseline one, otherwise the build will fail.
 <br> The name of the selected ClearCase UCM baseline is available through the 
 <code>CLEARCASE_BASELINE</code> environment variable. 
</div></div>
<ul><li><code>pvob</code>
<div><div> 
 <b>Mandatory</b> — Name of the ClearCase UCM PVOB. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>component</code>
<div><div> 
 <b>Mandatory</b> — Name of the ClearCase UCM component which owns the ClearCase UCM baseline to download at build-time.
 <br> At build-time, the user will be able to select one of the ClearCase UCM baselines defined for this component. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>promotionLevel</code>
<div><div> 
 <b>Optional</b> — Promotion level of the ClearCase UCM baseline to be downloaded at build-time.
 <br> If no promotion level is set (blank field), then the user will be presented with all the ClearCase UCM baselines belonging to the ClearCase UCM component defined above. If a promotion level is set, then, at build-time, the user will be presented with only the ClearCase UCM baselines which have been promoted to the specified level. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>stream</code>
<div><div> 
 <b>Optional</b> — Stream of the ClearCase UCM baseline to be downloaded at build-time.
 <br> If no stream is set (blank field), then the user will be presented with all the ClearCase UCM baselines belonging to the ClearCase UCM component defined above. If a stream is set, then, at build-time, the user will be presented with only the ClearCase UCM baselines which have been defined on this stream. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>restrictions</code>
<div><div> 
 <b>Optional</b> — List of folders (one folder per line) to be actually downloaded from ClearCase.
 <br> For this field to be taken into account, you need to check the 
 <b>Use snapshot view</b> field.
 <br> If no restrictions are defined, then all the data for the selected ClearCase UCM baseline will be downloaded. If restrictions are defined, then only these folders will be downloaded.
 <br> For each folder to download, don't forget to prefix them with the VOB name and the component root dir (usually identical to the component name) this folder belongs to. For example, if you want to download the folder 
 <code>05_impl/0_src</code> which is in the 
 <code>fa4_web</code> component of the 
 <code>fa4</code> VOB, set the value to 
 <code>/fa/fa4_web/05_impl/0_src</code>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>viewName</code>
<div><div> 
 <b>Mandatory</b> — Name of the ClearCase UCM view which will be created to download the content of the baseline selected at build-time.
 <br> You can use several variables within the view name, such as:
 <ul> 
  <li><code>CLEARCASE_BASELINE</code>, which is replaced with the name of the ClearCase UCM baseline which is selected at build-time;</li> 
  <li><code>JOB_NAME</code>, which is replaced with the name of the job;</li> 
  <li><code>USER_NAME</code>, which is replaced with the name of the user running Hudson.</li> 
 </ul> The ClearCase UCM view is available as two environment variables:
 <ul> 
  <li>The name of the ClearCase UCM view is available as <code>CLEARCASE_VIEWNAME</code>;</li> 
  <li>The absolute path to the ClearCase UCM view is available as <code>CLEARCASE_VIEWPATH</code>.</li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>mkviewOptionalParam</code>
<div><div> 
 <b>Optional</b> — If your build requires additional 
 <code>cleartool </code> arguments when creating a view using 
 <code>mkview</code>, specify them here.
 <br> Note that all other arguments (that is, 
 <code>-snapshot</code> —if applicable— and 
 <code>-tag ${CLEARCASE_VIEWNAME}</code> will be appended before these additional arguments.
 <br> For documentation on the 
 <code>mkview</code> command, take a look at the 
 <a href="http://publib.boulder.ibm.com/infocenter/cchelp/v7r0m0/index.jsp?topic=/com.ibm.rational.clearcase.cc_ref.doc/topics/ct_mkview.htm" rel="nofollow"> ClearCase 7.0 Information Center</a>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>snapshotView</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>useUpdate</code>
<div><div>
  Check this option to avoid recreating the Clearcase UCM view each time a build is triggered and the baseline has changed. Instead, the view config spec will be updated so that only files that have changed are loaded. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>forceRmview</code>
<div><div>
  Check this option to force the recreation of the ClearCase UCM view each time a build is triggered. If this option is not set and if the baseline which is selected when a new build is triggered is the same as for the previous build, then the ClearCase UCM view won't be recreated.
 <br> This setting can be overriden at run-time. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>excludeElementCheckedout</code>
<div><div>
  Check this option to exclude the 
 <code>element * CHECKEDOUT</code> rule from the config spec.
 <br> Note that the 
 <code>element * CHECKEDOUT</code> rule is mandatory when using snapshot views. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>moreRecentThan</code>
<div><div> 
 <b>Optional</b> — Use this field to display, when triggering a new build, only the ClearCase UCM baselines which are more recent than a given number of years, or months, or weeks, or days.
 <br> Examples: 
 <code>1 year</code>, 
 <code>6 months</code>, 
 <code>1 week</code>, 
 <code>10 days</code> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>uuid</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>credentials</code></li>
<div><div>
  Defines a credentials parameter, which you can use during a build. 
 <p> <i>For security reasons</i>, the credential is <i>NOT</i> directly exposed, the UUID of the credential is exposed. </p> However, the selected credential is available through variable substitution in some other parts of the configuration. The string value will be the UUID of the credential. A supporting plugin can thus use the UUID to retrieve the selected credential and expose it to the build in an appropriate way. 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<div><div>
  The default credentials to use. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialType</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>required</code>
<div><div>
  When this option is selected, the credentials selection drop down will not provide the empty selection as one of the options. This will not prevent a build without a value if there are no credentials available, for example if the job does not have access to any credentials of the correct type or there is no default value and the user starting the build either does not have any credentials of the correct type in their personal credentials store or they do not have permissions on the job to use credentials from their personal store. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'CvsTagsParamDefinition'</code></li>
<ul><li><code>name</code>
<div><div>
  The name this parameter will be referred to as during any builds. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>cvsRoot</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>passwordRequired</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>moduleName</code>
<div><div>
  The name of the item to retrieve a list of symbolic names for. This could be a module root (e.g. moduleName), subdirectory (e.g. moduleName/sub/directory/) or individual file (e.g. moduleName/sub/directory/file.name). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DateParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dateFormat</code>
<div>This is the Java date format. Like 'yyyyMMdd'.</div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<div>You can create a 'default value' in one of two forms. 
<p>1. Java LocalDate or LocalDateTime code style</p> 
<ul> 
 <li>LocalDate.now();</li> 
 <li>LocalDate.now().plusDays(1);</li> 
 <li>LocalDate.now().plusDays(1).plusYears(2);</li> 
 <li>LocalDate.now().minusDays(5).minusMonths(3).minusYears(2);</li> 
 <li>LocalDateTime.now()</li> 
 <li>LocalDateTime.now().minusHours(5).plusMinutes(10).minusSeconds(20);</li> 
 <li>LocalDateTime.now().minusDays(5).plusYears(5).plusSeconds(50);</li> 
</ul> 
<p>2. LocalDate String (This case should match the format of 'dateFormat')</p> 
<ul> 
 <li>20170501</li> 
 <li>2017-05-01</li> 
</ul></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DeployMetaDataParameterDefinition'</code></li>
<div>A deployment meta data parameter allows you to specify environment and build version to deploy that will be used in "Collect deploy metadata" plugin.</div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>environmentKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildVersion</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>applicationName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DropdownAutocompleteParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>displayExpression</code>
<div><div> 
 <p>Value is the text the job will receive in the parameter. Use this field to control how the text will provided to the job</p> 
 <ul> 
  <li>When this field is empty, the value will be whole value (the whole json)</li> 
  <li>Specify the JSON field name to choose a specific field</li> 
  <li>Write a javascript expression between {}'s and use the fields as if they were variables</li> 
 </ul> 
 <p>If the data provider returns a simple list of strings, each value can be referred by the variable 'value' in javascript expressions</p> 
 <p>Some examples. Let's assume the data provider resulted in the following json:</p> 
 <pre>
[
	{"name": "Eddard Stark","id":"estark", "house":"Stark"},
	{"name": "John Snow","id":"jsnow", "house":"Stark"},
	{"name": "Tyrion Lannister","id":"tlannister", "house":"Lannister"},
	...
]
</pre> Some valid examples: 
 <ul> 
  <li>name</li> 
  <li>house</li> 
  <li>{name}</li> 
  <li>{name+" ("+house+")"}</li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>valueExpression</code>
<div><div> 
 <p>For data providers that returns JSON arrays, there are display and values. Display is the text the user will see when inserting tokens. Value is the value that will be given to the build.</p> 
 <p>This field allows you specify one the the json's field names, leave it empty to use the whole json as value or write a javascript expression using the fields between {}'s.</p> 
 <p>If the dataset returns a simple list of strings, the value of this field is ignored.</p> 
 <p>Some examples. Let's assume the dataset resulted in the following json:</p> 
 <pre>
[
	{"name": "Eddard Stark","id":"estark", "house":"Stark"},
	{"name": "John Snow","id":"jsnow", "house":"Stark"},
	{"name": "Tyrion Lannister","id":"tlannister", "house":"Lannister"},
	...
]
</pre> Some valid examples: 
 <ul> 
  <li>name</li> 
  <li>house</li> 
  <li>{name}</li> 
  <li>{name+" ("+house+")"}</li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dataProvider</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'GroovyDataProvider'</code></li>
<ul><li><code>script</code>
<div><div>
  A groovy script that results in an array or collection of objects. It will work as long the elements in the result can be converted to JSON. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sandbox</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>classpath</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>path</code>
<div><div>
  A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul><li><code>$class: 'InlineJsonDataProvider'</code></li>
<ul><li><code>autoCompleteData</code>
<div><div>
  A json array of objects. For example: 
 <pre>
[
	{"name": "Eddard Stark","id":"estark", "house":"Stark"},
	{"name": "John Snow","id":"jsnow", "house":"Stark"},
	{"name": "Tyrion Lannister","id":"tlannister", "house":"Lannister"},
	...
]
</pre> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'RemoteDataProvider'</code></li>
<ul><li><code>autoCompleteUrl</code>
<div><div>
  The remote end point. The endpoint response should be a json array of objects 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  The credentials to access the endpoint, if needed. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'SimpleTextProvider'</code></li>
<ul><li><code>autoCompleteData</code>
<div><div>
  A list of values, one per line 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul><li><code>$class: 'ExtensibleChoiceParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>choiceListProvider</code>
<div><div>
  Select a provider that gives choices when build. 
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'ArtifactoryChoiceListProvider'</code></li>
<ul><li><code>artifactId</code> (optional)
<div><div>
  Mandatory: The artifactId to search for in the repository. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classifier</code> (optional)
<div><div>
  The Maven Artifact classifier, i.E. "sources". By default leave empty. You can specifiy a list of valid or invalid classifier separated by Comma, i.E. "sources,!jar" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<div><div>
  If your repository service requires user authentication, you'll have to configure the username and password here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>groupId</code> (optional)
<div><div>
  Optional: The GroupId to search the artifact, i.E. "org.jenkins-ci.plugins" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>packaging</code> (optional)
<div><div>
 Optional: Filters the matching packaging type from the results, i.E. "jar" or "zip". Use a * to return all the values. If parameter is not set, only the parent folder is returned.
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repositoryId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reverseOrder</code> (optional)
<div><div>
  If the list should be returned in reverse order. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>url</code> (optional)
<div><div>
  Enter the URL of the Artifactory server, i.E. https://repo.jenkins-ci.org/ 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'FilenameChoiceListProvider'</code></li>
<ul><li><code>baseDirPath</code>
<div><div>
  Specify the path to the directory to scan for files. This path will not be contained in choice list strings. If specified as a relative path, it is considered as relative to ${JENKINS_HOME}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>includePattern</code>
<div><div>
  Specify the pattern of files to list. Multiple patterns can be specified with separating with comma(,). Wildcard is available like '**/*.xml'. See 
 <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">includes attribute of Ant FileSet Type</a> for the exact format. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludePattern</code>
<div><div>
  Specify patterns not to list (even specified in File Name Pattern field). See the help of "File Name Pattern" for the formats of patterns. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>scanType</code>
<div><div>
  Specify what type of files to list. 
</div></div>

<ul><li><b>Values:</b> <code>File</code>, <code>Directory</code>, <code>FileAndDirectory</code></li></ul></li>
<li><code>reverseOrder</code>
<div><div>
  check to list files in reverse alphabetical order. If not checked, files are listed in alphabetical order. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>emptyChoiceType</code>
<div><div>
  Adds an empty choice to the specified place. 
</div></div>

<ul><li><b>Values:</b> <code>None</code>, <code>AtTop</code>, <code>AtEnd</code></li></ul></li>
</ul><li><code>$class: 'GlobalTextareaChoiceListProvider'</code></li>
<ul><li><code>name</code>
<div><div>
  Select a name of the choice set, that you have specified in the system configuration. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultChoice</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>addEditedValue</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>whenToAdd</code>
<ul><li><b>Values:</b> <code>Triggered</code>, <code>Completed</code>, <code>CompletedStable</code>, <code>CompletedUnstable</code></li></ul></li>
</ul><li><code>$class: 'MavenCentralChoiceListProvider'</code></li>
<ul><li><code>artifactId</code> (optional)
<div><div>
  Mandatory: The artifactId to search for in the repository. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classifier</code> (optional)
<div><div>
  The Maven Artifact classifier, i.E. "sources". By default leave empty. You can specifiy a list of valid or invalid classifier separated by Comma, i.E. "sources,!jar" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>groupId</code> (optional)
<div><div>
  Optional: The GroupId to search the artifact, i.E. "org.jenkins-ci.plugins" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>packaging</code> (optional)
<div><div>
 Optional: Filters the matching packaging type from the results, i.E. "jar" or "zip". Use a * to return all the values. If parameter is not set, only the parent folder is returned.
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repositoryId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reverseOrder</code> (optional)
<div><div>
  If the list should be returned in reverse order. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'NexusChoiceListProvider'</code></li>
<ul><li><code>artifactId</code> (optional)
<div><div>
  Mandatory/Optional: The artifactId to search for in the repository. Either provide at least the artifactId or the groupId. ArtifactId can contains * 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classifier</code> (optional)
<div><div>
  The Maven Artifact classifier, i.E. "sources". By default leave empty. You can specifiy a list of valid or invalid classifier separated by Comma, i.E. "sources,!jar" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code> (optional)
<div><div>
  If your repository service requires user authentication, you'll have to configure the username and password here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>groupId</code> (optional)
<div><div>
  Optional/Mandatory: The GroupId to search the artifact, i.E. "org.jenkins-ci.plugins". If ArtifactId is not defined you have to specify at least the GroupId. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>packaging</code> (optional)
<div><div>
 Optional: Filters the matching packaging type from the results, i.E. "jar" or "zip". Use a * to return all the values. If parameter is not set, only the parent folder is returned.
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repositoryId</code> (optional)
<div><div>
  Optional: The repositoryId which should be searched, i.E. "snapshots" or "releases" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reverseOrder</code> (optional)
<div><div>
  If the list should be returned in reverse order. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>url</code> (optional)
<div><div>
  Enter the URL of the Nexus server, i.E. http://nexus.mycompany.com/nexus/ 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'SystemGroovyChoiceListProvider'</code></li>
<ul><li><code>groovyScript</code>
<ul><b>Nested Object</b>
<li><code>script</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sandbox</code>
<div><div>
  If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>classpath</code>
<div><div>
  Additional classpath entries accessible from the script. 
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>path</code>
<div><div>
  A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul></li>
<li><code>defaultChoice</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>usePredefinedVariables</code>
<div><div> 
 <p>Enable following pre-defined variables:</p> 
 <dl> 
  <dt>
   project
  </dt> 
  <dd>
   The project. An instance of 
   <a href="http://javadoc.jenkins-ci.org/hudson/model/Job.html" rel="nofollow">Job</a>.
  </dd> 
 </dl> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'TextareaChoiceListProvider'</code></li>
<ul><li><code>choiceListText</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultChoice</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>addEditedValue</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>whenToAdd</code>
<ul><li><b>Values:</b> <code>Triggered</code>, <code>Completed</code>, <code>CompletedStable</code>, <code>CompletedUnstable</code></li></ul></li>
</ul></ul></li>
<li><code>editable</code>
<div><div>
  With checked, you can specify a parameter other than those in the choice. Of course, you can also select a parameter from the choice. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>file</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'FileSystemListParameterDefinition'</code></li>
<div><div>
  The 
 <strong>filesystem-list-parameter-plugin</strong> lists file system object names of a directory. One of the object names can be selected as build parameter. In addition the objects can be filtered: 
 <code>ALL, DIRECTORY, FILE, SYMLINK</code>. The order of the list can be reversed. 
</div></div>
<ul><li><code>name</code>
<div><div>
  The name of the parameter. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<div><div>
  The type of the file system objects that will be filtered from path. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>path</code>
<div><div>
  The path of the directory containing the file system objects. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>selectedType</code>
<div><div>
  Objects in "Path" can be filtered: 
 <code>ALL, DIRECTORY, FILE, SYMLINK</code>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>regexIncludePattern</code>
<div><div>
  The regular expression matching the file system objects to be excluded in parameter selection. (Will be ignored if empty) See Standard 
 <a href="http://download.oracle.com/javase/1.4.2/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>regexExcludePattern</code>
<div><div>
  The regular expression matching the file system objects to be included in parameter selection. (Will be ignored if empty) See Standard 
 <a href="http://download.oracle.com/javase/1.4.2/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a>. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sortByLastModified</code>
<div><div>
  If true, the list of the parameter values will be sorted by last modified file attribute. Default order is sort by parameter value. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>sortReverseOrder</code>
<div><div>
  If true, the list of the parameter values will be sorted in reverse order. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'GeneratorChoiceParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>choices</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'GeneratorKeyValueParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'GitParameterDefinition'</code></li>
<div><div> 
 <p>When used, this parameter will present at build-time a choice to select a Git tag (or revision number) which set a parameter for parametrized build.</p> 
 <p>Be aware that git does not allow us get additional information (like author/commmit date) from a remote URL this plugin will silently clone the project when your workspace is empty. This may take a long time when we have a slow connection and/or the checkout is big.</p> 
 <p>Often the parameter defined in the "Name" field is used to specify the branch of the git checkout.</p> 
</div></div>
<ul><li><code>name</code>
<div><div>
  The name of the parameter. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>type</code>
<div><div>
  The type of the list of parameters: 
 <ul> 
  <li>Tag - list of all commit tags in repository - returns Tag Name</li> 
  <li>Branch - list of all branch in repository - returns Branch Name</li> 
  <li>Revision - list of all revision sha1 in repository followed by its author and date - returns Tag SHA1</li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<div><div>
  This value is returned when list is empty. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<div><div>
  A description that will be shown to the user later. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>branch</code>
<div><div>
  Name of branch to look in. Used only if listing revisions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>branchFilter</code>
<div><div>
  Regex used to filter displayed branches. If blank, the filter will default to ".*".
 <br> Remote branches will be listed with the remote name first. E.g., "origin/master" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tagFilter</code>
<div><div>
  This parameter is used to get tag from git.
 <br> If is blank, parameter is set to "*".
 <br> Properly is executed command: git tag -l "*" or git tag -l "$tagFilter". 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sortMode</code>
<div><div>
  Select how to sort the downloaded parameters. Only applies to a branch or a tag. 
 <ul> 
  <li>none</li> 
  <li>ascending smart</li> 
  <li>descending smart</li> 
  <li>ascending</li> 
  <li>descending</li> 
 </ul> When smart sorting is chosen, the compare treats a sequence of digits as a single character. 
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>ASCENDING_SMART</code>, <code>DESCENDING_SMART</code>, <code>ASCENDING</code>, <code>DESCENDING</code></li></ul></li>
<li><code>selectedValue</code>
<div><div>
  Which value is selected, after loaded parameters.
 <br> If you choose 'default', but default value is not present on the list, nothing is selected. 
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>TOP</code>, <code>DEFAULT</code></li></ul></li>
<li><code>useRepository</code>
<div><div>
  If in the task is defined multiple repositories parameter specifies which the repository is taken into account.
 <br> If the parameter is not defined, is taken first defined repository. 
 <br> The parameter is a regular expression which is compared with a URL repository. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>quickFilterEnabled</code>
<div><div>
  When this option is enabled will show a text field.
 <br> Parameter is filtered on the fly. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'GithubBranchParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>githubRepoUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'GlobalVariableStringParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'InheritableStringParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>inheritanceMode</code>
<div><div>
  This field selects, how this parameter is altered, when a child project overrides its value. For example, you may provide a variable "A" here with the value "Foo", while a child also defines "A", but with the value "Bar". 
 <p> The mode that you select here will influence the final value of the parameter, when you build the child: </p>
 <ul> 
  <li>If you select "Overwritable", the build will just get the value "Bar"</li> 
  <li>If you select "Extensible", the build will get the value "FooBar" (or "Foo Bar", depending on the "Whitespace Mode" below)</li> 
  <li>If you select "Fixed", then the build will fail, since this project prohibited changing the value.</li> 
 </ul> Do note, that this field only has an effect on the 
 <b>child</b> parameter — not the other way around. In other words, this mode decides what will happen in the future, not what happens "now" to the current or earlier overrides. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>mustHaveDefaultValue</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>mustBeAssigned</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>whitespaceMode</code>
<div><div>
  This field allows you to select, how whitespaces at the start/end of the parameter should be handled, when a build is started: 
 <ol> 
  <li>Trim all leading/trailing whitespace from the entered value.</li> 
  <li>Keep the whitespace intact, exactly as the user entered it.</li> 
  <li>Keep the whitespace, but make sure that at least a single space is added to the front of the value, in case it <b>extends</b> a parameter with the same name from a parent. </li> 
 </ol> Select the first option, if you know the parameter should not have leading or trailing spaces.
 <br> Select the third option, if you are constructing a parameter that is used in flag- or command-construction. For example Compiler Flags.
 <br> Otherwise, or if in doubt, just select the second option. 
 <p> Do note that, if trimming is selected, this has an effect on both the default value used for automatically started builds, as well as user-initiated builds where the user had a chance to alter the parameter value. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>isHidden</code>
<div><div>
  If this is checked, the parameter will be hidden behind an "advanced" button on the screen for starting a build. For sanity's sake, you should set this for all mandatory variables that are rarely changed. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'InheritableStringParameterReferenceDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'JavaParameterDefinition'</code></li>
<div><div>
  This parameter lets the user specify JDK to be used at the star of each build. 
</div></div>
<ul><li><code>name</code>
<div><div>
  The name to be displayed on the build parameters page. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<div><div>
  The description to be shown on the build parameters page. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultJDK</code>
<div><div>
  The JDK that will be used if the user does not specify one. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>allowedJDKs</code>
<div><div>
  The JDKs that can be chosen from on the build parameters page. 
</div></div>

<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'JiraIssueParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>jiraIssueFilter</code>
<div><div>
  Specify the JQL search on JIRA instance. For a build, Jenkins will run this query, populate a drop-down list box, then ask the user to select one. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'JiraVersionParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>jiraProjectKey</code>
<div><div> 
 <p>Specify the project key. A project key is the all capitals part before the issue number in JIRA.</p> 
 <p>(<strong>EXAMPLE</strong>-100)</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>jiraReleasePattern</code>
<div><div> 
 <p>Specify a regular expression which release names have to match to be listed. Leave this blank to match all issues.</p> 
 <p>Example:</p> 
 <strong>v[0-9]+([.][0-9]+)+</strong> will match v1.0.1, v123, v12.0.1 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>jiraShowReleased</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>jiraShowArchived</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'LabelParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>allNodesMatchingLabel</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>nodeEligibility</code>
<div><div>
  Defines how selected offline nodes should be handled. 
 <ul> 
  <li><b>All Nodes</b> - trigger the job on all selected nodes, regardless of there online/offline state</li> 
  <li><b>Ignore Offline Nodes</b> - trigger the job only on nodes being online and having an executor</li> 
  <li><b>Ignore Temp Offline Nodes</b> - trigger the job on all selected nodes except on the ones currently manually marked as offline</li> 
 </ul> 
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AllNodeEligibility'</code></li>
<ul></ul><li><code>$class: 'IgnoreOfflineNodeEligibility'</code></li>
<ul></ul><li><code>$class: 'IgnoreTempOfflineNodeEligibility'</code></li>
<ul></ul></ul></li>
<li><code>triggerIfResult</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'ListSubversionTagsParameterDefinition'</code></li>
<div><div>
  When used, this parameter will display a field at build-time so that the user is able to select a Subversion tag from which to create the working copy for this project. 
 <p> Once the two fields <strong>Name</strong> and <strong>Repository URL</strong> are set, you must </p>
 <ol> 
  <li>ensure the job uses <strong>Subversion</strong> and </li>
  <li>set the <strong>Repository URL</strong> field of <strong>Subversion</strong> by concatenating the two fields of this parameter. </li>
 </ol> For instance, if 
 <strong> Name</strong> is set to 
 <code>SVN_TAG</code> and 
 <strong>Repository URL</strong> is set to 
 <code>https://svn.jenkins-ci.org/tags</code>, then 
 <strong>Subversion</strong>'s 
 <strong>Repository URL</strong> must be set to 
 <code>https://svn.jenkins-ci.org/tags/$SVN_TAG</code>. 
 <p> Notice that you can set the <strong>Repository URL</strong> field to a Subversion repository root rather than just pointing to a <code>tags</code> dir (ie, you can set it to <code>https://svn.jenkins-ci.org</code> rather than <code>https://svn.jenkins-ci.org/tags</code>). In that case, if this repository root contains the <code>trunk</code>, <code>branches</code> and <code>tags</code> folders, then the dropdown will allow the user to pick the trunk, or a branch, or a tag. </p>
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tagsDir</code>
<div><div>
  Specify the Subversion repository URL which contains the tags to be listed when triggering a new build. 
 <p> You can also specify the root of a Subversion repository: If this root contains the <code>trunk</code>, <code>branches</code> and <code>tags</code> folders, then the dropdown will display <code>trunk</code>, all the branches and all the tags. If the root does not contain these three folders, then all its subfolders are listed in the dropdown. </p>
 <p> When you enter the URL, Jenkins automatically checks if it can connect to it. If access requires authentication, you'll be prompted for the necessary credential. If you already have a working credential but would like to change it for some other reasons, click <a rel="nofollow"> this link</a> and specify a different credential. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tagsFilter</code>
<div><div>
  Specify a 
 <a href="http://download.oracle.com/javase/1.5.0/docs/api/java/util/regex/Pattern.html" rel="nofollow"> regular expression</a> which will be used to filter the tags which are actually displayed when triggering a new build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<div><div>
  For features such as SVN polling a default value is required. If job will only be started manually, this field is not necessary. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>maxTags</code>
<div><div>
  The maximum number of tags to display in the dropdown. Any non-number value will default to all. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reverseByDate</code>
<div><div>
  Check this option so that tags are sorted from the newest to the oldest. 
 <p> If this option is checked, the <b>Sort Z to A</b> one won't be taken into account. </p>
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>reverseByName</code>
<div><div>
  Check this option so that tags are displayed in reverse order (sorted Z to A). 
 <p> Notice that if <b>Sort newest first</b> is checked, this option won't be taken into account. </p>
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'MatrixCombinationsParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultCombinationFilter</code>
<div><div> 
 <p> A Groovy expression to specify which combinations are checked by default. They are also combinations which is built in a scheduled build. If not specified, the combination filter of this multi-configuration project is used. Also see <a rel="nofollow">help of the combination filter</a>. </p> 
 <p> Note that you cannot enable combinations which disabled by the combination filter of the project. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>shortcutList</code>
<div><div>
  Links to check a set of combinations. Combinations to check are calculated with the last build in the build page or with the build to rebuild in the rebuild page (when 
 <a href="https://wiki.jenkins-ci.org/display/JENKINS/Rebuild+Plugin" rel="nofollow">Rebuild plugin</a> is installed). 
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>$class: 'All'</code></li>
<div><div>
  Check all enable combinations. 
</div></div>
<ul></ul><li><code>$class: 'CombinationFilterShortcut'</code></li>
<div><div>
  Decide combinations to check with a combinations filter. 
</div></div>
<ul><li><code>name</code>
<div><div>
  The name displayed as the shortcut link. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>combinationFilter</code>
<div><div>
  A Groovy expression to decide combinations to check. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'None'</code></li>
<div><div>
  Uncheck all combinations. 
</div></div>
<ul></ul><li><code>$class: 'PreviousShortcut'</code></li>
<div><div>
  Check combinations built in the previous build. 
</div></div>
<ul></ul><li><code>$class: 'ResultShortcut'</code></li>
<div><div>
  Check combinations with specific results in the previous build. 
</div></div>
<ul><li><code>name</code>
<div><div>
  The name displayed as the shortcut link. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>exact</code>
<div><div>
  Only checks child builds running exactly in the previous build. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>resultsToCheck</code>
<div><div>
  Results of child builds to check. 
</div></div>

<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
</ul><li><code>$class: 'MavenMetadataParameterDefinition'</code></li>
<div><div>
  This parameter allows the resolution of maven artifact versions by contacting the repository and reading the 
 <a href="http://docs.codehaus.org/display/MAVEN/Repository+Metadata" rel="nofollow">maven-metadata.xml</a>. 
 <p></p> If you named your parameter "MY_JAR" and have configured all values correctly. Then the following parameters will be set for the build step: 
 <ul> 
  <li>MY_JAR_VERSION - the version you selected in the dropdown or that was selected as part of an automated build</li> 
  <li>MY_JAR_ARTIFACT_URL - the full URL to the actual artifact selected. You can use something like "wget" to download that artifact and do something with it.</li> 
  <li>MY_JAR_GROUP_ID - echoes back your configuration</li> 
  <li>MY_JAR_ARTIFACT_ID - echoes back your configuration</li> 
  <li>MY_JAR_CLASSIFIER - echoes back your configuration</li> 
  <li>MY_JAR_PACKAGING - echoes back your configuration</li> 
 </ul> 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repoBaseUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>groupId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>packaging</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>classifier</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>versionFilter</code>
<div><div>
  Specify a 
 <a href="http://docs.oracle.com/javase/6/docs/api/java/util/regex/Pattern.html" rel="nofollow"> regular expression</a> which will be used to filter the versions which are actually displayed when triggering a new build. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sortOrder</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<div><div>
  For features such as SVN polling a default value is required. If job will only be started manually, this field is not necessary.
 <br> There are 4 special default values which will be evaluated at runtime: 
 <ul> 
  <li>FIRST - will evaluate to the first item in the drop-down that would have been presented had the build been executed manually.</li> 
  <li>LAST - will evaluate to the last item in the drop-down that would have been presented had the build been executed manually.</li> 
  <li>RELEASE - will evaluate to the version marked as RELEASE in the <a href="http://docs.codehaus.org/display/MAVEN/Repository+Metadata" rel="nofollow">repository metadata</a> for the configured artifact. The versionFilter even if defined is ignored for this default value. </li> 
  <li>LATEST - will evaluate to the version marked as LATEST in the <a href="http://docs.codehaus.org/display/MAVEN/Repository+Metadata" rel="nofollow">repository metadata</a> for the configured artifact. The versionFilter even if defined is ignored for this default value. </li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>maxVersions</code>
<div><div>
 The maximum number of versions to display in the drop-down. Any non-number value as well as 0 or negative values will default to all.
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>currentArtifactInfoUrl</code>
<div><div>
  The URL where an information resource about the currently used artifact can be requested. If the URL is provided and valid, the information will be displayed next to the drop-down. Otherwise not artifact information will be displayed. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>currentArtifactInfoLabel</code>
<div><div>
  An informational label that will be displayed in front of the aritfact information. When no label is specified, the default label 
 <i>Currently used artifact</i> will be displayed. Any label will only be displayed when a valid 
 <i>Current Artifact Info URL</i> is configured. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>currentArtifactInfoPattern</code>
<div><div>
  A pattern that describes the part of the artifact information resources' content to be displayed: 
 <ul>
  When no pattern is specified, the whole content will be displayed.
 </ul> 
 <ul>
  When a standard pattern is specified, only its first match in the content will be displayed.
 </ul> 
 <ul>
  When a pattern with a capturing group is specified, only the first group of its first match in the content will be displayed.
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'NodeParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultSlaves</code>
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>allowedSlaves</code>
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>triggerIfResult</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>nodeEligibility</code>
<div><div>
  Defines how selected offline nodes should be handled. 
 <ul> 
  <li><b>All Nodes</b> - trigger the job on all selected nodes, regardless of there online/offline state</li> 
  <li><b>Ignore Offline Nodes</b> - trigger the job only on nodes being online and having an executor</li> 
  <li><b>Ignore Temp Offline Nodes</b> - trigger the job on all selected nodes except on the ones currently manually marked as offline</li> 
 </ul> 
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AllNodeEligibility'</code></li>
<ul></ul><li><code>$class: 'IgnoreOfflineNodeEligibility'</code></li>
<ul></ul><li><code>$class: 'IgnoreTempOfflineNodeEligibility'</code></li>
<ul></ul></ul></li>
</ul><li><code>$class: 'PackageChoiceParameterDefinition'</code></li>
<div><div>
  List Content Packages available for download from a configured Adobe CRX repository. 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>baseUrl</code>
<div><div>
  Specify the base URL of the Adobe Granite server, including hostname and port. The CRX Package Manager service path will be appended to this value for all requests. For example, 
 <strong>http://localhost:4502</strong> or 
 <strong>https://author.mycorp.com</strong>, etc.
 <br> 
 <br> If login credentials for the server are different than those configured in the Connection Options section, you may override them in the Base URL by inserting 
 <code>username[:password]@</code> between the scheme and the hostname.
 <br> 
 <br> For example, to override the Username without changing the associated password or private key, you may use the following form:
 <br> 
 <br> http://
 <strong>deployer@</strong>localhost:4502
 <br> 
 <br> To override the credentials completely, provide a username and password (which may be provided by an encrypted parameter) by separating them with a colon, as shown below:
 <br> 
 <br> http://
 <strong>deployer:Password123@</strong>localhost:4502 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<div><div>
  Select the login credentials with which content packages will be listed from the CRX server.
 <br> 
 <br> 
 <strong>[Signature]</strong> credentials may be used if the target server supports HTTP Signature Authentication using the keyId format, 
 <code>/$username/keys/$fingerprint</code>.
 <br> 
 <br> Select "-none-" to use the default credentials set in the global 
 <strong>CRX Content Package Deployer - HTTP Client</strong> configuration. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>requestTimeout</code>
<div><div>
  Specify the timeout in milliseconds to wait for a response for each individual request. Specify a value of 0 to use default behavior. 
</div></div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>serviceTimeout</code>
<div><div>
  Specify the timeout in milliseconds to wait for PackageManager service availability between sending POST requests. Specify a value of 0 to use default behavior. 
</div></div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>multiselect</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>excludeNotInstalled</code>
<div><div>
  Filter the list to exclude packages which have been uploaded to the server, but which are not installed. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>excludeModified</code>
<div><div>
  Filter the list to exclude packages whose metadata have been modified after upload to the server, e.g. which need to be re-wrapped. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>visibleItemCount</code>
<div><div>
  Set the number of visible items displayed when multiselect is enabled. The default is 10. 
</div></div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
<li><code>query</code>
<div><div>
  Specify a full-text search query to filter the list of packages, such as "Adobe". 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>packageIdFilter</code>
<div><div>
  Specify a package ID filter to match against the list of packages returned from the configured Granite server.
 <br> 
 <br> A Package ID consists of the group, the name, and the version of a package, separated by colons (':').
 <br> 
 <br> Package ID filters must follow one of three patterns:
 <br> 
 <ul> 
  <li> group:name:version </li> 
  <li> group:name </li> 
  <li> name </li> 
 </ul> Each segment in the filter may be either ommitted or replaced with an asterisk ('*') to represent a wildcard. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PackageParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>rep</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pkg</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'ParameterSeparatorDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>separatorStyle</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sectionHeader</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sectionHeaderStyle</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PatchParameterDefinition'</code></li>
<div><div>
  Accepts a patch file to be submitted. This patch will be applied to the workspace after the source code is checked out, then the build will proceed. 
</div></div>
<ul></ul><li><code>$class: 'PersistentBooleanParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>successfulOnly</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PersistentChoiceParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>choices</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>successfulOnly</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PersistentPackageParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useAwsKeys</code>
<div><div> 
 <p>If you need to access the repository outside of the repository, you will need grant access to the S3 bucket.</p> 
 <p>When accessing it from within AWS, it's probable that the server itself provides the necessary access rights.</p> 
 <p> When accessing it from outside, you need to provide a key pair. These are set up in the AWS admin console. If you don't have access, please ask operations to create a new key pair with access to the specified bucket. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>awsAccessKeyId</code>
<div><div> 
 <p>This is the AWS secret key setup in the AWS console. It will resemble the form: ‘<em>AAAAAAAAAA2AAA2AAAAA</em>’</p> 
 <p>If you don't have access to the AWS console, and you need an access key pair, please contact someone in operations.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsSecretAccessKey</code>
<div><div> 
 <p>This is the AWS secret key setup in the AWS console. It will resemble the form: ‘<em>XxXXXxx/1ZZz1zZZZ11zzZ1zz/YyYyYyyYyyyyYY</em>’</p> 
 <p>If you don't have access to the AWS console, and you need an access key pair, please contact someone in operations.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>bucketName</code>
<div><div> 
 <p> This should be set to a valid bucket name that you can access using the key value pair, or if within AWS, that the server has access to. </p> 
 <p> Ensure that the bucket specified contains the repo. It might sound obvious, but I just wanted to point that out. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repoPath</code>
<div><div> 
 <p>This is the path to the actual repo containing the artifacts, relative to the AWS S3 bucket.</p> 
 <p>For example, given the S3 bucket ‘<em>vhols-common-test-yumrepo</em>’, the path to the locations-public-api repo is repos/locations-public-api</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repositoryType</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PersistentStringParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>successfulOnly</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PersistentTextParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>successfulOnly</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PersistentYumParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>useAwsKeys</code>
<div><div> 
 <p>If you need to access the repository outside of the repository, you will need grant access to the S3 bucket.</p> 
 <p>When accessing it from within AWS, it's probable that the server itself provides the necessary access rights.</p> 
 <p> When accessing it from outside, you need to provide a key pair. These are set up in the AWS admin console. If you don't have access, please ask operations to create a new key pair with access to the specified bucket. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>awsAccessKeyId</code>
<div><div> 
 <p>This is the AWS secret key setup in the AWS console. It will resemble the form: ‘<em>AAAAAAAAAA2AAA2AAAAA</em>’</p> 
 <p>If you don't have access to the AWS console, and you need an access key pair, please contact someone in operations.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>awsSecretAccessKey</code>
<div><div> 
 <p>This is the AWS secret key setup in the AWS console. It will resemble the form: ‘<em>XxXXXxx/1ZZz1zZZZ11zzZ1zz/YyYyYyyYyyyyYY</em>’</p> 
 <p>If you don't have access to the AWS console, and you need an access key pair, please contact someone in operations.</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>bucketName</code>
<div><div> 
 <p> This should be set to a valid bucket name that you can access using the key value pair, or if within AWS, that the server has access to. </p> 
 <p> Ensure that the bucket specified contains the repo. It might sound obvious, but I just wanted to point that out. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repoPath</code>
<div><div> 
 <p>This is the path to the actual repo containing the artifacts, relative to the AWS S3 bucket.</p> 
 <p>For example, given the S3 bucket ‘<em>vhols-common-test-yumrepo</em>’, the path to the locations-public-api repo is repos/locations-public-api</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PromotedBuildParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>jobName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>process</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PromotionLevelParameter'</code></li>
<div><div>
  Defines a parameter selected from the configured promotion levels. Note that the parameter provided to builds has the 
 <b>numeric</b> value of the promotion level, i.e. its index in the list below, starting with one. 
 <br> If used with the Copy Artifact plugin to copy artifacts of a particular promotion level, the name of the parameter should be COPY_PROMOTION_LEVEL. 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultLevel</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'RandomStringParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedValidationMessage</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'ReviewboardParameterDefinition'</code></li>
<div><div>
  Accepts a patch url or number of review request. This patch will be applied to the workspace after the source code is checked out, then the build will proceed. 
</div></div>
<ul></ul><li><code>$class: 'RunFilterParameter'</code></li>
<div><div>
  Defines a parameter that can be used for a build filter of Copy Artifact. 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>run</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>projectName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>filter</code>
<ul><li><b>Values:</b> <code>ALL</code>, <code>STABLE</code>, <code>SUCCESSFUL</code>, <code>COMPLETED</code></li></ul></li>
</ul><li><code>$class: 'RunSelectorParameter'</code></li>
<div><div> 
 <p> Defines a parameter that specifies how a Copy Artifact build step should select which build to copy from. Note that this parameter type is easier to use when starting the build from a browser; to specify a value via direct HTTP POST or the CLI, valid XML must be given. </p> 
 <p> Be aware that this string value is encoded selector configuration, and not compatible with different plugin versions. </p> 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultSelector</code>
<ul><b>Nested Choice of Objects</b>
<li><code>buildNumber</code></li>
<ul><li><code>buildNumber</code>
<div><div>
  While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fallback</code></li>
<ul><li><code>entryList</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>runSelector</code>
<ul><b>Nested Choice of Objects</b>
<li><code>buildNumber</code></li>
<ul><li><code>buildNumber</code>
<div><div>
  While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>fallback</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameterName</code>
<div><div>
  Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p> You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>permalink</code></li>
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>status</code></li>
<ul><li><code>buildStatus</code>
<ul><li><b>Values:</b> <code>STABLE</code>, <code>SUCCESSFUL</code>, <code>UNSTABLE</code>, <code>FAILED</code>, <code>COMPLETED</code>, <code>ANY</code></li></ul></li>
</ul><li><code>triggering</code></li>
<ul><li><code>allowUpstreamDependencies</code> (optional)
<div><div>
  Tracks upstream builds not only with build-triggering relations, but also with relations via artifacts. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>upstreamFilterStrategy</code> (optional)
<div><div>
  Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System". 
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
</ul></ul></li>
<li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code></li>
<ul><li><code>runFilterList</code>
<ul><b>Array/List</b><br/>
<b>Nested Choice of Objects</b>
<li><code>and</code></li>
<li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>displayName</code></li>
<ul><li><code>runDisplayName</code>
<div><div>
  Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'DownstreamRunFilter'</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>not</code></li>
<li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>or</code></li>
<li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameter</code>
<div><div>
  Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as 
 <code>PARAM</code>, specify 
 <code>${PARAM}</code> here. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>parameters</code></li>
<ul><li><code>paramsToMatch</code>
<div><div> 
 <p> Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked. </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>saved</code></li>
<ul></ul></ul></li>
</ul></li>
</ul><li><code>parameterized</code></li>
<ul><li><code>parameterName</code>
<div><div>
  Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p> You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>permalink</code></li>
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>status</code></li>
<ul><li><code>buildStatus</code>
<ul><li><b>Values:</b> <code>STABLE</code>, <code>SUCCESSFUL</code>, <code>UNSTABLE</code>, <code>FAILED</code>, <code>COMPLETED</code>, <code>ANY</code></li></ul></li>
</ul><li><code>triggering</code></li>
<ul><li><code>allowUpstreamDependencies</code> (optional)
<div><div>
  Tracks upstream builds not only with build-triggering relations, but also with relations via artifacts. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>upstreamFilterStrategy</code> (optional)
<div><div>
  Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System". 
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
</ul></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'SauceParameterDefinition'</code></li>
<ul></ul><li><code>$class: 'ScriptSelectionTaskDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>path</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>arrayCheckBox</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>variableName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>check</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>type</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>parent</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>testDelimSymbol</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>nodeDelimSymbol</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>countDelimiterSymbol</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>delimiter</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'SpringBootLibrariesListParameterDefinition'</code></li>
<ul><li><code>springBootVersion</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'StashBranchParameterDefinition'</code></li>
<ul><li><code>name</code>
<div><div>
  The name of the parameter. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>repository</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>branchNameRegex</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tagNameRegex</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>string</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'TestExecuter'</code></li>
<div><div>
  This plugin allows you to choose specific tests you want to run.
 <br> First, you need to specify the name of the environment variable in which you want your selected tests to be saved in (after build the selected tests will be in this environment variable as a JSON array).
 <br> Second, you need to enter the properties file path. This file will contain all your tests and maybe some extra fields for the plugin (more details about the properties file are in the appropriate help field).
 <br> After that, your tests will be shown in a tree diagram, allowing you to select some of them. 
</div></div>
<ul><li><code>name</code>
<div><div>
  Enter the name of the 
 <b>environment variable</b> in which you want your selected tests to be saved in (after build the selected tests will be in this environment variable as a JSON array).
 <br> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>propertiesFilePath</code>
<div><div> 
 <div>
   The properties file you enter 
  <b>must</b> have a property called 
  <b>tests</b>.
 </div> 
 <div>
   The 
  <b>tests</b> property value is a JSON array that contains a JSON object for each test. 
  <br> In each test object you need to specify it's attributes by a key/value pairs.
 </div> 
 <br> 
 <div>
   The following properties will allow you to select specific fields which have a special meaning: 
 </div> 
 <div>
  1.
  <span>&nbsp; </span>
  <b>enableField</b> - the name of the field that will imply if the test is enabled or not. 
  <br> if the value in the specified field, for some test(s), will be false then the test will not be shown at all.
 </div> 
 <div>
  2.
  <span>&nbsp; </span>
  <b>groupBy</b> - the field that the plugin will group the tests by. 
  <br> if 2 tests have the same value in this field, they will be in the same group.
 </div> 
 <div>
  3.
  <span>&nbsp; </span>
  <b>showFields - </b>the field(s) that will be shown in the tests tree.
 </div> 
 <div>
  4.
  <span>&nbsp; </span>
  <b>multiplicityField - </b>the field that will be set to the amount of times the test should run.
 </div> 
 <div>
  5.
  <span>&nbsp; </span>
  <b>fieldSeparator - </b>the character that will separate between the fields in the tests tree.
 </div> 
 <div> 
  <b>Each property must</b> be defined either in the properties file or in the override section bellow. 
  <br> If you want to change the properties you defined In the file, you can override them in the section bellow. 
 </div> 
 <br> 
 <div> 
  <u>This is an <b>example</b> for a properties file which contains all above properties: </u> 
 </div> 
 <div>
  tests=[{"enabled":true,"owner":"shushu","testgroup":"A","testcase":"single"},{"enabled":false,"owner":"shushu","testgroup":"B","setuptype":"basic","testcase":"triple"}]
 </div> 
 <div>
  enableField=enabled
 </div> 
 <div>
  groupBy=testgroup
 </div> 
 <div>
  fieldSeparator=.
 </div> 
 <div>
  showFields=testsuite,testcase
 </div> 
 <div>
  multiplicityField=multiplicity
 </div> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>enableField</code>
<div><div>
  Setting 
 <b>Enable Field</b> property. 
 <br> 
 <b>Enable Field</b> - the name of the field that will imply if the test is enabled or not. If the value in the specified field, for some test(s), will be false then the test will not be shown at all. 
</div></div>

<ul><b>Nested Object</b>
<li><code>text</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>groupBy</code>
<div><div>
  Setting 
 <b>Group By</b> property. 
 <br> 
 <b>Group By</b> - the field that the plugin will group the tests by. If 2 tests have the same value in this field, they will be in the same group.
</div></div>

<ul><b>Nested Object</b>
<li><code>text</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>fieldSeparator</code>
<div><div>
  Setting 
 <b>Field Separator</b> property. 
 <br> 
 <b>Field Separator </b>- the character that will separate between the fields in the tests tree. 
</div></div>

<ul><b>Nested Object</b>
<li><code>text</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>showFields</code>
<div><div>
  Setting 
 <b>Show Fields</b> property. 
 <br> 
 <b>Show Fields</b> - the field(s) that will be shown in the tests tree.
 <br> If you click on "Show/Hide Available Fields" button then next to each available field appears (howManyTestsHasThisField/amountOfTests). 
</div></div>

<ul><b>Nested Object</b>
<li><code>text</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>multiplicityField</code>
<div><div>
  Setting 
 <b>Multiplicity Field</b> property. 
 <br> 
 <b>Multiplicity Field</b> - the field that will be set to the amount of times the test should run. 
</div></div>

<ul><b>Nested Object</b>
<li><code>text</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul><li><code>text</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'ToolVersionParameterDefinition'</code></li>
<ul><li><code>toolName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'VBoxParameterDefinition'</code></li>
<div><div>
  Build parameter with virtual node names. Parameter 
 <i>name</i> is exported to the build from virtual node names joined by node name delimiter. 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>nodeDelimiter</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'ValidatingStringParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>regex</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedValidationMessage</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'VersionParameterDefinition'</code></li>
<div><div> 
 <p> Defines the artifact build parameter for selecting a version of this artifact. </p> 
 <ul> 
  <li>Repository - the repository to resolve the artifact from</li> 
  <li>Group Id - the group id of the artifact to resolve</li> 
  <li>Artifact Id - the artifact id of the artifact to resolve</li> 
  <li>Description - a description for what the artifact is used for</li> 
 </ul> 
 <b>This parameter type does not support a default value - therefore, this type should not be used in a scheduled job!</b> 
</div></div>
<ul><li><code>repoid</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>groupid</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>artifactid</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>propertyName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'WHideParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'WReadonlyStringParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'WReadonlyTextParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'com.michelin.cio.hudson.plugins.passwordparam.PasswordParameterDefinition'</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'com.moded.extendedchoiceparameter.ExtendedChoiceParameterDefinition'</code></li>
<ul><li><code>name</code>
<div><div>
  The name of the parameter. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>type</code>
<div><div>
  The type of parameter: 
 <ul> 
  <li>Single Select: user chooses a single selection from a drop down menu, populated by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li> 
  <li>Multi Select: a user can choose multiple selections from a multi-line box, populated by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li> 
  <li>Check Boxes: user can check off zero or more check boxes, labeled by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li> 
  <li>Multi-Level Single Select: user chooses a selection from a drop down, and then a another drop down appears with selections that depend on the first value, and upon second selection a third drop down may appear depending on the first two selections, and so on.<br><br> The property file is a tab delimited file, with levels defined in columns and choices defined in rows. For example, to have a 2 level selection where you first select a country and then a city, you could specify a file such as the following:<br><br> <pre>
Country	City
United States	San Francisco
United States	Chicago
Mexico	Mexico City
Mexico	Cancun
            </pre> This would result in a first drop down with the options "Select a country...", "United States", and "Mexico" (the initial selection is "Select a country...", which serves as a label for the drop down). After the user selects a country, a "City" drop down would appear. If United States was chosen first, then San Francisco and Chicago would be options, but if Mexico was selected then instead Mexico City and Cancun would be options. <br><br> The columns that should represent levels must be specified in the value field. For example "Country,City" could be valid values. <br><br> Note that default values are not supported for multi-level selects.<br><br> </li> 
  <li>Multi-Level Multi Select: same as single select, but after all levels are chosen, a button appears to "Select another..." and an additional multi-level selection is presented. </li>
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<div><div>
  Comma separated list of values for the single select or multi-select box. 
 <br>
 <br>This field can be left blank if the comma separated values need to be picked up from a properties file (set via 'Property File' and 'Property Key'). 
 <br>
 <br> This value has different meaning for multi-level select -- see the parameter type help for more info. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>propertyFile</code>
<div><div>
  The 
 <a href="http://download.oracle.com/javase/6/docs/api/java/util/Properties.html" rel="nofollow">properties file</a> is a collection of key,value pairs of the form key=value1,value2,... 
 <br>
 <br> Property files may reference other properties. For example: 
 <blockquote>
   prop1=a,b,c,d,e
  <br> prop2=${prop1},f,g,h 
 </blockquote> The properties file can be placed anywhere on the file-system that Jenkins can access. 
 <br>
 <br> This property file has different meaning for multi-level select -- see the parameter type help for more info. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>propertyKey</code>
<div><div>
  The property of the property file to use. 
 <br>
 <br> For example, if the property file was the following: 
 <blockquote>
   prop1=a,b,c,d,e
  <br> prop2=1,2,3,4 
 </blockquote> Then you could specify the property as either prop1 or prop2. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<div><div>
  Initial selection of the single-select or mult-select box. 
 <br>
 <br>In case of the multi-select box, default value can be a comma separated string. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultPropertyFile</code>
<div><div>
  Absolute path (specified without using environment variables). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultPropertyKey</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>quoteValue</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>visibleItemCount</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>multiSelectDelimiter</code>
<div><div> 
 <p>Inserts this value between selections when the parameter is a multi-select.</p> 
 <p>The default when empty is ','</p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>bindFieldName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>svnPath</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>svnUrl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>svnUserName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>svnPassword</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>projectName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>roleBasedFilter</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'com.perfectomobile.jenkins.copyartifact.BuildSelectorParameter'</code></li>
<div><div>
  Defines a parameter that specifies how a Copy Artifact build step should select which build to copy from. Note that this parameter type is easier to use when starting the build from a browser; to specify a value via direct HTTP POST or the CLI, valid XML must be given. 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultSelector</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'ParameterizedBuildSelector'</code></li>
<ul><li><code>parameterName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PermalinkBuildSelector'</code></li>
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'SavedBuildSelector'</code></li>
<ul></ul><li><code>$class: 'SpecificBuildSelector'</code></li>
<ul><li><code>buildNumber</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'StatusBuildSelector'</code></li>
<ul><li><code>stableOnly</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'TriggeredBuildSelector'</code></li>
<ul><li><code>fallback</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>$class: 'WorkspaceSelector'</code></li>
<ul></ul></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'com.veertu.plugin.anka.parameters.CloudSelectorParameter'</code></li>
<ul></ul><li><code>password</code></li>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultValue</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'hudson.plugins.copyartifact.BuildSelectorParameter'</code></li>
<div><div> 
 <p> Defines a parameter that specifies how a Copy Artifact build step should select which build to copy from. Note that this parameter type is easier to use when starting the build from a browser; to specify a value via direct HTTP POST or the CLI, valid XML must be given. </p> 
 <p> Be aware that this string value is encoded selector configuration, and not compatible with different plugin versions. </p> 
</div></div>
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>defaultSelector</code>
<ul><b>Nested Choice of Objects</b>
<li><code>downstream</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>lastCompleted</code></li>
<ul></ul><li><code>$class: 'MultiJobBuildSelector'</code></li>
<ul></ul><li><code>buildParameter</code></li>
<ul><li><code>parameterName</code>
<div><div>
  Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p> You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>permalink</code></li>
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PromotedBuildSelector'</code></li>
<ul><li><code>level</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul><li><code>latestSavedBuild</code></li>
<ul></ul><li><code>specific</code></li>
<ul><li><code>buildNumber</code>
<div><div>
  While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). The display name of a build and permalinks (e.g. "lastSuccessfulBuild", "lastBuild"...) can be used as well. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>lastSuccessful</code></li>
<ul><li><code>stable</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>upstream</code></li>
<ul><li><code>fallbackToLastSuccessful</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>upstreamFilterStrategy</code>
<div><div>
  Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System". 
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
<li><code>allowUpstreamDependencies</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>workspace</code></li>
<ul></ul></ul></li>
<li><code>description</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'org.jenkinsci.plugins.vsphere.parameters.CloudSelectorParameter'</code></li>
<ul></ul></ul></li>
<li><code>submitter</code> (optional)
<div><div>
  User IDs and/or 
 <em>external</em> group names of person or people permitted to respond to the input, separated by ','. If you configure "alice, bob", will match with "alice" but not with "bob". You need to remove all the white spaces. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>submitterParameter</code> (optional)
<div><div>
  If specified, this is the name of the return value that will contain the ID of the user that approves this input. The return value will be handled in a fashion similar to the 
 <code>parameters</code> value. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
