---
layout: pipelinesteps
title: "流水线实用程序步骤"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== 流水线实用程序步骤

plugin:pipeline-utility-steps[在插件索引中查看此插件]

=== +findFiles+: 在工作区中查找文件
++++
<div><p> Find files in the current working directory. The step returns an array of file info objects who's properties you can see in the below example.<br> <em>Ex: </em> <code> def files = findFiles(glob: '**/TEST-*.xml') echo """${files[0].name} ${files[0].path} ${files[0].directory} ${files[0].length} ${files[0].lastModified}""" </code> </p></div>
<ul><li><code>glob</code> (optional)
<div><p> <a href="https://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant style pattern</a> of file paths that should match. If this property is set all descendants of the current working directory will be searched for a match and returned, if it is omitted only the direct descendants of the directory will be returned. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +nodesByLabel+: 按标签排列的节点列表默认排除脱机节点
++++
<div><div>
  Returns an array of 
 <code>node</code> names with the given label. 
</div></div>
<ul><li><code>label</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>offline</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +readJSON+: 从工作区中的文件中读取JSON.
++++
<div><p> Reads a file in the current working directory or a String as a plain text <a href="http://www.json.org/json-it.html" rel="nofollow">JSON</a> file. The returned object is a normal Map with String keys or a List of primitives or Map. </p> 
<p> <strong>Example:</strong><br> <code></code></p>
<pre><code>
def props = readJSON file: 'dir/input.json'
assert props['attr1'] == 'One'
assert props.attr1 == 'One'

def props = readJSON text: '{ "key": "value" }'
assert props['key'] == 'value'
assert props.key == 'value'

def props = readJSON text: '[ "a", "b"]'
assert props[0] == 'a'
assert props[1] == 'b'
	</code></pre> 
<p></p></div>
<ul><li><code>file</code> (optional)
<div><p> Path to a file in the workspace from which to read the JSON data. <em>Data could be access as an array or a map.</em> </p> 
<p> You can only specify <code>file</code> <strong>or</strong> <code>text</code>, not both in the same invocation. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>text</code> (optional)
<div><p> A string containing the JSON formatted data. <em>Data could be access as an array or a map.</em> </p> 
<p> You can only specify <code>file</code> <strong>or</strong> <code>text</code>, not both in the same invocation. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +readManifest+: 阅读Jar 清单
++++
<div><p> Reads a <a href="https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#JAR_Manifest" rel="nofollow">Jar Manifest</a> file or text and parses it into a set of Maps. The returned data structure has two properties: <code>main</code> for the main attributes, and <code>entries</code> containing each individual section (except for main). </p> 
<p> <strong>Example:</strong><br> <code> </code></p>
<pre><code>
            def man = readManifest file: 'target/my.jar'
            assert man.main['Version'] == '6.15.8'
            assert man.main['Application-Name'] == 'My App'
            assert man.entries['Section1']['Key1'] == 'value1-1'
            assert man.entries['Section2']['Key2'] == 'value2-2'
        </code></pre>
<code> </code> 
<p></p></div>
<ul><li><code>file</code> (optional)
<div><p> Optional path to a file to read. It could be a plain text, <code>.jar</code>, <code>.war</code> or <code>.ear</code>. In the latter cases the manifest will be extracted from the archive and then read. </p> 
<p> You can only specify <code>file</code> <strong>or</strong> <code>text</code>, not both in the same invocation. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>text</code> (optional)
<div><p> Optional text containing the manifest data. </p> 
<p> You can only specify <code>file</code> <strong>or</strong> <code>text</code>, not both in the same invocation. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +readMavenPom+: 阅读maven项目文件.
++++
<div><p> Reads a <a href="https://maven.apache.org/pom.html" rel="nofollow">Maven project</a> file. The returned object is a <a href="http://maven.apache.org/components/ref/3.3.9/maven-model/apidocs/org/apache/maven/model/Model.html" rel="nofollow">Model</a> . </p></div>
<ul><li><code>file</code> (optional)
<div><p> Optional path to the file to read. <em>If left empty the step will try to read <code>pom.xml</code> in the current working directory</em>. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +readProperties+: 从工作区或文本中的文件读取属性.
++++
<div><p> Reads a file in the current working directory or a String as a plain text <a href="https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html" rel="nofollow">Java Properties</a> file. The returned object is a normal Map with String keys. The map can also be pre loaded with default values before reading/parsing the data. </p> 
<strong>Fields:</strong> 
<ul> 
 <li> <code>file</code>: Optional path to a file in the workspace to read the properties from. <em>These are added to the resulting map after the defaults and so will overwrite any key/value pairs already present.</em> </li> 
 <li> <code>text</code>: An Optional String containing properties formatted data. <em>These are added to the resulting map after <code>file</code> and so will overwrite any key/value pairs already present.</em> </li> 
 <li> <code>defaults</code>: An Optional Map containing default key/values. <em>These are added to the resulting map first.</em> </li> 
 <li> <code>interpolate</code>: Flag to indicate if the properties should be interpolated or not. In case of error or cycling dependencies, the original properties will be returned. </li> 
</ul> 
<p> <strong>Example:</strong><br> <code> </code></p>
<pre><code>
        def d = [test: 'Default', something: 'Default', other: 'Default']
        def props = readProperties defaults: d, file: 'dir/my.properties', text: 'other=Override'
        assert props['test'] == 'One'
        assert props['something'] == 'Default'
        assert props.something == 'Default'
        assert props.other == 'Override'
        </code></pre>
<code> </code> 
<strong>Example with interpolation:</strong> 
<code> <pre>
        def props = readProperties interpolate: true, file: 'test.properties'
        assert props.url = 'http://localhost'
        assert props.resource = 'README.txt'
        // if fullUrl is defined to ${url}/${resource} then it should evaluate to http://localhost/README.txt
        assert props.fullUrl = 'http://localhost/README.txt'
        </pre> </code> 
<p></p></div>
<ul><li><code>defaults</code> (optional)
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>file</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>interpolate</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>text</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +readYaml+: 从工作区或文本中的文件中读取yaml.
++++
<div><p> Reads a file in the current working directory or a String as a plain text <a href="http://yaml.org" rel="nofollow">YAML</a> file. It uses <a href="https://bitbucket.org/asomov/snakeyaml" rel="nofollow">SnakeYAML</a> as YAML processor. The returned objects are standard Java objects like List, Long, String, ...: bool: [true, false, on, off] int: 42 float: 3.14159 list: ['LITE', 'RES_ACID', 'SUS_DEXT'] map: {hp: 13, sp: 5} </p> 
<strong>Fields:</strong> 
<ul> 
 <li> <code>file</code>: Optional path to a file in the workspace to read the YAML datas from. </li> 
 <li> <code>text</code>: An Optional String containing YAML formatted datas. <em>These are added to the resulting object after <code>file</code> and so will overwrite any value already present if not a new YAML document</em> </li> 
</ul> 
<p> <strong>Examples:</strong><br> With only one YAML document : <code> </code></p>
<pre><code>
        def datas = readYaml text: """
something: 'my datas'
size: 3
isEmpty: false
"""
        assert datas.something == 'my datas'
        assert datas.size == 3
        assert datas.isEmpty == false
        </code></pre>
<code> </code> With several YAML documents : 
<code> <pre>
        def datas = readYaml text: """
---
something: 'my first document'
---
something: 'my second document'
"""
        assert datas.size() == 2
        assert datas[0].something == 'my first document'
        assert datas[1].something == 'my second document'
        </pre> </code> With file dir/my.yml containing 
<code>something: 'my datas'</code> : 
<code> <pre>
        def datas = readYaml file: 'dir/my.yml', text: "something: 'Override'"
        assert datas.something == 'Override'
        </pre> </code> 
<p></p></div>
<ul><li><code>file</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>text</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +sha1+: 计算给定文件的SHA1
++++
<div><p> Computes the SHA1 of a given file. </p></div>
<ul><li><code>file</code>
<div><p> The path to the file to hash. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +tee+: 输出到文件
++++
<ul><li><code>file</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +touch+: 在工作区中创建一个文件（如果尚不存在），并设置时间戳
++++
<div><p> Creates a file if it does not already exist, and updates the timestamp. </p></div>
<ul><li><code>file</code>
<div><p> The path to the file to touch. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>timestamp</code> (optional)
<div><p> The timestamp to set (number of ms since the epoc), leave empty for current system time. </p></div>

<ul><li><b>Type:</b> <code>long</code></li></ul></li>
</ul>


++++
=== +unzip+: 提取Zip文件
++++
<div><p> Extract a zip file in the workspace. </p></div>
<ul><li><code>zipFile</code>
<div><p> The name/path of the zip file to extract. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>charset</code> (optional)
<div><p> Specify which Charset you wish to use eg. UTF-8 </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>dir</code> (optional)
<div><p> The path of the base directory to extract the zip to. Leave empty to extract in the current working directory. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>glob</code> (optional)
<div><p> <a href="https://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant style pattern</a> of files to extract from the zip. Leave empty to include all files and directories. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>quiet</code> (optional)
<div><p> Suppress the verbose output that logs every single file that is dealt with. <em>E.g.</em> <code> unzip zipFile: 'example.zip', quiet: true </code> </p></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>read</code> (optional)
<div><p> Read the content of the files into a Map instead of writing them to the workspace. The keys of the map will be the path of the files read. <em>E.g.</em> <code> def v = unzip zipFile: 'example.zip', glob: '*.txt', read: true String version = v['version.txt'] </code> </p></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>test</code> (optional)
<div><p> Test the integrity of the archive instead of extracting it. When this parameter is enabled, all other parameters <em>(except for zipFile)</em> will be ignored. The step will return <code>true</code> or <code>false</code> depending on the result instead of throwing an exception. </p></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +writeJSON+: 将JSON写入工作区中的文件.
++++
<div><p> Write a <a href="http://www.json.org/json-it.html" rel="nofollow">JSON</a> file in the current working directory. That for example was previously read by <code>readJSON</code>. </p> 
<strong>Fields:</strong> 
<ul> 
 <li> <code>json</code>: The <a href="http://json-lib.sourceforge.net/apidocs/jdk15/net/sf/json/JSON.html" rel="nofollow">JSON</a> object to write. </li> 
 <li> <code>file</code>: Path to a file in the workspace to write to. </li> 
 <li> <code>pretty</code> <i>(optional)</i>: Prettify the output with this number of spaces added to each level of indentation. </li> 
</ul> 
<p> <strong>Example:</strong><br> <code></code></p>
<pre><code>
def input = readJSON file: 'myfile.json'
//Do some manipulation
writeJSON file: 'output.json', json: input
// or pretty print it, indented with a configurable number of spaces
writeJSON file: 'output.json', json: input, pretty: 4
	</code></pre> 
<p></p></div>
<ul><li><code>file</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>json</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>pretty</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul>


++++
=== +writeMavenPom+: 编写一个Maven项目文件.
++++
<div><p> Writes a <a href="https://maven.apache.org/pom.html" rel="nofollow">Maven project</a> file. That for example was previously read by <code>readMavenPom</code>. </p> 
<strong>Fields:</strong> 
<ul> 
 <li> <code>model</code>: The <a href="http://maven.apache.org/components/ref/3.3.9/maven-model/apidocs/org/apache/maven/model/Model.html" rel="nofollow">Model</a> object to write. </li> 
 <li> <code>file</code>: Optional path to a file in the workspace to write to. <em>If left empty the step will write to <code>pom.xml</code> in the current working directory.</em> </li> 
</ul> 
<p> <strong>Example:</strong><br> <code> </code></p>
<pre><code>
        def pom = readMavenPom file: 'pom.xml'
        //Do some manipulation
        writeMavenPom model: pom
        </code></pre>
<code> </code> 
<p></p></div>
<ul><li><code>model</code>
<ul><code>org.apache.maven.model.Model</code>
</ul></li>
<li><code>file</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +writeYaml+: 从一个对象写一个yaml.
++++
<div><p> Writes a yaml file in the current working directory from an Object or a String. It uses <a href="https://bitbucket.org/asomov/snakeyaml" rel="nofollow">SnakeYAML</a> as YAML processor. The call will fail if the file already exists. </p> 
<strong>Fields:</strong> 
<ul> 
 <li> <code>file</code>: Mandatory path to a file in the workspace to write the YAML datas to. </li> 
 <li> <code>data</code>: A Mandatory Object containing the data to be serialized. </li> 
 <li> <code>charset</code>: Optionally specify the charset to use when writing the file. Defaults to UTF-8 if nothing else is specified. What charsets that are available depends on your Jenkins master system. The java specification tells us though that at least the following should be available: 
  <ul> 
   <li>US-ASCII</li> 
   <li>ISO-8859-1</li> 
   <li>UTF-8</li> 
   <li>UTF-16BE</li> 
   <li>UTF-16LE</li> 
   <li>UTF-16</li> 
  </ul> </li> 
</ul> 
<p> <strong>Examples:</strong><br> <code> </code></p>
<pre><code>
        def amap = ['something': 'my datas',
                    'size': 3,
                    'isEmpty': false]

        writeYaml file: 'datas.yaml', data: amap
        def read = readYaml file: 'datas.yaml'

        assert read.something == 'my datas'
        assert read.size == 3
        assert read.isEmpty == false
        </code></pre>
<code> </code> 
<p></p></div>
<ul><li><code>file</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>data</code>



++++
=== +zip+: 创建Zip 文件
++++
<div><p> Create a zip file of content in the workspace. </p></div>
<ul><li><code>zipFile</code>
<div><p> The name/path of the zip file to create. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>archive</code> (optional)
<div><p> If the zip file should be archived as an artifact of the current build. The file will still be kept in the workspace after archiving. </p></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>dir</code> (optional)
<div><p> The path of the base directory to create the zip from. Leave empty to create from the current working directory. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>glob</code> (optional)
<div><p> <a href="https://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant style pattern</a> of files to include in the zip. Leave empty to include all files and directories. </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
