---
layout: pipelinesteps
title: "Pipeline: AWS Steps"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Pipeline: AWS Steps

plugin:pipeline-aws[View this plugin on the Plugins Index]

=== +awaitDeploymentCompletion+: Wait for AWS CodeDeploy deployment completion
++++
<ul><li><code>deploymentId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +awsIdentity+: Print and return the AWS identity
++++
<ul></ul>


++++
=== +cfInvalidate+: Invalidate given paths in CloudFront distribution
++++
<ul><li><code>distribution</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>paths</code>
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +cfnCreateChangeSet+: Create CloudFormation change set
++++
<ul><li><code>changeSet</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>stack</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>



++++
=== +cfnDelete+: Delete CloudFormation stack
++++
<ul><li><code>stack</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pollInterval</code> (optional)
<ul><li><b>Type:</b> <code>long</code></li></ul></li>
</ul>


++++
=== +cfnDeleteStackSet+: Delete CloudFormation Stack Set
++++
<ul><li><code>stackSet</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pollInterval</code> (optional)
<ul><li><b>Type:</b> <code>long</code></li></ul></li>
</ul>


++++
=== +cfnDescribe+: Describe outputs of CloudFormation stack
++++
<ul><li><code>stack</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +cfnExecuteChangeSet+: Execute CloudFormation change set
++++
<ul><li><code>changeSet</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>stack</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pollInterval</code> (optional)
<ul><li><b>Type:</b> <code>long</code></li></ul></li>
</ul>


++++
=== +cfnExports+: Describe CloudFormation global exports
++++
<ul></ul>


++++
=== +cfnUpdate+: Create or Update CloudFormation stack
++++
<ul><li><code>stack</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>



++++
=== +cfnUpdateStackSet+: Create or Update CloudFormation Stack Set
++++
<ul><li><code>stackSet</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>



++++
=== +cfnValidate+: Validate CloudFormation template
++++
<ul><li><code>file</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>url</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +deployAPI+: Deploy the given API Gateway API
++++
<ul><li><code>api</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>stage</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>description</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>variables</code> (optional)
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +ec2ShareAmi+: Create and return the ECR login string
++++
<ul><li><code>accountIds</code> (optional)
<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>amiId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +ecrLogin+: Create and return the ECR login string
++++
<ul><li><code>email</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +invokeLambda+: Invoke a given Lambda function
++++
<ul><li><code>functionName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>



++++
=== +listAWSAccounts+: List all AWS accounts of the organization
++++
<ul></ul>


++++
=== +s3Delete+: Delete file from S3
++++
<div><div> 
 <p> Delete a file/folder from S3. If the path ends in a "/", then the path will be interpreted to be a folder, and all of its contents will be removed. </p> 
</div></div>
<ul><li><code>bucket</code>
<div><div>
  This is the bucket to use. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>path</code>
<div><div> 
 <p> This is the path inside the bucket to delete. If this ends in a "/", then the path will be interpreted to be a folder, and all of its contents will be removed. </p> 
 <p> <i>Do not begin with a leading "/".</i> </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pathStyleAccessEnabled</code> (optional)
<div><div>
  Enabled/Disable Path-style Access for AWS S3. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>payloadSigningEnabled</code> (optional)
<div><div>
  Enabled/Disable Payload Signing for AWS S3. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +s3Download+: Copy file from S3
++++
<div><div> 
 <p> Download a file/folder from S3 to the local workspace. Set optional parameter force to true to overwrite any existing files in workspace. If the path ends with a /, then the complete virtual directory will be downloaded. </p> 
</div></div>
<ul><li><code>file</code>
<div><div>
  This is the local target file to download into. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>bucket</code>
<div><div>
  This is the bucket to use. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pathStyleAccessEnabled</code> (optional)
<div><div>
  Enabled/Disable Path-style Access for AWS S3. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>payloadSigningEnabled</code> (optional)
<div><div>
  Enabled/Disable Payload Signing for AWS S3. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>force</code> (optional)
<div><div>
  Set this to true to overwrite local workspace files. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>path</code> (optional)
<div><div>
  This is the path inside the bucket to use. 
 <i>Do not begin with a leading "/".</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +s3FindFiles+: Find files in S3
++++
<div><div> 
 <p> Return a list of all of the files/folders in the bucket. If path is given, then it will be used as the root of the search. Results are returned <i>relative</i> to path; if path is not given, then the results will contain the full S3 path. </p> 
 <p> The following all ultimately return one item referring to "path/to/my/file.ext"; however, by limiting the scope via path, the results are different. </p>
 <ul> 
  <li> files = s3FindFiles bucket: "my-bucket", glob: "path/to/my/file.ext"<br> // files[0].name = "file.ext"<br> // files[0].path = "path/to/my/file.ext" </li> 
  <li> files = s3FindFiles bucket: "my-bucket", path: "path/to/", glob: "my/file.ext"<br> // files[0].name = "file.ext"<br> // files[0].path = "my/file.ext" </li> 
  <li> files = s3FindFiles bucket: "my-bucket", path: "path/to/my/", glob: "file.ext"<br> // files[0].name = "file.ext"<br> // files[0].path = "file.ext" </li> 
 </ul> 
 <p></p> 
 <p> List every file in the bucket: </p>
 <ul> 
  <li>s3FindFiles bucket: "my-bucket", glob: "**", onlyFiles: true</li> 
 </ul> 
 <p></p> 
 <p> The return format is identical to that of the findFiles step. This will return an array of FileWrapper instances with the following properties: </p>
 <ul> 
  <li>name: the filename portion of the path (for "path/to/my/file.ext", this would be "file.ext")</li> 
  <li>path: the full path of the file, <i>relative</i> to the path specified (for path="path/to/", this property of the file "path/to/my/file.ext" would be "my/file.ext")</li> 
  <li>directory: true if this is a directory; false otherwise</li> 
  <li>length: the length of the file (this is always "0" for directories)</li> 
  <li>lastModified: the last modification timestamp, in milliseconds since the Unix epoch (this is always "0" for directories)</li> 
 </ul> When used in a string context, a FileWrapper object returns the value of its path. 
 <p></p> 
</div></div>
<ul><li><code>bucket</code>
<div><div>
  This is the bucket to use. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pathStyleAccessEnabled</code> (optional)
<div><div>
  Enabled/Disable Path-style Access for AWS S3. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>payloadSigningEnabled</code> (optional)
<div><div>
  Enabled/Disable Payload Signing for AWS S3. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>glob</code> (optional)
<div><div> 
 <p> This is the glob to use to match files/folders. You may use a full file name/path (for example "path/to/file.ext"), but you may also use a glob (for example, "path/t*/file.*"). </p> 
 <p> If left blank, this will perform the equivalent function of "*". </p> 
 <p> To list absolutely everything, use "**". </p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>onlyFiles</code> (optional)
<div><div>
  Set this to true to only return actual files. Otherwise, by default, this will return both files and folders. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>path</code> (optional)
<div><div>
  This is the path inside the bucket to use as the root of the search. 
 <i>Do not begin with a leading "/".</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +s3Upload+: Copy file to S3
++++
<div><div> 
 <p> Upload a file/folder from the workspace to an S3 bucket. If the file parameter denotes a directory, then the complete directory (including all subfolders) will be uploaded. </p> 
</div></div>
<ul><li><code>bucket</code>
<div><div>
  This is the bucket to use. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pathStyleAccessEnabled</code> (optional)
<div><div>
  Enabled/Disable Path-style Access for AWS S3. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>payloadSigningEnabled</code> (optional)
<div><div>
  Enabled/Disable Payload Signing for AWS S3. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>acl</code> (optional)
<div><div> 
 <p> Canned ACL to add to the upload request. </p>
 <ul> 
  <li>Private : Specifies the owner is granted Full Control. No one else has access rights. This is the default access control policy for any new buckets or objects.</li> 
  <li>PublicRead : Specifies the owner is granted Full Control and to the All Users group grantee is granted Read access.</li> 
  <li>PublicReadWrite: Specifies the owner is granted Full Control and to the All Users group grantee is granted Read and Write access.</li> 
  <li>AuthenticatedRead: Specifies the owner is granted Full Control and to the Authenticated Users group grantee is granted Read access.</li> 
  <li>LogDeliveryWrite: Specifies the owner is granted Full Control and to the Log Delivery group grantee is granted Write access.</li> 
  <li>BucketOwnerRead: Specifies the owner of the bucket, but not necessarily the same as the owner of the object, is granted Read access.</li> 
  <li>BucketOwnerFullControl: Specifies the owner of the bucket, but not necessarily the same as the owner of the object, is granted Full Control.</li> 
  <li>AwsExecRead: Specifies the owner is granted Full Control and Amazon EC2 is granted {@link Permission#Read} access to GET an Amazon Machine Image (AMI) bundle from Amazon S3.</li> 
 </ul> 
 <p></p> 
</div></div>

<ul><li><b>Values:</b> <code>Private</code>, <code>PublicRead</code>, <code>PublicReadWrite</code>, <code>AuthenticatedRead</code>, <code>LogDeliveryWrite</code>, <code>BucketOwnerRead</code>, <code>BucketOwnerFullControl</code>, <code>AwsExecRead</code></li></ul></li>
<li><code>cacheControl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>contentType</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludePathPattern</code> (optional)
<div><div>
  This is the pattern to use to exclude files 
 <i>Sample : "*.svg"</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>file</code> (optional)
<div><div>
  This is the local file to upload from the workspace. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>includePathPattern</code> (optional)
<div><div>
  This is the pattern to use to find files to push to S3 
 <i>Sample : "dist/**"</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>kmsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>metadatas</code> (optional)
<div><div>
  Metadatas to add to push file. Multiple metadatas must be separated with a ';' and name and value separated by a ':'. 
 <i>Sample : "Content-Type:image/svg+xml;Another:AnotherValue"</i> 
</div></div>

<ul><b>Array/List</b><br/>
<li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>path</code> (optional)
<div><div>
  This is the path inside the bucket to use. 
 <i>Do not begin with a leading "/".</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>workingDir</code> (optional)
<div><div>
  Working directories for s3Upload plugin 
 <i>Sample : "dist"</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +setAccountAlias+: Set the AWS account alias
++++
<div><div> 
 <p> The <code>setAccountAlias</code> step set the given name as AWS account alias. </p> 
</div></div>
<ul><li><code>name</code>
<div><div>
  Name to use as account alias. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +snsPublish+: Publish notification to SNS
++++
<ul><li><code>topicArn</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>subject</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>message</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +updateIdP+: Update thirdparty Identity Provider
++++
<ul><li><code>name</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>metadata</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +updateTrustPolicy+: Update trust policy of IAM roles
++++
<ul><li><code>roleName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>policyFile</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +withAWS+: set AWS settings for nested block
++++
<div><div> 
 <p> The <code>withAWS</code> step provides authorization for the nested steps. You can provide region and profile information or let Jenkins assume a role in another or the same AWS account. You can mix all parameters in one <code>withAWS</code> block. </p> 
</div></div>
<ul><li><code>credentials</code> (optional)
<div><div>
  Use standard Jenkins UsernamePassword credentials. Note: the username should be your Access Key ID, and the password should be the Secret Access Key. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>endpointUrl</code> (optional)
<div><div>
  The AWS endpoint-url. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>externalId</code> (optional)
<div><div>
  (optional) The external ID. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>federatedUserId</code> (optional)
<div><div>
  (optional) The federated user ID. It generates a set of temporary credentials and allows you to push a federated user id into cloud trail for auditing. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>policy</code> (optional)
<div><div>
  (optional) An additional policy that is to be combined with the policy associated with the role. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>profile</code> (optional)
<div><div>
  Use this profile information from ~/.aws/config. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>region</code> (optional)
<div><div>
  The AWS region. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>role</code> (optional)
<div><div>
  Assume role information (
 <i>Role Account</i> is optional; it uses current account as default, 
 <i>External ID</i> is optional). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>roleAccount</code> (optional)
<div><div>
  (optional) The account to use. This uses current account by default. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
