---
layout: pipelinesteps
title: "流水线: Bamboo 步骤"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== 流水线: Bamboo 步骤

plugin:pipeline-bamboo[在插件索引中查看此插件]

=== +buildBamboo+: 构建 Bamboo
++++
<div><div> 
 <p> The <b>buildBamboo</b> step provides a way to invoke Bamboo plans from within a Jenkinsfile. </p> 
</div></div>
<ul><li><code>projectKey</code>
<div><div>
  (required) The project key of your build plan. For example, if the build plan is "MYPROJECT-MYPLAN", this would be "MYPROJECT". 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>planKey</code>
<div><div>
  (required) The plan key of your build plan. For example, if the build plan is "MYPROJECT-MYPLAN", this would be "MYPLAN". 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>serverAddress</code>
<div><div>
  (required) The hostname or IP of the Bamboo server. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>username</code>
<div><div>
  (required) The username to use to authenticate to Bamboo. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>password</code>
<div><div>
  (required) The Bamboo server password. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>checkInterval</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>params</code> (optional)
<ul><code>java.lang.Object></code>
</ul></li>
<li><code>propagate</code> (optional)
<div><div>
  (optional) Boolean. Whether or not failures halt the pipeline. Default: True 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
