---
layout: pipelinesteps
title: "Protecode SC"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Protecode SC

plugin:protecode-sc[在插件索引中查看此插件]

=== +protecodesc+: Protecode SC
++++
<ul><li><code>credentialsId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>protecodeScGroup</code> (optional)
<div><div>
  Specify the Protecode SC Group ID where the artifacts should be uploaded to. 
 <p> Group ID can be found from the Protecode SC service by looking at the URL when browsing an individual group: <code>https://protecode-sc.mydomain.com/group/<strong>1234</strong>/</code> or with Groups API <code>https://protecode-sc.mydomain.com/api/groups/</code>. </p> 
 <br> 
 <i> Please notice that this value should be a number, not the name or the path to the group.</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>convertToSummary</code> (optional)
<div><div>
  The summary can be shown using 
 <a href="https://wiki.jenkins-ci.org/display/JENKINS/Summary+Display+Plugin" rel="nofollow">Summary Display Jenkins Plugin.</a> 
 <br> The report file name to publish is 
 <b><code>protecodesc.xml</code></b>. 
 <br>
 <br> If you wish to see only the latest results in the summary, you can run a "shell command" build step before the Protecode SC build step: "rm -rf reports". You can find the mentioned build step in the list of possible build steps on the build configuration page. Please notice that this action is irreversible. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>directoryToScan</code> (optional)
<div><div>
  Please specify the directory in the workspace you wish to scan. 
 <br>
 <br> If you wish to use an absolute path put '/' at the beginning of the path, this will cause the plugin to not try to find the folder from the build workspace. 
 <i>Please notice that it is possible to upload massive amounts of files if this option is set to absolute path and the 'Include subdirectories' is enabled.</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failIfVulns</code> (optional)
<div><div>
  Trigger build failure if Protecode SC finds vulnerabilities from the scanned files. The build will always fail if the connection or api calls to Protecode SC returned any errors. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>includeSubdirectories</code> (optional)
<div><div>
  Also include subdirectories of the directory from which the build attempts to find files to scan. 
 <br>
 <br> 
 <i>Please notice that if this is selected, it is possible to accidentally upload massive amounts of files. </i> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>pattern</code> (optional)
<div><div>
  Here you can provide a regular expression to include only certain files. The format used in this option is the default java Pattern format: https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html 
 <br>
 <br> 
 <i>Leave blank to include all found files.</i> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>scanTimeout</code> (optional)
<div><div>
  Timeout for the scan. If this timeout is exceeded the plugin will not try to get further results from Protecode SC. If a comprehensive timeout for the build is needed, it is suggested to use the 
 <a href="https://plugins.jenkins.io/build-timeout" rel="nofollow">Build Timeout Plugin</a>. 
</div></div>

<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul>


++++
