---
layout: pipelinesteps
title: "通过CIFS发布"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== 通过CIFS发布

plugin:publish-over-cifs[在插件索引中查看此插件]

=== +cifsPublisher+: 将构建工件发送到Windows共享
++++
<div><div>
 Send build artifacts to a windows share
</div></div>
<ul><li><code>alwaysPublishFromMaster</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>continueOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>masterNodeName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>paramPublish</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'BapFtpParamPublish'</code></li>
<ul><li><code>parameterName</code>
<div><div>
  The name of the parameter or environment variable that will contain the expression for matching the labels. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'BapSshParamPublish'</code></li>
<ul><li><code>parameterName</code>
<div><div>
  The name of the parameter or environment variable that will contain the expression for matching the labels. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>publishers</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>configName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>verbose</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>transfers</code>
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>sourceFiles</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludes</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>remoteDirectory</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>removePrefix</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>remoteDirectorySDF</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>flatten</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>cleanRemote</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>noDefaultExcludes</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>makeEmptyDirs</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>patternSeparator</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>useWorkspaceInPromotion</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>usePromotionTimestamp</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>retry</code>
<ul><b>Nested Object</b>
<li><code>retries</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>retryDelay</code>
<ul><li><b>Type:</b> <code>long</code></li></ul></li>
</ul></li>
<li><code>label</code>
<ul><b>Nested Object</b>
<li><code>label</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul></li>
</ul>


++++
