---
layout: pipelinesteps
title: "Pyenv Pipeline Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Pyenv Pipeline Plugin

plugin:pyenv-pipeline[View this plugin on the Plugins Index]

=== +pybat+: PyEnvVar Batch Script
++++
<ul><li><code>script</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>encoding</code> (optional)
<div><div>
  Encoding of standard output, if it is being captured. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>returnStatus</code> (optional)
<div><div>
  Normally, a script which exits with a nonzero status code will cause the step to fail with an exception. If this option is checked, the return value of the step will instead be the status code. You may then compare it to zero, for example. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>returnStdout</code> (optional)
<div><div>
  If checked, standard output from the task is returned as the step value as a 
 <code>String</code>, rather than being printed to the build log. (Standard error, if any, will still be printed to the log.) You will often want to call 
 <code>.trim()</code> on the result to strip off a trailing newline. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +pysh+: PyEnvVar Shell Script
++++
<ul><li><code>script</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>encoding</code> (optional)
<div><div>
  Encoding of standard output, if it is being captured. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>returnStatus</code> (optional)
<div><div>
  Normally, a script which exits with a nonzero status code will cause the step to fail with an exception. If this option is checked, the return value of the step will instead be the status code. You may then compare it to zero, for example. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>returnStdout</code> (optional)
<div><div>
  If checked, standard output from the task is returned as the step value as a 
 <code>String</code>, rather than being printed to the build log. (Standard error, if any, will still be printed to the log.) You will often want to call 
 <code>.trim()</code> on the result to strip off a trailing newline. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
=== +withPythonEnv+: Code Block
++++
<div><p> Wraps a block in a Python virtualenv. Any <code>pysh</code> or <code>pybat</code> steps executed within the block, are executed using the virtualenv specified </p> 
<p>Example:</p> 
<pre><code>withPythonEnv('python3') {
    pysh 'python --version'
}</code></pre> 
<p> The argument supplied to <code>withPythonEnv</code> is the name of the virtualenv to make available to any <code>pysh</code> or <code>pybat</code> steps called within the block. </p> 
<p> Initially, <code>withPythonEnv</code> tries to match the string passed to it to a tool name. Currently, this means examining the installed tools for ShiningPanada. If the string matches an installed ShiningPanda Python tool instance, the virtualenv within that block is generated from that ShiningPanda tool. </p> 
<p> Otherwise, the text is treated "as-is". You can pass "python" to use the default Python installation of the node that the job runs on, or specify an executable path. </p></div>
<ul><li><code>pythonInstallation</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
