---
layout: pipelinesteps
title: "R Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== R Plugin

plugin:r[View this plugin on the Plugins Index]

=== +r+: Execute R script
++++
<ul><li><code>command</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>encoding</code> (optional)
<div><div>
  Encoding of standard output, if it is being captured. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>returnStatus</code> (optional)
<div><div>
  Normally, a script which exits with a nonzero status code will cause the step to fail with an exception. If this option is checked, the return value of the step will instead be the status code. You may then compare it to zero, for example. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>returnStdout</code> (optional)
<div><div>
  If checked, standard output from the task is returned as the step value as a 
 <code>String</code>, rather than being printed to the build log. (Standard error, if any, will still be printed to the log.) You will often want to call 
 <code>.trim()</code> on the result to strip off a trailing newline. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
