---
layout: pipelinesteps
title: "Rich Text Publisher Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Rich Text Publisher Plugin

plugin:rich-text-publisher-plugin[View this plugin on the Plugins Index]

=== +rtp+: Publish rich text message
++++
<ul><li><code>abortedAsStable</code> (optional)
<div><div>
  When selected, the same text block is used for stable and aborted builds. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>abortedText</code> (optional)
<div><p> Specify rich text to be published on build and job summary pages for aborted builds. This text will be used only if "The same text for aborted builds as for stable" checkbox is not selected. Build parameters may be put in <code>${PARAM_NAME}</code> format. Global environment variable values may be put in <code>${ENV:VAR_NAME}</code> format. </p> 
<p> Content of specified files may be also added to summary page. Use <code>${FILE:path/to/file.txt}</code> to put entire file contents. Use <code>${FILE_SL:path/to/file.txt}</code> to put file contents as single line (all CR and LF symbols are skipped). </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failedAsStable</code> (optional)
<div><div>
  When selected, the same text block is used for stable and failed builds. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>failedText</code> (optional)
<div><p> Specify rich text to be published on build and job summary pages for failed builds. This text will be used only if "The same text for failed builds as for stable" checkbox is not selected. Build parameters may be put in <code>${PARAM_NAME}</code> format. Global environment variable values may be put in <code>${ENV:VAR_NAME}</code> format. </p> 
<p> Content of specified files may be also added to summary page. Use <code>${FILE:path/to/file.txt}</code> to put entire file contents. Use <code>${FILE_SL:path/to/file.txt}</code> to put file contents as single line (all CR and LF symbols are skipped). </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>nullAction</code> (optional)
<div><p> Select what happens in the case that the buildstate is null or unknown </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>parserName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>stableText</code> (optional)
<div><p> Specify rich text to be published on build and job summary pages for stable and (if corresponding checkboxes are selected) for unstable and failed builds. Build parameters may be put in <code>${PARAM_NAME}</code> format. Global environment variable values may be put in <code>${ENV:VAR_NAME}</code> format. </p> 
<p> Content of specified files may be also added to summary page. Use <code>${FILE:path/to/file.txt}</code> to put entire file contents. Use <code>${FILE_SL:path/to/file.txt}</code> to put file contents as single line (all CR and LF symbols are skipped). </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>unstableAsStable</code> (optional)
<div><div>
  When selected, the same text block is used for stable and unstable builds. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>unstableText</code> (optional)
<div><p> Specify rich text to be published on build anyd job summary pages for unstable builds. This text will be used only if "The same text for unstable builds as for stable" checkbox is not selected. Build parameters may be put in <code>${PARAM_NAME}</code> format. Global environment variable values may be put in <code>${ENV:VAR_NAME}</code> format. </p> 
<p> Content of specified files may be also added to summary page. Use <code>${FILE:path/to/file.txt}</code> to put entire file contents. Use <code>${FILE_SL:path/to/file.txt}</code> to put file contents as single line (all CR and LF symbols are skipped). </p></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
