---
layout: pipelinesteps
title: "RocketChat 通知程序"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== RocketChat通知程序

plugin:rocketchatnotifier[在插件索引中查看此插件]

=== +rocketSend+: 发送RocketChat消息
++++
<div><div>
  Simple step for sending a RocketChat message to specified channel.
 <br> Use the advanced settings to override the RocketChat Plugin global configuration to include: 
 <code>channel</code>.
 <br> Please see the RocketChat Plugin global configuration for more details on the fields. Usage Example:
 <br> 
 <code> rocketSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (&lt;${env.BUILD_URL}|Open&gt;)" </code> 
</div></div>
<ul><li><code>message</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>attachments</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>title</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>audioUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authorIcon</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authorName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>collapsed</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>color</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>imageUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>messageLink</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>text</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>thumbUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>titleLink</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>titleLinkDownload</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ts</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>videoUrl</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>avatar</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>channel</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>emoji</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>failOnError</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>rawMessage</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>webhookToken</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>webhookTokenCredentialId</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
