---
layout: pipelinesteps
title: "S3 publisher plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== S3 publisher plugin

plugin:s3[View this plugin on the Plugins Index]

=== +s3CopyArtifact+: S3 Copy Artifact
++++
<ul><li><code>projectName</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildSelector</code>
<ul><b>Nested Choice of Objects</b>
<li><code>downstream</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>lastCompleted</code></li>
<ul></ul><li><code>$class: 'MultiJobBuildSelector'</code></li>
<ul></ul><li><code>buildParameter</code></li>
<ul><li><code>parameterName</code>
<div><div>
  Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p> You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>permalink</code></li>
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PromotedBuildSelector'</code></li>
<ul><li><code>level</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul><li><code>latestSavedBuild</code></li>
<ul></ul><li><code>specific</code></li>
<ul><li><code>buildNumber</code>
<div><div>
  While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). The display name of a build and permalinks (e.g. "lastSuccessfulBuild", "lastBuild"...) can be used as well. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>lastSuccessful</code></li>
<ul><li><code>stable</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>upstream</code></li>
<ul><li><code>fallbackToLastSuccessful</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>upstreamFilterStrategy</code>
<div><div>
  Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System". 
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
<li><code>allowUpstreamDependencies</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>workspace</code></li>
<ul></ul></ul></li>
<li><code>filter</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludeFilter</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>target</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>flatten</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>optional</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
