---
layout: pipelinesteps
title: "SaltStack 插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== SaltStack 插件

plugin:saltstack[在插件索引中查看此插件]

=== +salt+: 发送消息给Salt API
++++
<ul><li><code>servername</code>
<div><div>
  Salt servername. In the form: https://host.domain:8000
 <br> The Test Connection process is run from the Jenkins master. If the build is localized to an agent, and the servername is specific to that agent, then Test Connection will likely fail, while the actual build may succeed. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>authtype</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>clientInterface</code>
<ul><b>Nested Choice of Objects</b>
<li><code>hook</code></li>
<ul><li><code>post</code>
<div><div>
  Publish JSON object as 'post' data, see 
 <a href="https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Webhook.POST" rel="nofollow">upstream documentation</a>. . Paramaterized Build variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>tag</code>
<div><div>
  Specify salt event tag for message. The event tag is prefixed with salt/netapi/hook, see 
 <a href="https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Webhook" rel="nofollow">upstream documentation</a>. Paramaterized variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>batch</code></li>
<ul><li><code>function</code>
<div><div>
  Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>arguments</code>
<div><div>
  Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br> Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>batchSize</code>
<div><div>
  Specify salt batch size. Example: 10 or 10% 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>target</code>
<div><div>
  Specify salt target as defined in the 
 <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targettype</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>local</code></li>
<ul><li><code>function</code>
<div><div>
  Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>arguments</code>
<div><div>
  Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br> Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>target</code>
<div><div>
  Specify salt target as defined in the 
 <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targettype</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>blockbuild</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>jobPollTime</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>minionTimeout</code> (optional)
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul><li><code>subset</code></li>
<ul><li><code>function</code>
<div><div>
  Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>arguments</code>
<div><div>
  Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br> Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>subset</code>
<div><div>
  Execute the routine on a random subset of the targeted minions. Paramaterized variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>target</code>
<div><div>
  Specify salt target as defined in the 
 <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>targettype</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>runner</code></li>
<ul><li><code>function</code>
<div><div>
  Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>arguments</code>
<div><div>
  Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>mods</code>
<div><div>
  Specify runner mods value. Used in state.orchestrate function to specify the name of the orchestrate module
 <br> Paramaterized Build variables should be specified in the format {{VARNAME}} 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>pillarvalue</code>
<div><div>
  Specify runner pillar value. Used in state.orchestrate functions. Ex: {"key": "value"}
 <br> Paramaterized Build variables should be specified in the format {{VARNAME}} 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>saveEnvVar</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>saveFile</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>skipValidation</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
