---
layout: pipelinesteps
title: "Sonar Gerrit Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Sonar Gerrit Plugin

plugin:sonar-gerrit[View this plugin on the Plugins Index]

=== +sonarToGerrit+: Post SonarQube issues as Gerrit comments
++++
<ul><li><code>authConfig</code> (optional)
<div><div> 
 <b>Override</b> HTTP credentials specified in Gerrit Trigger settings to be used for review posting 
</div></div>

<ul><b>Nested Object</b>
<li><code>password</code> (optional)
<div><div>
  This field will 
 <b>override</b> the HTTP password from Gerrit Trigger settings and will be used for plugin purposes only. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>username</code> (optional)
<div><div>
  This field will 
 <b>override</b> the HTTP username from Gerrit Trigger settings and will be used for plugin purposes only. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>category</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>changedLinesOnly</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>httpPassword</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>httpUsername</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>inspectionConfig</code> (optional)
<div><div>
  Configure accordance of SonarQube report(s) and project or module(s) path(s) 
</div></div>

<ul><b>Nested Object</b>
<li><code>autoMatch</code> (optional)
<div><div>
  Allow plugin to match inspection and review system file names automatically (useful for projects with several nested modules) 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>baseConfig</code> (optional)
<div><div>
  Provides settings for the whole project 
</div></div>

<ul><b>Nested Object</b>
<li><code>autoMatch</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>projectPath</code> (optional)
<div><div>
  Provides module prefix for a file path for multi-module projects 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sonarReportPath</code> (optional)
<div><div>
  Path to SonarQube report on Jenkins server. Default value is "target/sonar/sonar-report.json" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>serverURL</code> (optional)
<div><div>
  URL of the SonarQube instance used for static code analysis 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>subJobConfigs</code> (optional)
<div><div>
  Provides separate settings for each module 
</div></div>

<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>autoMatch</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>projectPath</code> (optional)
<div><div>
  Provides module prefix for a file path for multi-module projects 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sonarReportPath</code> (optional)
<div><div>
  Path to SonarQube report on Jenkins server. Default value is "target/sonar/sonar-report.json" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>type</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>issueComment</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>issuesNotification</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>issuesScore</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>newIssuesOnly</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>noIssuesNotification</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>noIssuesScore</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>noIssuesToPostText</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>notificationConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>commentedIssuesNotificationRecipient</code> (optional)
<div><div>
  This setting allow to determine who will be notified in case there are 
 <b>several SonarQube issues matching filter settings</b> found in particular commit. 
 <br> An e-mails sent to recipients will contain review information: title of review and list of comments (issues). Recipient settings: 
 <br> 
 <br> * None - No one;
 <br> * Owner - Owner (i.e. author of the commit);
 <br> * Owner and Reviewers - Owner (i.e. author of the commit) and all Reviewers (people who was added to reviewer list of the commit);
 <br> * All - everyone in the project list. 
 <br> 
 <br> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>negativeScoreNotificationRecipient</code> (optional)
<div><div>
  This setting allow to determine who will be notified in case if the build got a negative score due to issues matching score filter settings are found. An e-mails sent to recipients will contain review information: title of review and list of comments (issues). Recipient settings: 
 <br> 
 <br> * None - No one;
 <br> * Owner - Owner (i.e. author of the commit);
 <br> * Owner and Reviewers - Owner (i.e. author of the commit) and all Reviewers (people who was added to reviewer list of the commit);
 <br> * All - everyone in the project list. 
 <br> 
 <br> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>noIssuesNotificationRecipient</code> (optional)
<div><div>
  This setting allow to determine who will be notified in case there are 
 <b>no SonarQube issues matching filter settings</b> found in particular commit. 
 <br> An e-mails sent to recipients will contain review information: title of review. Recipient settings: 
 <br> 
 <br> * None - No one;
 <br> * Owner - Owner (i.e. author of the commit);
 <br> * Owner and Reviewers - Owner (i.e. author of the commit) and all Reviewers (people who was added to reviewer list of the commit);
 <br> * All - everyone in the project list. 
 <br> 
 <br> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>overrideCredentials</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>path</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>postScore</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>projectPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>reviewConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>issueCommentTemplate</code> (optional)
<div><div>
  This text will appear as comment for a line with SonarQube issue in Gerrit review. 
 <br> There are some tags available: 
 <br> 
 <br> * &lt;key&gt; - will be replaced with 
 <b>issue key</b>; 
 <br> * &lt;component&gt; - will be replaced with 
 <b>issue component info</b>; 
 <br> * &lt;message&gt; - will be replaced with 
 <b>issue message</b>; 
 <br> * &lt;severity&gt; - will be replaced with 
 <b>issue severity</b>; 
 <br> * &lt;rule&gt; - will be replaced with 
 <b>issue rule name</b>; 
 <br> * &lt;rule_url&gt; - will be replaced with link to 
 <b>rule description on SonarQube</b> if SonarQube URL is provided in SonarQube settings section or 
 <b>rule name</b> if URL is not provided; 
 <br> * &lt;status&gt; - will be replaced with 
 <b>issue status</b>; 
 <br> * &lt;creation_date&gt; - will be replaced with 
 <b>issue creation date</b>. 
 <br> 
 <br> Please note that only 
 <b>filtered</b> by severity level issues and their counts will be shown in report. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>issueFilterConfig</code> (optional)
<div><div>
  Issue filter to specify issues to be 
 <b>commented</b> in Gerrit 
</div></div>

<ul><b>Nested Object</b>
<li><code>changedLinesOnly</code> (optional)
<div><div>
  Only 
 <b>changed in current commit</b> lines to be commented by Gerrit when checked. Modified files to be commented with 
 <b>all issues</b> if this control unchecked. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>newIssuesOnly</code> (optional)
<div><div>
  Only 
 <b>new</b> SonarQube issues to be commented in Gerrit when checked. Modified files to be commented with 
 <b>all</b> corresponding issues when unchecked. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>severity</code> (optional)
<div><div>
  Minimum level of SonarQube severity to be reported to Gerrit. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>noIssuesTitleTemplate</code> (optional)
<div><div>
  This text will appear as title of Gerrit review in case when 
 <b>no issues matching filter settings</b> found. 
 <br> There are some tags available: 
 <br> 
 <br> * &lt;info_count&gt; - will be replaced with count of issues having 
 <b>INFO</b> severity level; 
 <br> * &lt;minor_count&gt; - will be replaced with count of issues having 
 <b>MINOR</b> severity level; 
 <br> * &lt;major_count&gt; - will be replaced with count of issues having 
 <b>MAJOR</b> severity level; 
 <br> * &lt;critical_count&gt; - will be replaced with count of issues having 
 <b>CRITICAL</b> severity level; 
 <br> * &lt;blocker_count&gt; - will be replaced with count of issues having 
 <b>BLOCKER</b> severity level; 
 <br> * &lt;min_minor_count&gt; - will be replaced with count of issues having 
 <b>MINOR</b> severity level 
 <b>or higher</b>; 
 <br> * &lt;min_major_count&gt; - will be replaced with count of issues having 
 <b>MAJOR</b> severity level 
 <b>or higher</b>; 
 <br> * &lt;min_critical_count&gt; - will be replaced with count of issues having 
 <b>CRITICAL</b> severity level 
 <b>or higher</b>; 
 <br> * &lt;total_count&gt; - will be replaced with 
 <b>total count</b> of issues. 
 <br> Please note that only 
 <b>filtered</b> by severity level issues and their counts will be shown in report. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>someIssuesTitleTemplate</code> (optional)
<div><div>
  This text will appear as title of Gerrit review in case when there are several issues matching filter settings found. 
 <br> There are some tags available: 
 <br> 
 <br> * &lt;info_count&gt; - will be replaced with count of issues having 
 <b>INFO</b> severity level; 
 <br> * &lt;minor_count&gt; - will be replaced with count of issues having 
 <b>MINOR</b> severity level; 
 <br> * &lt;major_count&gt; - will be replaced with count of issues having 
 <b>MAJOR</b> severity level; 
 <br> * &lt;critical_count&gt; - will be replaced with count of issues having 
 <b>CRITICAL</b> severity level; 
 <br> * &lt;blocker_count&gt; - will be replaced with count of issues having 
 <b>BLOCKER</b> severity level; 
 <br> * &lt;min_minor_count&gt; - will be replaced with count of issues having 
 <b>MINOR</b> severity level 
 <b>or higher</b>; 
 <br> * &lt;min_major_count&gt; - will be replaced with count of issues having 
 <b>MAJOR</b> severity level 
 <b>or higher</b>; 
 <br> * &lt;min_critical_count&gt; - will be replaced with count of issues having 
 <b>CRITICAL</b> severity level 
 <b>or higher</b>; 
 <br> * &lt;total_count&gt; - will be replaced with 
 <b>total count</b> of issues. 
 <br> Please note that only 
 <b>filtered</b> by severity level issues and their counts will be shown in report. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>scoreConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>category</code> (optional)
<div><div>
  This field describes under what category score will appear in Gerrit. This category should match one of existent Gerrit categories. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>issueFilterConfig</code> (optional)
<div><div>
  Issue filter to specify issues to affect 
 <b>score</b> in Gerrit 
</div></div>

<ul><b>Nested Object</b>
<li><code>changedLinesOnly</code> (optional)
<div><div>
  Only 
 <b>changed in current commit</b> lines to be commented by Gerrit when checked. Modified files to be commented with 
 <b>all issues</b> if this control unchecked. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>newIssuesOnly</code> (optional)
<div><div>
  Only 
 <b>new</b> SonarQube issues to be commented in Gerrit when checked. Modified files to be commented with 
 <b>all</b> corresponding issues when unchecked. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>severity</code> (optional)
<div><div>
  Minimum level of SonarQube severity to be reported to Gerrit. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>issuesScore</code> (optional)
<div><div>
  Score to be posted to Gerrit in case when there are SonarQube violations found 
</div></div>

<ul><li><b>Type:</b> <code>int</code></li></ul></li>
<li><code>noIssuesScore</code> (optional)
<div><div>
  Score to be posted to Gerrit in case when there are no SonarQube violations found 
</div></div>

<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul></li>
<li><code>severity</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>someIssuesToPostText</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sonarURL</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>subJobConfigs</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>autoMatch</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>projectPath</code> (optional)
<div><div>
  Provides module prefix for a file path for multi-module projects 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>sonarReportPath</code> (optional)
<div><div>
  Path to SonarQube report on Jenkins server. Default value is "target/sonar/sonar-report.json" 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
</ul>


++++
