---
layout: pipelinesteps
title: "存储通知程序"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== 存储通知程序

plugin:stashNotifier[在插件索引中查看此插件]

=== +notifyBitbucket+: 通知存储实例
++++
<ul><li><code>stashServerBaseUrl</code>
<div><div>
  The base URL of the Stash server to notify. Examples are: 
 <ul> 
  <li>http://localhost:7990, or</li> 
  <li>http://my.company.intranet/stash.</li> 
 </ul> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>credentialsId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>ignoreUnverifiedSSLPeer</code>
<div>Check this if you need to connect by HTTPS to a Stash server that uses an invalid or self-signed SSL certificate</div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>commitSha1</code>
<div><div>
  Enter a 40-digit SHA1 commit id or a Jenkins variable prefixed with '$' (e. g. 
 <em>$GIT_COMMIT</em>) when you want the notification to be attached to a specific commit in Stash. If left empty, Jenkins will use the commit that was built by the Git plugin. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>includeBuildNumberInKey</code>
<div><div> 
 <p> Check this if you want results of repeated builds of the same commit to show up in Stash as a list of builds. If unchecked, Stash will only display the latest build result. </p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>projectKey</code>
<div><div>
  If not empty, this key will be used instead of automatically configured project key 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>prependParentProjectKey</code>
<div><div>
  Whether to prepend parent project while forming notify key 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>disableInprogressNotification</code>
<div><div>
  Disable sending pre-build notification to Stash (Bitbucket) 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>considerUnstableAsSuccess</code>
<div><div>
  Consider unstable builds as success, besides the test errors. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul>


++++
