---
layout: pipelinesteps
title: "Windows Azure存储插件"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== Windows Azure存储插件

plugin:windows-azure-storage[在插件索引中查看此插件]

=== +azureDownload+: 从Azure存储下载
++++
<ul><li><code>storageCredentialId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>downloadType</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>buildSelector</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>downstream</code></li>
<ul><li><code>upstreamProjectName</code>
<div><div> 
 <p> Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions. </p> 
 <p> Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them. </p> 
 <p> Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects). </p>
 <dl> 
  <dt>
   AbstractProject based projects:
  </dt> 
  <dd>
   Freestyle projects
  </dd> 
  <dd>
   Multi-configuration projects
  </dd> 
  <dd>
   Maven projects
  </dd> 
  <dt>
   Non AbstractProject based projects:
  </dt> 
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd> 
 </dl> 
 <p></p> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>upstreamBuildNumber</code>
<div><div>
  The number of the build to find its downstream build. You can also specify display names. You can use variable expressions. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>lastCompleted</code></li>
<ul></ul><li><code>$class: 'MultiJobBuildSelector'</code></li>
<ul></ul><li><code>buildParameter</code></li>
<ul><li><code>parameterName</code>
<div><div>
  Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p> You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin. </p>
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>permalink</code></li>
<ul><li><code>id</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>$class: 'PromotedBuildSelector'</code></li>
<ul><li><code>level</code>
<ul><li><b>Type:</b> <code>int</code></li></ul></li>
</ul><li><code>latestSavedBuild</code></li>
<ul></ul><li><code>specific</code></li>
<ul><li><code>buildNumber</code>
<div><div>
  While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). The display name of a build and permalinks (e.g. "lastSuccessfulBuild", "lastBuild"...) can be used as well. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul><li><code>lastSuccessful</code></li>
<ul><li><code>stable</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>upstream</code></li>
<ul><li><code>fallbackToLastSuccessful</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>upstreamFilterStrategy</code>
<div><div>
  Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System". 
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
<li><code>allowUpstreamDependencies</code>
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul><li><code>workspace</code></li>
<ul></ul></ul></li>
<li><code>containerName</code> (optional)
<div><div>
  Enter a storage container name. 
 <br> Environment variables can also be referenced. 
 <br> For example: ${JOB_NAME} 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>deleteFromAzureAfterDownload</code> (optional)
<div><div>
  If checked, the file copy on Azure will be removed after it's downloaded to local. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>downloadDirLoc</code> (optional)
<div><div>
  Enter a download path. If not specified, the files will be downloaded into the job's workspace.
 <br> Environment variables can also be referenced, for example: ${JOB_NAME} If "Flatten Directories" is checked, this directory will contain all outputs. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>excludeFilesPattern</code> (optional)
<div><div>
  Enter a pattern of blobs to exclude from the download. Ant fileset syntax. Leaving blank will download the entire container. Environment variables can also be referenced. 
 <br> For example: ${JOB_NAME} 
 <br> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>fileShare</code> (optional)
<div><div>
  Enter a Azure File Storage Share name. 
 <br> Environment variables can also be referenced. 
 <br> For example: ${JOB_NAME} 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>flattenDirectories</code> (optional)
<div><div>
  If checked, all files specified for download will be flattened to the single download directory. If two files are named the same in different directories, only one will remain. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>includeArchiveZips</code> (optional)
<div><div>
  The archive zip files generated (archive.zip in the root of the container/virtual path) are typically excluded from download. Check this to enable downloading of the archive zip. 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>includeFilesPattern</code> (optional)
<div><div>
  Enter a pattern of blobs to download. Ant fileset syntax. Environment variables can also be referenced. 
 <br> For example: ${JOB_NAME} 
 <br> 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>projectName</code> (optional)
<div><div>
  The name of the project to download the managed artifact from. 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
=== +azureUpload+: Upload artifacts to Microsoft Azure Storage
++++
<ul><li><code>storageCredentialId</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>filesPath</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>storageType</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>allowAnonymousAccess</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>blobProperties</code> (optional)
<ul><b>Nested Object</b>
<li><code>cacheControl</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>contentEncoding</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>contentLanguage</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>contentType</code>
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>detectContentType</code>
<div><div> 
 <p>Auto detect content type based on file content and file name if content type is not set.</p> 
 <p>This detection is provided by <a href="https://tika.apache.org" rel="nofollow">Apache Tika</a> and may not always be accurate.</p> 
</div></div>

<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
</ul></li>
<li><code>cleanUpContainerOrShare</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>containerName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>doNotFailIfArchivingReturnsNothing</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>doNotUploadIndividualFiles</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>doNotWaitForPreviousBuild</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>excludeFilesPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>fileShareName</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>metadata</code> (optional)
<ul><b>Array/List</b><br/>
<b>Nested Object</b>
<li><code>key</code>
<div><div>
  Metadata key for the files from this build. It will be prefixed by "x-ms-meta-" when uploaded to Azure. Can contain macros (e.g. environment variables). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
<li><code>value</code>
<div><div>
  Metadata value for the files from this build. Can contain macros (e.g. environment variables). 
</div></div>

<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul></li>
<li><code>pubAccessible</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>uploadArtifactsOnlyIfSuccessful</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>uploadZips</code> (optional)
<ul><li><b>Type:</b> <code>boolean</code></li></ul></li>
<li><code>virtualPath</code> (optional)
<ul><li><b>Type:</b> <code>String</code></li></ul></li>
</ul>


++++
