---
layout: developerextension
uneditable: true
---
:toc:
# DotCi 插件中定义的扩展点

plugin:DotCi[DotCi Plugin]

## 构建类型
+jenkinsdoc:DotCi:com.groupon.jenkins.dynamic.buildtype.BuildType[]+

_This extension point has no Javadoc documentation._

**Implementations:**

* plugin:DotCi-InstallPackages[DotCi安装包插件]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++**InstallPackagesBuild** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++dockercompose.+++<wbr/>+++**DockerComposeBuild** 
* plugin:DotCiInstallPackages[DotCiInstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++**InstallPackagesBuild** 


## DotCi扩展
+jenkinsdoc:DotCi:com.groupon.jenkins.extensions.DotCiExtension[]+

_This extension point has no Javadoc documentation._

**Implementations:**

* plugin:DotCi-DockerPublish[DotCi Docker发布插件]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++DockerComposeDotCi.+++<wbr/>+++**DockerPublishPlugin** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dynamic.+++<wbr/>+++build.+++<wbr/>+++plugins.+++<wbr/>+++artifacts.+++<wbr/>+++**ArtifactsPluginAdapter** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++plugins.+++<wbr/>+++**DotCiPluginAdapter** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dynamic.+++<wbr/>+++build.+++<wbr/>+++plugins.+++<wbr/>+++downstream.+++<wbr/>+++**DownstreamJobPlugin** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++notifications.+++<wbr/>+++**EmailNotifierBase** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++extensions.+++<wbr/>+++**GenericSimpleBuildStepPlugin** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++notifications.+++<wbr/>+++**PostBuildEmailNotifier** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++notifications.+++<wbr/>+++**PostBuildNotifier** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++notifications.+++<wbr/>+++**PusherEmailNotifier** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++plugins.+++<wbr/>+++**AnalysisCollectorPluginAdapter** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++plugins.+++<wbr/>+++**CheckStylePluginAdapter** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++plugins.+++<wbr/>+++**CoberturaPluginAdapter** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++plugins.+++<wbr/>+++**FindbugsPluginAdapter** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++notifiers.+++<wbr/>+++**HipchatNotifier** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++plugins.+++<wbr/>+++**JaCoCoPluginAdapter** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++plugins.+++<wbr/>+++**JunitPluginAdapter** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++plugins.+++<wbr/>+++**PmdPluginAdapter** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++plugins.+++<wbr/>+++**TapPluginAdapter** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++notifiers.+++<wbr/>+++**WebhookNotifier** 


## Github库行动
+jenkinsdoc:DotCi:com.groupon.jenkins.buildsetup.GithubRepoAction[]+

_This extension point has no Javadoc documentation._

**Implementations:**

* plugin:DotCi[DotCi 插件]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildsetup.+++<wbr/>+++**NewDotCiJobRepoAction** 
* plugin:DotCi[DotCi Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildsetup.+++<wbr/>+++**RefreshHookRepoAction** 


## 工作指标
+jenkinsdoc:DotCi:com.groupon.jenkins.dynamic.build.api.metrics.JobMetric[]+

_This extension point has no Javadoc documentation._

**Implementations:**

* plugin:DotCi[DotCi 插件]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dynamic.+++<wbr/>+++build.+++<wbr/>+++api.+++<wbr/>+++metrics.+++<wbr/>+++**BuildTimeMetric** 
* plugin:DotCi-Plugins-Starter-Pack[DotCi-Plugins-Starter-Pack Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++dotci.+++<wbr/>+++metrics.+++<wbr/>+++**CodeCoverageMetric** 


## 组织Gravatar图标
+jenkinsdoc:DotCi:com.groupon.jenkins.dynamic.organizationcontainer.OrganizationGravatarIcon[]+

_This extension point has no Javadoc documentation._

**Implementations:**

_(no known implementations)_

