---
layout: developerextension
uneditable: true
---
:toc:
# DotCi安装包插件中定义的扩展点
plugin:DotCiInstallPackages[otCi安装包插件]

## DotCi模板
+jenkinsdoc:DotCiInstallPackages:com.groupon.jenkins.buildtype.install_packages.template.DotCiTemplate[]+

_This extension point has no Javadoc documentation._

**Implementations:**

* plugin:DotCi-Fig-template[DotCi Fig模板插件]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Docker** 
* plugin:DotCi-Fig-template[DotCi Fig template Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Dockercompose** 
* plugin:DotCi-Fig-template[DotCi Fig template Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Fig** 
* plugin:DotCi-InstallPackages[DotCi InstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Base** 
* plugin:DotCi-InstallPackages[DotCi InstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Clojure** 
* plugin:DotCi-InstallPackages[DotCi InstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**GoLang** 
* plugin:DotCi-InstallPackages[DotCi InstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**InstallPackages** 
* plugin:DotCi-InstallPackages[DotCi InstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Java** 
* plugin:DotCi-InstallPackages[DotCi InstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Node** 
* plugin:DotCi-InstallPackages[DotCi InstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Ruby** 
* plugin:DotCiInstallPackages[DotCiInstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Base** 
* plugin:DotCiInstallPackages[DotCiInstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Clojure** 
* plugin:DotCiInstallPackages[DotCiInstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**GoLang** 
* plugin:DotCiInstallPackages[DotCiInstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**InstallPackages** 
* plugin:DotCiInstallPackages[DotCiInstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Java** 
* plugin:DotCiInstallPackages[DotCiInstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Node** 
* plugin:DotCiInstallPackages[DotCiInstallPackages Plugin]: com.+++<wbr/>+++groupon.+++<wbr/>+++jenkins.+++<wbr/>+++buildtype.+++<wbr/>+++install_packages.+++<wbr/>+++template.+++<wbr/>+++**Ruby** 

