---
layout: developerextension
uneditable: true
---
:toc:
# 项目继承插件中定义的扩展点

plugin:project-inheritance[项目继承插件]

## 构建视图扩展
+jenkinsdoc:project-inheritance:hudson.plugins.project_inheritance.projects.view.BuildViewExtension[]+

+++ This class servers as an extension point to render additional configuration+++ +++ entries for a build action.+++ +++
<p>+++ +++ It is useful to add additional properties to the build; regardless of+++ +++ whether or not this happens on a build or re-build.+++ +++ </p>
<p>+++ +++ The extension needs to implement a "value.groovy" or "value.jelly" which+++ +++ gets added into the form tag of the build submission. The name of this+++ +++ file can be overridden via+++ jenkinsdoc:#getValuePage()[] +++.+++ +++ </p>
<p>+++ +++ The fields will be put into the JSON form data inside the+++ ++++++ jenkinsdoc:StaplerRequest[] +++when the build is executed. For simplicity's sake,+++ +++ the method+++ jenkinsdoc:#onBuild(AbstractProject, StaplerRequest)[] +++will be called+++ +++ whenever a build is configured.+++ </p>


**Implementations:**

_(no known implementations)_


## 继承选择器
+jenkinsdoc:project-inheritance:hudson.plugins.project_inheritance.projects.inheritance.InheritanceSelector[]+

+++ Extension point that allows other plugins to decide how a particular type+++ +++ of object should be treated during inheritenace.+++ +++
<p>+++ +++ During inheritance, the settings of multiple projects need to be merged into+++ +++ one object, since the leaf project needs to respond to Jenkins as if it did+++ +++ not do any inheritance.+++ +++ </p>
<p>+++ +++ For example, a project might inherit multiple+++ jenkinsdoc:SCM[] +++objects, but it+++ +++ has to be ensured that only one is returned to Jenkins. The default+++ +++ behaviour in that case is to use+++ jenkinsdoc:SCM[] +++that was defined "last". If you+++ +++ want to override that behaviour, just register a new subclass of+++ ++++++ jenkinsdoc:InheritanceSelector[] +++that has+++ jenkinsdoc:SCM[] +++as the template type and+++ +++ returns a mode other than+++ jenkinsdoc:MODE#NOT_RESPONSIBLE[] +++fpr+++ jenkinsdoc:SCM[] +++in+++ ++++++ jenkinsdoc:#getModeFor(Class)[] +++.+++ +++ </p>
<p>+++ </p>


**Implementations:**

* plugin:project-inheritance[项目继承插件]: hudson.+++<wbr/>+++plugins.+++<wbr/>+++project_inheritance.+++<wbr/>+++projects.+++<wbr/>+++inheritance.+++<wbr/>+++**ParameterSelector** 
* plugin:promoted-builds[promoted builds Plugin]: hudson.+++<wbr/>+++plugins.+++<wbr/>+++promoted_builds.+++<wbr/>+++inheritance.+++<wbr/>+++**JobPropertyImplSelector** (link:https://github.com/jenkinsci/promoted-builds-plugin/search?q=JobPropertyImplSelector&type=Code[在 GitHub上查看])


## 重建参数过滤器
+jenkinsdoc:project-inheritance:hudson.plugins.project_inheritance.projects.rebuild.RebuildParameterFilter[]+

+++ This extension point allows you, to specify whether a given parameter+++ +++ should be included in a rebuild of a job, or not.+++ +++
<p>+++ +++ It can be used to remove automatically generated parameters, so that the+++ +++ rebuild can progress safely.+++ +++ </p>
<p>+++ +++ Each+++ jenkinsdoc:RebuildParameterFilter[] +++is called for each parameter of the+++ +++ previous build, that is about to be rebuilt. If any filter returns false+++ +++ when queried for+++ jenkinsdoc:#isParameterAllowed(ParameterValue)[] +++, the+++ +++ value is not copied into the new build.+++ +++ </p>
<p>+++ +++ Do note, that the parameter may still be present -- only that in these cases+++ +++ the default value from the project will be used, as if there were no+++ +++ value from the previous build.+++ +++ </p>
<p>+++ +++ Also do note, that the current rebuild implementation filters out all+++ +++ parameters, that are not+++ jenkinsdoc:StringParameterValue[] +++s (or subclasses). This+++ +++ is not guaranteed though, which is why this class accepts generic+++ ++++++ jenkinsdoc:ParameterValue[] +++s.+++ </p>


**Implementations:**

_(no known implementations)_


## 版本更改监听器
+jenkinsdoc:project-inheritance:hudson.plugins.project_inheritance.projects.versioning.VersionChangeListener[]+

+++ This class tracks whenever a change is done on show version related item.+++


**Implementations:**

_(no known implementations)_

