---
layout: developerextension
uneditable: true
---
:toc:
# YAML项目支持插件中定义的扩展点

plugin:yaml-project[YAML项目支持插件]

## 抽象限制
+jenkinsdoc:yaml-project:com.google.jenkins.plugins.dsl.restrict.AbstractRestriction[]+

+++ExtensionPoint for surfacing restrictions on what a DSL job can do. +++


**Implementations:**

* plugin:yaml-project[YAML项目支持插件]: com.+++<wbr/>+++google.+++<wbr/>+++jenkins.+++<wbr/>+++plugins.+++<wbr/>+++dsl.+++<wbr/>+++restrict.+++<wbr/>+++**AbstractPluginRestriction** 
* plugin:yaml-project[YAML Project support Plugin]: com.+++<wbr/>+++google.+++<wbr/>+++jenkins.+++<wbr/>+++plugins.+++<wbr/>+++dsl.+++<wbr/>+++restrict.+++<wbr/>+++**NoRestriction** 
* plugin:yaml-project[YAML Project support Plugin]: com.+++<wbr/>+++google.+++<wbr/>+++jenkins.+++<wbr/>+++plugins.+++<wbr/>+++dsl.+++<wbr/>+++restrict.+++<wbr/>+++**PluginBlacklist** 
* plugin:yaml-project[YAML Project support Plugin]: com.+++<wbr/>+++google.+++<wbr/>+++jenkins.+++<wbr/>+++plugins.+++<wbr/>+++dsl.+++<wbr/>+++restrict.+++<wbr/>+++**PluginWhitelist** 


## Yaml变换提供者
+jenkinsdoc:yaml-project:com.google.jenkins.plugins.dsl.tag.YamlTransformProvider[]+

+++ This+++ jenkinsdoc:ExtensionPoint[] +++serves as a means for plugins to augment+++ +++ the+++ jenkinsdoc:YamlTransform[] +++discovery process. The intended usage is:+++ +++
<pre><code>+++ +++   List&lt;YamlTransform&gt; list = YamlTransformProvider.get();+++ +++ </code></pre>+++ +++ This will delegate to the various extension implementations to+++ ++++++ jenkinsdoc:#provide()[] +++a+++ jenkinsdoc:List[] +++of requirements from things it+++ +++ understands how to discover.+++


**Implementations:**

* plugin:yaml-project[YAML项目支持插件]: com.+++<wbr/>+++google.+++<wbr/>+++jenkins.+++<wbr/>+++plugins.+++<wbr/>+++dsl.+++<wbr/>+++tag.+++<wbr/>+++**BuiltinYamlTransformProvider** 
* plugin:yaml-project[YAML Project support Plugin]: com.+++<wbr/>+++google.+++<wbr/>+++jenkins.+++<wbr/>+++plugins.+++<wbr/>+++dsl.+++<wbr/>+++tag.+++<wbr/>+++**DescribableYamlTransformProvider** 
* plugin:yaml-project[YAML Project support Plugin]: com.+++<wbr/>+++google.+++<wbr/>+++jenkins.+++<wbr/>+++plugins.+++<wbr/>+++dsl.+++<wbr/>+++tag.+++<wbr/>+++**DisplayNameYamlTransformProvider** 
* plugin:yaml-project[YAML Project support Plugin]: com.+++<wbr/>+++google.+++<wbr/>+++jenkins.+++<wbr/>+++plugins.+++<wbr/>+++dsl.+++<wbr/>+++tag.+++<wbr/>+++**KeyYamlTransformProvider** 

