---
layout: developerextension
uneditable: true
---
:toc:
# 在另一个Docker插件中定义的扩展点

plugin:yet-another-docker-plugin[另一个Docker插件]

## Docker云订单
+jenkinsdoc:yet-another-docker-plugin:com.github.kostyasha.yad.other.cloudorder.DockerCloudOrder[]+

_This extension point has no Javadoc documentation._

**Implementations:**

* plugin:yet-another-docker-plugin[另一个Docker插件]: com.+++<wbr/>+++github.+++<wbr/>+++kostyasha.+++<wbr/>+++yad.+++<wbr/>+++other.+++<wbr/>+++cloudorder.+++<wbr/>+++**AsIsDockerCloudOrder** 
* plugin:yet-another-docker-plugin[Yet Another Docker Plugin]: com.+++<wbr/>+++github.+++<wbr/>+++kostyasha.+++<wbr/>+++yad.+++<wbr/>+++other.+++<wbr/>+++cloudorder.+++<wbr/>+++**RandomLeastLoadedDockerCloudOrder** 


## YA Docker连接器
+jenkinsdoc:yet-another-docker-plugin:com.github.kostyasha.yad.connector.YADockerConnector[]+

+++ Different connectors to docker.+++ +++ DockerConnector appeared first so can't rename and YAD become parent.+++


**Implementations:**

* plugin:yet-another-docker-plugin[另一个Docker插件]: com.+++<wbr/>+++github.+++<wbr/>+++kostyasha.+++<wbr/>+++yad.+++<wbr/>+++connector.+++<wbr/>+++**CloudNameDockerConnector** 
* plugin:yet-another-docker-plugin[Yet Another Docker Plugin]: com.+++<wbr/>+++github.+++<wbr/>+++kostyasha.+++<wbr/>+++yad.+++<wbr/>+++connector.+++<wbr/>+++**CredentialsYADockerConnector** 
* plugin:yet-another-docker-plugin[Yet Another Docker Plugin]: com.+++<wbr/>+++github.+++<wbr/>+++kostyasha.+++<wbr/>+++yad.+++<wbr/>+++**DockerConnector** 

