---
layout: chapter
title: 安装Jenkins
---
ifdef::backend-html5[]
:notitle:
:description:
:sectanchors:
:toc:
:toclevels: 4
:imagesdir: ../resources
endif::[]


= jenkins安装

本节的步骤适用于单个/本地机器上的Jenkins新安装。


Jenkins通常作为一个独立的应用程序在其自己的流程中运行，
内置link:https://stackoverflow.com/questions/7213541/what-is-java-servlet[Java
                                 servlet] 容器/应用程序服务器（link:http://www.eclipse.org/jetty/[Jetty]）。

Jenkins也可以运行在不同的Java servlet容器(（如link:http://tomcat.apache.org/[Apache Tomcat]
或 link:https://javaee.github.io/glassfish/[GlassFish]）)中作为servlet运行.但是设置这些类型的安装的说明超出了本页的范围

*注意:*：尽管此页面重点关注Jenkins的本地安装，但此内容也可用于帮助在生产环境中设置Jenkins。


== 系统要求

最低推荐配置:

* 256MB可用内存
* 1GB可用磁盘空间(作为一个<<docker,Docker>>容器运行jenkins的话推荐10GB)

为小团队推荐的硬件配置:

* 1GB+可用内存
* 50 GB+ 可用磁盘空间

软件配置:

* Java 8--无论是Java运行时环境（JRE）还是Java开发工具包（JDK）都可以。

*注意:* 如果将Jenkins作为Docker 容器运行，这不是必需的


== 安装平台

本节介绍如何在不同的平台和操作系统上安装/运行Jenkins。


=== Docker

////
IMPORTANT: If you update content in this section, please ensure you check these
changes against the procedures documented in the sibling
'_run-jenkins-in-docker.adoc' file, which is used in the Tutorials of the
Jenkins User Documentation.
////


link:https://docs.docker.com/engine/docker-overview/[Docker]是一个在称为“容器”（或Docker容器）的孤立环境中可运行应用程序的平台。
像Jenkins这样的应用程序可以作为只读的“镜像”（或Docker镜像）下载，
每个镜像都作为容器在Docker中运行。Docker容器实际上是Docker镜像的“运行实例”。
从这个角度来看，镜像永久存储（只要镜像更新发布），而容器暂时存储。
在Docker文档的入门指南，link:https://docs.docker.com/get-started/[Getting Started, Part 1: Orientation
               and setup]页面中阅读有关这些概念的更多信息 。


Docker的基础平台和容器设计意味着可以在任何支持的操作系统（macOS，Linux和Windows）
或云服务（AWS和Azure）上运行单个Docker镜像（对于任何给定的应用程序，如Jenkins）。



==== 安装Docker


要在您的操作系统上安装Docker，请访问 link:https://store.docker.com/search?type=edition&offering=community[Docker
                      store]网站并单击适用于您的操作系统或云服务的*Docker Community Edition*框。
                      按照其网站上的安装说明进行操作。

Jenkins也可以在Docker企业版上运行，您可以通过 Docker商店网站上的*Docker EE*访问它。


[ CAUTION]
====
如果您要在基于Linux的操作系统上安装Docker，请确保配置Docker，以便它可以作为非root用户进行管理。
在Docker的link:https://docs.docker.com/engine/installation/linux/linux-postinstall/[Post-installation
        steps for Linux]网页中了解更多关于它 的文档。
        如何将Docker配置为默认启动的方式也可在此文档中查找。
====


==== 在Docker中下载并运行Jenkins

几个可用的Jenkins Docker镜像.

建议使用的Docker映像是link:https://hub.docker.com/r/jenkinsci/blueocean/[`jenkinsci/blueocean` image](来自 the link:https://hub.docker.com/[Docker Hub repository])。
该镜像包含当前的link:/download[长期支持 (LTS) 的Jenkins版本] （可以投入使用）
，捆绑了所有Blue Ocean插件和功能。这意味着你不需要单独安装Blue Ocean插件。


[NOTE]
====
jenkinsci/blueocean每次发布Blue Ocean新版本时，都会发布新镜像。您可以在link:https://hub.docker.com/r/jenkinsci/blueocean/tags/[标签]
 page页上看到以前发布的镜像版本列表 。

您还可以使用其他Jenkins Docker镜像（在Docker Hub上可通过link:https://hub.docker.com/r/jenkins/jenkins/[`jenkins/jenkins`]获取）。
但是，这些不会随Blue Ocean的发布而提供，需要通过
Jenkins中的link:../managing[*Manage Jenkins*] > link:../managing/plugins[*Manage Plugins*]页面进行安装。
在link:../blueocean/getting-started[Blue Ocean入门]中了解更多信息。
====

include::doc/book/installing/_docker.adoc[]


=== WAR文件

Jenkins的Web应用程序ARchive（WAR）文件版本可以安装在任何支持Java的操作系统或平台上。

*要下载并运行Jenkins的WAR文件版本，请执行以下操作:*

. 将link:http://mirrors.jenkins.io/war-stable/latest/jenkins.war[最新的稳定Jenkins WAR包]
下载到您计算机上的相应目录。
. 在下载的目录内打开一个终端/命令提示符窗口到。
. 运行命令java -jar jenkins.war
. 浏览http://localhost:8080并等到*Unlock Jenkins*页面出现。
. 继续使用<<setup-wizard,Post-installation setup wizard>>后面步骤设置向导。

将link:http://mirrors.jenkins.io/war-stable/latest/jenkins.war[最新的稳定Jenkins WAR包]下载到您计算机上的相应目录。

*Notes:*

* 不像在Docker中下载和运行有Blue Ocean的Jenkins，这个过程不会自动安装Blue Ocean功能，
    这将分别需要在jenkins上通过 link:../../book/managing[**Manage Jenkins**] > link:../../book/managing/plugins/[**Manage Plugins**]安装。
    在link:../../book/blueocean/getting-started/[Getting started with Blue Ocean]有关于安装Blue Ocean的详细信息 。.

* 您可以通过`--httpPort`在运行`java -jar jenkins.war`命令时指定选项来更改端口。例如，要通过端口9090访问Jenkins，请使用以下命令运行Jenkins：
  `java -jar jenkins.war --httpPort=9090`

=== 苹果系统

从网站安装的话使用这个包:

* link:http://mirrors.jenkins.io/osx/latest[Download the latest package]
* 打开包装并按照说明操作

Jenkins 也可以使用`brew`以下方式安装：

* 安装最新版本
[source,bash]
----
brew install jenkins
----

* 安装 LTS 版本
[source,bash]
----
brew install jenkins-lts
----


=== Linux


==== Debian/Ubuntu

在基于Debian的发行版（如Ubuntu）上，您可通过`apt`安装Jenkins

在link:https://pkg.jenkins.io/debian/[an apt repository]可获得最新版本，较老但稳定的LTS版本在link:https://pkg.jenkins.io/debian-stable/[this apt repository]这里可获得

[source,bash]
----
wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins
----

安装这个软件包将会：

* 将Jenkins设置为启动时启动的守护进程。查看`/etc/init.d/jenkins`获取更多细节
* 创建一个'`jenkins`'用户来运行此服务
* 直接将控制台日志输出到文件`/var/log/jenkins/jenkins.log`。如果您正在解决Jenkins问题，请检查此文件
* /etc/default/jenkins`为启动填充配置参数，例如JENKINS_HOME
* 将Jenkins设置为在端口8080上进行监听。使用浏览器访问此端口以开始配置

[NOTE]
====
如果你的`/etc/init.d/jenkins`文件无法启动Jenkins，编辑`/etc/default/jenkins`，
修改 `----HTTP_PORT=8080----`为`----HTTP_PORT=8081----`
 在这里，“8081”也可被换为其他可用端口。
====


=== Windows

从网站安装的话, 请使用安装程序：

* link:http://mirrors.jenkins.io/windows/latest[Download the latest package]
* 打开包装并按照说明操作


=== 其他操作系统



==== OpenIndiana Hipster

在运行link:http://www.openindiana.org/[OpenIndiana Hipster]的系统上 ，
可以使用link:https://en.wikipedia.org/wiki/Image_Packaging_System[Image Packaging
    System] (IPS)将Jenkins安装在本地或全局区域中 。

[IMPORTANT]
====
免责声明：这个平台不是由Jenkins团队正式支持的，使用它需要您自担风险。
本节中描述的打包和集成由OpenIndiana Hipster团队维护，捆绑通用的`jenkins.war` 到该操作环境中工作。
====

对于运行每周最新的版本包作为独立服务器这种常见情景，只需执行：
[source,bash]
----
pkg install jenkins
svcadm enable jenkins
----

上面命令将会发生：

* 创建一个`jenkins`用户来运行该服务并拥有其下的目录结构`/var/lib/jenkins`
* Pull the OpenJDK8 and other packages required to execute Jenkins, including
    the `jenkins-core-weekly` package with the latest `jenkins.war`

+
CAUTION: 长期支持（LTS）的Jenkins版本目前不支持基于OpenZFS的系统，因此目前没有提供包安装
* 将Jenkins设置为SMF服务实例（`svc:/network/http:jenkins`），然后可以使用上面的`svcadm`命令启用它。
* 设置Jenkins监听8080端口。
* 配置log输出文件`/var/svc/log/network-http:jenkins.log`,由SMF管理.

一旦jenkins运行，看log(`/var/svc/log/network-http:jenkins.log`)， 一般在
`/var/lib/jenkins/home/secrets/initialAdminPassword`里可以获取jenkins初始化的管理员密码.
 然后进入link:http://localhost:8080[localhost:8080] to <<setup-wizard, complete configuration of the
                                                     Jenkins instance>>来完成Jenkins实例的配置。
Jenkins instance>>.



要更改服务的属性（如环境变量JENKINS_HOME 或用于Jetty Web服务器的端口号），请使用`svccfg`：

[source,bash]
----
svccfg -s svc:/network/http:jenkins editprop
svcadm refresh svc:/network/http:jenkins
----

您还可以参考`/lib/svc/manifest/network/jenkins-standalone.xml`
获取有关当前支持的SMF服务可调参数的更多详细信息和评论。
请注意，由packaging创建的`jenkins`用户帐户有特殊的特权，允许绑定1024以下的端口号。


可用于OpenIndiana特定版本的Jenkins相关软件包的当前状态可以通过查询：

[source,bash]
----
pkg info -r '*jenkins*'
----

升级包可以通过更新整个操作环境来执行`pkg update`，或者专门针对Jenkins核心软件进行更新：


[source,bash]
----
pkg update jenkins-core-weekly
----

[CAUTION]
====
更新软件包的过程将重新启动当前运行的Jenkins进程。
如果确定需要更新，请确保在更新之前准备好关闭并完成所有正在运行的作业
====


==== Solaris, OmniOS, SmartOS, and other siblings

一般来说，应该满足：安装Java 8和link:/download[download] jenkins.war，
并运行它作为一个独立的进程或应用服务器，比如link:http://tomcat.apache.org[Apache Tomcat]。

一些注意事项:

* Headless JVM and fonts: For OpenJDK builds on minimalized-footprint systems,
  there may be
  link:https://wiki.jenkins.io/display/JENKINS/Jenkins+got+java.awt.headless+problem[issues
  running the headless JVM], because Jenkins needs some fonts to render certain
  pages.
  Headless模式JVM和字体：为了OpenJDK构建在占用空间最小的系统上，
  请看链接link:https://wiki.jenkins.io/display/JENKINS/Jenkins+got+java.awt.headless+problem[issues
                                              running the headless JVM]，
  因为Jenkins需要一些字体来渲染某些页面。
* ZFS相关的JVM崩溃:当Jenkins在`SunOS`系统上运行时，它会通过使用bundled`libzfs.jar`映射从Java到主机操作系统提供的`libzfs.so`尝试加载集成高级ZFS功能。
    不幸的是，该库是为了在操作系统中构建和捆绑的二进制实用程序，同时与它一起制作，
    并不是作为一个稳定界面显示给消费者的。作为Solaris遗留的分支，
    包括ZFS以及随后的OpenZFS计划的发展，许多不同的二进制功能签名由不同的主机操作系统提供。
    当Jenkins`libzfs.jar`调用错误的签名时，整个JVM进程崩溃`jenkins.war`自从发布2.55（至今尚未在任何LTS中）以来，提出并整合了一个解决方案。
    使管理员能够配置哪些功能签名应该用于已知具有不同变体的每个功能，
    将其应用于其应用程序服务器初始化选项，然后运行和更新通用而不需要进一步的解决方法。
    有关更多详细信息，请参阅 link:https://github.com/kohsuke/libzfs4j[the libzfs4j Git repository]，
    包括尝试使用脚本并“锁定”您特定分发所需的配置（特别是如果您的内核更新带来新的不兼容`libzfs.so`）。


另外请注意，OpenZFS计划的分支可能会在各种BSD，Linux和macOS发行版上提供ZFS。
一旦Jenkins支持检测ZFS功能，而不是依赖于SunOS检查，则应考虑上述与Jenkins集成ZFS的注意事项。

include::doc/book/installing/_setup-wizard.adoc[]
